### ISSUE TITLE
Organizations: Enable Creation

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#100]
Within the signup flow, you should have the option to create an organization, then you can create:

- an individual (admin) account **and** the organization (an individual should not be able to create an organization after the fact - and this is a very unlikely scenario given the payment structure).

This is the **only** way to create an organization.

Stuff to build/reuse from other components and screens:
- [x] Frontend
- [x] Input validation
- [x] GraphQL mutations

_Edited to reflect what was discussed in the meeting on June 2_

_Edited to reflect what was discussed on June 3_

**Comment by lucastbelem** [comment]
Not sure if this is where this comment should go, but here you go:

There should only be 2 ways to create organizations:
1. At sign up, when someone creates their org profile, through the sign up flow
2. When a Jesus Collective admin decides to create one (should be able to change ownership to that organization's admin, who may need to create their own profile) - this may happen when an individual partner decides to enrol their organization in Jesus Collective, as an example.

**Comment by GeorgeBellTMH** [comment]
Let’s discuss more this afternoon.

Sent from my iPhone

On Jun 2, 2020, at 8:59 AM, lucastbelem <notifications@github.com> wrote:

﻿

Not sure if this is where this comment should go, but here you go:

There should only be 2 ways to create organizations:

  1.  At sign up, when someone creates their org profile, through the sign up flow
  2.  When a Jesus Collective admin decides to create one (should be able to change ownership to that organization's admin, who may need to create their own profile) - this may happen when an individual partner decides to enrol their organization in Jesus Collective, as an example.
