### ISSUE TITLE
Organizations: Invite Members and Handle Join Requests

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#104]
* [ ] Lambda function via HTTPs trigger to send email using the Pinpoint API, create a new user that is connected to the organization
* [x] Verify no-reply@jesuscollective.com in Pinpoint
* [ ] Build frontend interface (likely within Account Settings) for organization admins to send invites to new users via email
* [ ] Add security with Cognito to ensure only authorized users can trigger the Lambda (probably need to read from DynamoDB to ensure the current requesting user is the superAdmin or an admin)
* [ ] Create simple HTML template (probably [handlebars](https://handlebarsjs.com/))

Admins need to be able to invite members and accept/reject join requests. 

Additional: admins should be able to send email invites (this is probably for later).

Edit: we don't really know if people can request to join an org (see #127).

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713130118)

**Comment by GeorgeBellTMH** [comment]
Emails/alerts can be done via pinpoint which is part of amplify...I've only tested it via the amazon web interface - but I believe there is an api as well...it also allows for texting and phone calls! We can do a call at some point and I can show you all the stuff it can do...very fun...

**Comment by GeorgeBellTMH** [comment]
More likely though via lambda...since we are emailing people who are not in pinpoint.

**Comment by JonEsparaz** [comment]
> More likely though via lambda...since we are emailing people who are not in pinpoint.

SES?

**Comment by GeorgeBellTMH** [comment]
https://aws.amazon.com/ses/
https://aws.amazon.com/pinpoint/



Sent from my iPhone

On Jun 2, 2020, at 3:30 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

More likely though via lambda...since we are emailing people who are not in pinpoint.

SES?

**Comment by JonEsparaz** [comment]
I'd like to get started with this sooner rather than later. @GeorgeBellTMH let me know what you think of the plan I add in the first comment.

**Comment by GeorgeBellTMH** [comment]
Yup... I have emails working in the lambdas now. Just take a look at the DM one. 

I was having trouble authenticating correctly without using a user - there is an example without a password in the other lambda....I have to setup secrets on Amazon so the password is added as an env variable. But for now I am just hardcoding the password when I publish. 

I think you can either do it as a trigger when you add to an invite table, or you could do it as an API function that writes to the table and sends the email. But you are correct they need to be logged in to send it...and probably we need to throttle them - only one invite sent to an email every week or something.

**Comment by GeorgeBellTMH** [comment]
I am delivering CRM v0.1 that has ability to invite users...

**Comment by GeorgeBellTMH** [comment]
Just realized that this is really an admin only function for now, since it relies on admin query....hmmm...
