### ISSUE TITLE
Jr High series page loading incorrectly

### ISSUE THREAD

**Issue by laurengermain** [jesus-collective/mobile#1049]
The Junior High Midweek series page for Matthew Get Up switches to Kids Matthew Get Up (or Jr High Weekend) any time the page is refreshed or the original link is copy/pasted into the browser.

1. Go to 'https://beta.jesuscollective.com/app/resource?create=false&id=resource-1611326161952'
1. Click on 'Jr High Midweek'
1. Scroll down to 'Year 2' and select 'Matthew Get Up'
1. Refresh the page
1. See error (switches to Kids series page)

 AND

1. Copy/paste Jr High Midweek series page link into a new browser window: https://beta.jesuscollective.com/app/resourcedisplay/resource-1611326161952?resource=00adbc2d-53e4-4cda-a14a-d7cc923f0d1b&series=57d41eb0-78e7-4d25-b7ac-386c222779e8
1. See error (appears as Jr High Weekend)

**Expected behavior**
When the Jr High Midweek series page is refreshed or copy/pasted into a new browser window, it needs to stay on the Jr High Midweek series page instead of switching to Kids or Jr High Weekend.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=790723609)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this one is urgent. Could you please take a look?

**Comment by GeorgeBellTMH** [comment]
I did 1-5 and it works fine for me...in safari...

I believe the link should be: https://beta.jesuscollective.com/app/resourcedisplay/resource-1611326161952?resource=4b0b01b7-062b-4536-9114-c75577bc17b5&series=6c0366db-3a92-4504-9c21-d7c051644a18
