### ISSUE TITLE
Delete card with issue

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1057]
GeorgeBellTMH can you pls delete this card? We can't do it for some reason. It's in the resource "Diversity and Inclusion" here: https://beta.jesuscollective.com/app/resource?groupType=null&id=resource-1633450967064&create=false.

![](https://user-images.githubusercontent.com/48295718/145271356-04897809-fb76-4ed9-b86d-4ac8d8cac7d3.png)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=808315951)

**Comment by lucastbelem** [comment]
Please note that there is a second card in this resource called "Dispersing Power". That one should stay.

**Comment by lucastbelem** [comment]
@laurengermain can you pls verify if this is fixed?

**Comment by laurengermain** [comment]
Fixed -- there is only 1 card with that title.
![Screen Shot 2022-12-16 at 1 27 52 PM](https://user-images.githubusercontent.com/89869101/208164824-19d5f5d1-83ef-4f6c-8929-e073b399f28b.png)
