### ISSUE TITLE
OS sign in flow changes - priority #1

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1059]
Changes needed for the One Story sign in/sign up flow:

* [x] Create new yellow graphic
* [x] Upload new yellow graphic
* [x] Update slogan to OS slogan (Made by a church. Made for your church.)
* [x] Change buttons from red to OS yellow)
* [x] Change button text from white to black)
* [x] Remove JC logo
* [ ] Upload black OS logo
* [x] Remove "welcome" paragraph from sign in screen and from the "individual or org" page
* [x] On org account creation page, change "Set up the account for the administrator of your organization first" to "Create Your Account"

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=812818332)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH graphic on #1060

**Comment by GeorgeBellTMH** [comment]
@lucastbelem I need the logo as transparent png with dimensions: 2000 × 549

**Comment by GeorgeBellTMH** [comment]
use ?brand=oneStory on dev to see changes so far...

**Comment by GeorgeBellTMH** [comment]
I think I will also need to get new images for the login phases that work against the yellow...

**Comment by GeorgeBellTMH** [comment]
Closing, just need the images - making a new ticket
