### ISSUE TITLE
New OS graphic

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1060]
If you go to onestorycurriculum.com and look at the collage of images, you'll see an image of a girl holding a red balloon.

* [ ] Can you please take the graphic below and remake it with:
* [ ] the picture of the girl holding the red balloon
* [ ] with a yellow overlay instead of red (the One Story yellow)
* [ ] Then send it to George pls?
Thank you!
![leftPanel 5df737e1](https://user-images.githubusercontent.com/48295718/146474803-0b2c3278-ca4b-4809-a90f-06820280f0e5.png)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=813912344)

**Comment by laurengermain** [comment]
Hey @GeorgeBellTMH here is the graphic.
![OS_Graphic](https://user-images.githubusercontent.com/89869101/146572098-87d84a01-971c-499f-8a92-f94a40f6ac9e.jpg)
