### ISSUE TITLE
Facelift login

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1062]
When users enter their verification codes, they get an error message.
![](https://user-images.githubusercontent.com/48295718/147124868-5e0984a2-e22a-4e09-aede-fc158c24da83.png)

Then I click "submit" again and get this error:
![](https://user-images.githubusercontent.com/48295718/147124899-d57e01ff-a61f-4293-bdc8-2156561d8fc8.png)

Then I go back to the login and screen and just login and it works.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=816453497)

**Comment by GeorgeBellTMH** [comment]
I think it’s missing a group, I’ll take a look at it…for now just permit them from Cognito.

**Comment by lucastbelem** [comment]
Ok will do that.

**Comment by lucastbelem** [comment]
@laurengermain could you pls see if this is still an issue?

**Comment by laurengermain** [comment]
No longer an issue
