### ISSUE TITLE
Alternative profile fields for non-partner sign ups - priority #3

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1063]
Specifically, this is for One Story, but will apply to other products that will follow the same flow as One Story (i.e. Friends a la carte). We're hoping to launch friends a la carte in mid January and it'd be great to have this profile stuff sorted out before the conference in the US (**starts Jan 11**). Below are the profile fields we want to show for this:

* Name
* Email
* Address
* Phone Number
* Current Role
* One Sentence about me (we don't actually need this long term, but since the map UI requires it, we can still ask for it for now)
* Org name
* About us (optional)
* Type of org
* Denomination (optional)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=817223226)

**Comment by GeorgeBellTMH** [comment]
I want to confirm that you don't want (even optionally):
1) A Photo (basically they will always appear as ghost heads)
2) A map location (not sure yet what this will do...)

**Comment by lucastbelem** [comment]
I think we discussed this on the phone after Jan 2 and decided yes to photo and yes to map optionally, but not required and not displayed by default.

**Comment by lucastbelem** [comment]
Closing for a duplicate.
