### ISSUE TITLE
Improvements to products - priority #2

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1064]
* [x] Ability to invite users to sign up flows for a particular product (i.e. one story, partnership, a la carte friends, etc). Right now we can only invite to the platform, which defaults to One Story.
* [x] Similarly, these sign up flows should have specific urls for when a user clicks "buy this" on the JC marketing site (like we already do for One Story, but we'd like to be able to do this for any product)
* [x] Ability to customize the info that appears on the product summary card when creating the product in admin.
* [x] Ability for admins to indicate which products should bypass the dashboard (i.e. land the user directly in the resource as is the case with One Story)

This is also ideally ready by mid January. @GeorgeBellTMH does this seem reasonable?

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=817226177)

**Comment by GeorgeBellTMH** [comment]
Can you give me some examples of what you want the product cards to look like?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this is the same card that already exists for One Story. I'm just looking to be able to customize it. For example, for most products, I might not need a question box (i.e. how many kids?), but instead will just have a written summary of the product. I may not need an EULA, etc.

**Comment by GeorgeBellTMH** [comment]
K...I'm going to add this to the tests to see how much customization is currently available...
