### ISSUE TITLE
Improvements to products - priority #4

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1065]
* [ ] Ability to create $0 products that don't require the user to enter their payment info (for context, this is our idea for accommodating a free version of One Story (and other products) that are limited, but that allow the user easier and quicker access to the platform. This is a stretch goal.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=817226346)

**Comment by GeorgeBellTMH** [comment]
Have you tried making 0$ products in stripe?

I think this should be possible already...

**Comment by lucastbelem** [comment]
No longer relevant.
