### ISSUE TITLE
A la carte permissioning/groups

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1067]
We need to figure out how to allocate groups for people who purchase these a la carte friendship products. Do we create a new Cognito group for every product we create? Every resource we create?

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=817229803)

**Comment by GeorgeBellTMH** [comment]
So I think the way this should be setup...

1) Create a product, enabled, show on login, is org tier and is individual tier
2) Set the ID - we will use it later
3) Set price and Is Stripe
4) Groups: verifiedUsers, friends, [ala-name of product]

Setup the page to be visible to people in the following groups:
[ala-name of product]
either subscriptionPartners or subscriptionky[all three of them]

The link should be:
auth/signin?brand=jc|oneStory&joinedProduct=[id from step 2]

**Comment by GeorgeBellTMH** [comment]
We can do a walk through of this on Tuesday if you want...

**Comment by GeorgeBellTMH** [comment]
I am thinking about this a bit more...I think I might create a few automated tests so that we can ensure these are always working...
