### ISSUE TITLE
A few more changes for resources/sign in

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1073]
Can we please hide the following elements from the main menu for anyone who is **not a partner or an admin**:

* Events directory
* Groups directory
* Resource directory
* Message icon

Can you please hide the "back" button on [this screen](https://beta.jesuscollective.com/auth/signup?brand=oneStory&joinedAs=organization) for only One Story brand sign in?

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=825702906)

**Comment by GeorgeBellTMH** [comment]
My plan is to make the menu customizable from the admin screen…you will be able to do the following:

Set top menu items
Set sub menu items
Reorder items

For all menu items you will be able to set visibility for groups and where it should go

This should give you guys more control going forward…

**Comment by lucastbelem** [comment]
@GeorgeBellTMH that is spectacular! How much time do you need for this work? A day? A week? A month?

If it's on the later end of the time frames, could you hide them temporarily so we can get the experience improved as quickly as possible? Obviously if this is a quick switch over, it may be worth just giving us customization capabilities instead.

**Comment by lucastbelem** [comment]
Closing this for #1079
