### ISSUE TITLE
Sign in issue

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#108]
@lucastbelem mentioned that people are having trouble getting past the sign in page.

I just experienced that pressing Enter doesn't do anything. We might need to add a key binding, but this is a likely "cause" of the issue.

OS: Windows 10
Browser: Firefox, Chrome, Edge.

**Comment by GeorgeBellTMH** [comment]
Also safari...

**Comment by JonEsparaz** [comment]
Just noting that this is probably impossible until Expo fixes some stuff.

**Comment by lucastbelem** [comment]
What does this mean, guys? If a user on one of the mentioned browsers who has Windows 10 won't be able to sign up properly?

**Comment by JonEsparaz** [comment]
No, no. They will be able to sign in if they _click_ the sign in button. This issue is that pressing enter on your keyboard doesn’t do what you expect (ie sign you in).

**Comment by lucastbelem** [comment]
Gotcha.
