### ISSUE TITLE
Double menus

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1091]
In the facelift environment, if I go to courses, 2 menus appear.
![](https://user-images.githubusercontent.com/48295718/152459193-d7d06ef8-ba1d-46a5-93ae-cd1b20f87725.png)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=839118550)

**Comment by GeorgeBellTMH** [comment]
I think you mean @itbel

**Comment by lucastbelem** [comment]
Yeah, sorry!
