### ISSUE TITLE
Remove old messaging icon from secondary nav of courses - facelift

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1092]
We added this before because we didn't have that in the top nav. Can you pls remove the envelope icon from the dark grey menu bar of courses?
![](https://user-images.githubusercontent.com/48295718/152462702-1ccd220d-460f-482d-95dc-97676bcee18c.png)

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=839128317)

**Comment by GeorgeBellTMH** [comment]
I think this is going to have to get redesigned...double logo...black vs white...

I think it probably makes more sense with the weeks on the left now...under home....

Or we should just get rid of the white menu altogether in courses....

**Comment by lucastbelem** [comment]
@GeorgeBellTMH  I like your thinking here. 3 menus is crazy. I'm on the fence about which menu area to get rid of - the vertical menu or the horizontal grey menu. 

I'd like to suggest that we get rid of the vertical menu (and the black bar altogether) and then shift everything to the left. This will create a ton of space for the course itself.

Then we keep the grey horizontal menu, but add Home there (courses can go away) and remove the envelope icon too. 

Or we can get rid of the grey horizontal menu and keep the left instead and add weeks there. But I definitely like the idea of keeping the top white menu there so the user always has a way out of the course that's clear and easy.

@chrstygratton thoughts?

**Comment by lucastbelem** [comment]
- [ ] Remove top level (white menu)
- [ ] Switch envelope icon for airplane
