### ISSUE TITLE
Cross user type visibility

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1104]
Something is up with user visibility in beta.<br/><br/>With the curriculum permissions I should only see curriculum users, but I do see partners (who don&#x27;t have curriculum permissions). <br/>Then with the partner permission I see partners, but not all, and I do see curriculum users as well. I.e. one partner from Brazil seems to only appear on the map when I only have curriculum permissions.<br/><br/>Here is how we need this thing to work for both the map and the directory:<br/><br/><ul><li><label><input type="checkbox"  />As a user type I want to see only those in my own user type so I can easily navigate the platform and connect with people that are most aligned with me and my reason for being on the platform.</label></li></ul>

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=844786242)

**Comment by lucastbelem** [comment]
I tagged @GeorgeBellTMH because he has the most context and knowledge of this area, but it'd be great if @itbel could tackle this so George can stay focused on sign in and payment flows.

**Comment by GeorgeBellTMH** [comment]
Note, I'd like to make this an admin thing...

I'm not fully sure how it will work, but there aren't specifically user groups, there is a user hierarchy...

Admin
Partners
Kids and youth
One offs 
Future groups

Id like the logic for it to be easy to change and those changes to be done automatically across the platform...

**Comment by lucastbelem** [comment]
Love it!

It's like one of those permission pages on a pre-built website, like Craft or Wordpress where you get to decide what each kind of users sees and does. We should talk about what this interface would look and function like.

But in the meantime, is there a quicker solution for when we release the facelift so that partners can only see partners? This is the key factor because I'm gonna hide menu items from other users anyways, so if their maps are inaccurate, it won't matter. But it will for partners.

**Comment by GeorgeBellTMH** [comment]
Actually think it will be easier to develop it than do that…give me a bit to come up with a plan…

**Comment by lucastbelem** [comment]
CLosing for #1256
