### ISSUE TITLE
Sending a message isn't working

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1107]
When I click "send message" on a person's profile tile in the people directory, it takes me to the correct place (the DM screen) but no message is initiated. 

Priority 1

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=848136523)

**Comment by GeorgeBellTMH** [comment]
This might be just a delay issue...it takes some time to figure out if an existing message room exists...it's gotta check them all...we may need to put a "loading..." screen up instead while we figure out if it exists...

**Comment by itbel** [comment]
There's a check that is preventing shouldCreateRoom() from running when the user has no conversations. I'm working on it.
