### ISSUE TITLE
Footer: Styling and Functionality

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#112]
Links look a little funky and all go to the events page.

**Comment by GeorgeBellTMH** [comment]
Some of these should link to the main website (www.jesuscollective.com)...

**Comment by lucastbelem** [comment]
The bolded titles should be headers, not actual links. What's below the headers are links. Here is where each link should go:

**About Us**
Who we are: jesuscollective.com
Our Mission: jesuscollective.com/discover
Team: jesuscollective.com/team

**Events** (need to add 2 links below)
My Events: a page with all of my events. For now, it can probably just go the person's dashboard
Recommended: Doesn't exist yet, so we can leave it out

**Groups** (need to add 2 links below)
My Groups: Same as my events, but for groups.
Recommended: Same as events, but for groups

**Resources** (need to add 1 link below)
Kids and Youth Curriculum: Straight into the Curriculum Resource overview page

Contact Us
Connect with Us: mailto:connect@jesuscollective.com
Get Involved (I'm not sure yet what this is supposed to do.

**Comment by JonEsparaz** [comment]
@mmacedom I activated the links in #139. Once it's merged, you can make the styling changes.

@lucastbelem I made my events and my groups go to all events and all groups for now since the footer only shows up on the dashboard, so the link didn't go anywhere.

**Comment by mmacedom** [comment]
Thanks @JonEsparaz for activating the links.

**Comment by mmacedom** [comment]
@lucastbelem the footer has been styled.

**Comment by JonEsparaz** [comment]
Looks great @mmacedom!

**Comment by mmacedom** [comment]
Thanks @JonEsparaz! Cheers
