### ISSUE TITLE
Creating a thread with an empty discussion board appends one duplicate thread

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1127]
Creating a thread with an empty discussion board appends one duplicate thread (only when empty), disappears on refresh.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=849403700)

**Comment by lucastbelem** [comment]
@itbel did you fix this?

**Comment by itbel** [comment]
not yet

**Comment by itbel** [comment]
This appears to have been fixed.
