### ISSUE TITLE
Resources are not accessible

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1164]
Users are reporting that they are not being able to access One Story content. For example, the "Mark Because Jesus" series in Junior High weekend...when you click on it, it just takes the user to the dashboard.
I wonder if it's something to do with urls or startups?

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=852281523)

**Comment by lucastbelem** [comment]
Woah...I went to Cognito to check the permissions for this user...turns out the user reporting this issue doesn't have ANY groups assigned to them and is an UNCONFIRMED user...How's that even possible?

**Comment by GeorgeBellTMH** [comment]
Ok…did they just create their account?

There is a problem with the adding of groups on prod…I have a fix that will go with this chunk…and we will rerun the hook so they get their groups…

G

**Comment by lucastbelem** [comment]
Nah, they created in December. 

But, I think I figured out that the account I looked at in Cognito is an Org account. Could that be it too?

**Comment by lucastbelem** [comment]
I tested it myself and I'm having the same issue. The series is accessible in the list view, but not in the manual card (where a url was pasted for the series). Maybe the app vs beta thing?

**Comment by lucastbelem** [comment]
Here is what happens when I try to change the card from manual to auto:
<img width="1434" alt="Screen Shot 2022-02-28 at 2 22 15 PM" src="https://user-images.githubusercontent.com/48295718/156045705-23c0a5c5-9c91-4cf0-941c-412b54169135.png">

**Comment by lucastbelem** [comment]
I think I got a partial fix on this. The current url for manual cards includes https://beta.jesuscollective.com/**web**/resourcedisplay/resource-1611326161952...

I changed it to https://beta.jesuscollective.com/**app**/resourcedisplay/resource-1611326161952...

That seems to have done the trick.

However, the issue remains that changing manual to auto cards and trying to select a series results in the above screenshot. 

Note that the immediate/urgent issue is resolved.

**Comment by lucastbelem** [comment]
@laurengermain could you pls make it a priority to tomorrow to change the target url for all manual cards to reflect the information above?

**Comment by laurengermain** [comment]
@lucastbelem done -- all the cards seem to be working now.
