### ISSUE TITLE
Resources: Join/Delete/Leave styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#117]
When looking at resources, we have the same initial problem as in events where all buttons show up at once rather than "join" when I haven't joined, or "leave" when I haven't left.

**Comment by mmacedom** [comment]
@lucastbelem this is a functionality issue. Perhaps @GeorgeBellTMH or Jon are working on it?

**Comment by GeorgeBellTMH** [comment]
It's fixed.
