### ISSUE TITLE
Make payment processing page button configurable

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1188]
We need to change this text from "process payment" to "proceed".

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=880201171)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH where are we with this one?

**Comment by GeorgeBellTMH** [comment]
This is done. Please test (button text on admin screen needs to be setup)
