### ISSUE TITLE
Chat in app

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#1195]
Would be cool to include the YouTube chat in the app along side the notes...This could be used on Sunday mornings to chat in real-time while the service is happening.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=892507209)

**Comment by GeorgeBellTMH** [comment]
Should be done using the YouTube api instead of the chat embed i think - so it looks native.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH Why did you close this? No good?

**Comment by lucastbelem** [comment]
Nevermind...I know why you closed it lol
