### ISSUE TITLE
Resource: Editing title and description not working

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#121]
I tried to update the kids and youth information in the resource but the editor isn't working properly. When I type, my input disappears immediately. However, if I press "enter" fast enough, my edit saves.

**Comment by GeorgeBellTMH** [comment]
Still some bugs…please don’t edit kids and youth…edit podcasts only…

**Comment by lucastbelem** [comment]
Sounds good. Do you want me to edit podcasts as a place to test? With our time crunch, and podcasts not being a priority, I'd rather not spend too much time on it. However, if you're saying that podcasts is ready for editing, and bugs found there will influence bugs we find on Kids and youth, I'm happy to do it.

Thoughts?

**Comment by GeorgeBellTMH** [comment]
Ya, just don’t edit kids and youth until we are sure the editing works…re-importing it will be a pain…

Testing in podcasts, you can do whatever you want there…we will delete it on fridya…

**Comment by lucastbelem** [comment]
Ok. Testing/editing podcasts will be useful for this week's launch though?
