### ISSUE TITLE
Replace react-chips with react-native-dropdown-picker

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#1211]
When you do the work on the user selector, can you replace react-chips with react-native-dropdown-picker...

I think it might work better...it has ability to do search and picking...

I'd like to replace it since it hasn't been maintained, and it's holding us back from a bunch of upgrades...

Let me know when you are going to start on this...I will check in the mass of changes that bring react-native-dropdown-picker up to date, and then you can use the new features...

**Comment by GeorgeBellTMH** [comment]
I've rewritten most of the resource components as functions...

**Comment by GeorgeBellTMH** [comment]
And working on moving the pickers to use react-native-dropdown-picker...so we only have the one dependency...

**Comment by itbel** [comment]
Sounds good. I can look into this tomorrow.

**Comment by GeorgeBellTMH** [comment]
I've checked everything in...

**Comment by itbel** [comment]
What do you need me to do for this? react-chips package is no longer in use as per your latest commits.

**Comment by GeorgeBellTMH** [comment]
I commented it out...so we need to duplicate the functionality but with react-native-dropdown-picker...

Basically the deal is it should allow you to type user names in, then provide suggestions, if the user clicks on it, then it should become a chip..

Something like this:

<img width="260" alt="Screenshot 2022-08-09 at 1 42 46 PM" src="https://user-images.githubusercontent.com/47749730/183756990-87ae3b9a-f18b-4892-b306-2eb3182ff963.png">
.

**Comment by GeorgeBellTMH** [comment]
Ideally we use the elastic search functionality instead of downloading a list of all the users...

**Comment by GeorgeBellTMH** [comment]
Bonus marks if you can get the user profile images in there...

**Comment by itbel** [comment]
Okay got it.

**Comment by GeorgeBellTMH** [comment]
And extra bonus marks if you can then implement it on the message board as well (so people can message multiple people at once....similar to a To: )
