### ISSUE TITLE
Replace content with scrollview (ensure scrolling works correctly in forms, tables and all other screens)

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1222]

**Comment by lucastbelem** [comment]
Accidental issue.

**Comment by lucastbelem** [comment]
When I click a directory, sometimes I cannot scroll down. I'm able to tab through the page, and then once I tab through and the page moves down to show me my current selection, I'm then (sometimes) able to scroll again. It's intermittent and occurs on different pages, although I've only seen it on directory pages.

**Comment by itbel** [comment]
I have not been successful at replicating this issue...

**Comment by itbel** [comment]
This issue appears to be fixed... @lucastbelem
