### ISSUE TITLE
Card sizes and layout are off inside resources (Dev environment)

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1223]
@itbel please prioritize this.

<img width="1436" alt="Screen Shot 2022-08-17 at 10 43 16 PM" src="https://user-images.githubusercontent.com/48295718/185273657-33505313-72aa-47f7-b9c1-e3600893f731.png">

**Comment by lucastbelem** [comment]
@itbel part of course UI, but the content within the card is also wonky in courses....
<img width="744" alt="Screen Shot 2022-08-24 at 11 24 37 AM" src="https://user-images.githubusercontent.com/48295718/186443887-aceca6fd-c420-40e3-b003-1e8666d0a449.png">

**Comment by itbel** [comment]
Should be fixed in #1230
