### ISSUE TITLE
Resource download buttons not downloading correctly - Dev

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1224]
If I go to a resource in Dev (i.e. My Curriculum Test), and click on Kids, Son of God, and click the "download" for "The Greatest", instead of downloading the main file or showing the drop down, instead, I see the following:
<img width="1437" alt="Screen Shot 2022-08-17 at 10 51 10 PM" src="https://user-images.githubusercontent.com/48295718/185274833-2a13942d-aac4-445d-9fb1-4f2587b3ee2f.png">

**Comment by GeorgeBellTMH** [comment]
This is working now, will publish shortly
