### ISSUE TITLE
New CRM intermittently regressing

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1247]
User navigates to CRM and gets the new CRM. Then user navigates away and upon returning the CRM that appears is the old one (the one where all data loads at once).

**Comment by itbel** [comment]
I have been unable to replicate this issue... can you confirm it still occurs on a different browser?

**Comment by lucastbelem** [comment]
@itbel can't confirm cause it's intermittent...@ZulemaTMH would you be able to test on Firefox? 

@GeorgeBellTMH 
Could we clear cache centrally to see if it solves the issue? It's not just CRM...events and groups intermittently appear as well.

**Comment by lucastbelem** [comment]
Zulema confirmed that clearing cache solved the problem... she'll test throughout the day to be sure. But @GeorgeBellTMH if you could still check our caching settings just to make sure everything is fine that'd be good...just cause it seems like it took a bit too long for cache to clear.

**Comment by GeorgeBellTMH** [comment]
Cache is always cleared…I wonder if the browsers cache is just overdoing it…Sent from my iPhoneOn Sep 7, 2022, at 2:12 PM, Lucas Belem ***@***.***> wrote:﻿
@itbel can't confirm cause it's ***@***.*** would you be able to test on Firefox?
@GeorgeBellTMH
Could we clear cache centrally to see if it solves the issue? It's not just CRM...events and groups intermittently appear as well.
