### ISSUE TITLE
Header/Footer Logo Resolution

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#125]
Pretty minor, but the JC logo has some sort of resolution issue. Should be fixed before a public launch.

**Comment by GeorgeBellTMH** [comment]
The current one is white on transparent png and 156x43...

@lucastbelem can we get a better version? Maybe 2x the size....still white on transparent.

**Comment by JonEsparaz** [comment]
@lucastbelem just want to bump this. For future use, is there a Google Drive folder with all the Jesus Collective logos we can get access to?

**Comment by lucastbelem** [comment]
Logos [here](https://drive.google.com/drive/folders/14hH7urFN6oSeiTafRLz32k9B62Ni4Xsv)...but they may not be much bigger.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can you try replacing the logo with this?
![JC-Logo-RGB-KO2](https://user-images.githubusercontent.com/48295718/112902624-66508c80-90b4-11eb-97b8-cb51470d36c0.png)
