### ISSUE TITLE
Map not loading properly

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#1257]
<img width="1440" alt="Screen Shot 2022-09-14 at 1 01 41 PM" src="https://user-images.githubusercontent.com/48295718/190204933-1dab6a0c-a462-4f9f-9620-02ab3a00e908.png">

**Comment by lucastbelem** [comment]
@itbel @GeorgeBellTMH can you pls indicate cause?

**Comment by GeorgeBellTMH** [comment]
I may have fixed this when I deployed...can someone check?

**Comment by laurengermain** [comment]
> I may have fixed this when I deployed...can someone check?

Seems to be working! 
![Screen Shot 2023-01-03 at 10 13 57 AM](https://user-images.githubusercontent.com/89869101/210385682-452246b6-0fad-4634-9ad4-2a45f0567588.png)
