### ISSUE TITLE
Map: Toggle Default

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#130]
This isn't necessarily an actionable issue, but I wanted to log it. We need to talk about whether the map should default to open or closed. The design would suggest it should default to open, but it kind of takes over the dashboard screen when that's the case, so it may not be ideal. Unless we made it so that when toggled on, it also disappears when scrolled.

**Comment by GeorgeBellTMH** [comment]
My preference is to keep it closed by default, especially early on when there aren't a lot of items on the map.
