### ISSUE TITLE
Events: Time Zones

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#136]
Since Jesus Collective is global, we need the ability to set time zones in events.

**Comment by JonEsparaz** [comment]
@lucastbelem don't know if you missed George's comment: https://github.com/jesus-collective/mobile/pull/138#issuecomment-639382744

**Comment by lucastbelem** [comment]
Yeah. I agree with his comments. User timezone displayed is best. But I would still prefer to actually display the timezone (i.e. EST) wherever they are so it's not confusing. I.e. Is it 10am here in Australia or 10am in Canada?

**Comment by JonEsparaz** [comment]
Ok sounds good. On the top of my list for this week.

**Comment by JonEsparaz** [comment]
> Yeah. I agree with his comments. User timezone displayed is best. But I would still prefer to actually display the timezone (i.e. EST) wherever they are so it's not confusing. I.e. Is it 10am here in Australia or 10am in Canada?

Date/time now displays in the user's time zone with the time zone code to reduce ambiguity. Exception: on EventScreen, the event organizer views the time _exactly_ as they set it. This is to prevent event organizers from getting confused if say they set the time as 10:00am (PST), then the next time they open the page it shows up as 1:00pm (EST).
