### ISSUE TITLE
Style: No Members Yet text can be smaller

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#152]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/47749730/83950711-d2e35d80-a7fa-11ea-95a0-3f3de0607165.png">

This is on groups, resources, events pages...

**Comment by mmacedom** [comment]
@GeorgeBellTMH @lucastbelem This has been fixed. The font size has been reduced from 20px to 16px.
