### ISSUE TITLE
Style: Mobile issues on homepage

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#153]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/47749730/83950832-919f7d80-a7fb-11ea-9720-04dd9f4e5580.png">

- [x] People you may connect with is on top of groups
- [ ] We likely need to come up with a different design for Show All, My Events, Previous Events and Create Event - since this doesn't really fit on the page anymore

**Comment by lucastbelem** [comment]
For the second point @GeorgeBellTMH mentioned, could a simple views dropdown work?

**Comment by JonEsparaz** [comment]
> For the second point @GeorgeBellTMH mentioned, could a simple views dropdown work?

This is probably best. We also need a dropdown for #120.

**Comment by mmacedom** [comment]
@GeorgeBellTMH @JonEsparaz Do you recommend using <Picker> for this drop down or do we have any other already existing drop down component that we can use here? 

@GeorgeBellTMH Are you still seeing "People you want to connect with" above Groups on your machine? I haven't been able to replicate it on my local.

**Comment by mmacedom** [comment]
@GeorgeBellTMH I just checked the positioning of the components on Safari mobile with the dev tools and everything is where they are supposed to be, i.e Conversations is at the very [bottom
<img width="951" alt="Screen Shot 2020-06-11 at 10 45 13 PM" src="https://user-images.githubusercontent.com/24467324/84459377-4ccd7980-ac35-11ea-8e0d-fd9a90372797.png">

**Comment by GeorgeBellTMH** [comment]
Closing for #325
