### ISSUE TITLE
Map: set initial centre as user's location

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#154]
Initial centre is always Toronto(ish) for most map views. Would make sense if we centre the map at the user's "home" location.

- [x] Setup google api and key for map service
- [x] Change credit card
- [x] Setup limits
- [x] Center map at users location
- [ ] Allow user to drag/change location (without using the popup)
- [ ] Allow for reverse lookup of location name
- [ ] Remove the set/change button on left side of profile
- [ ] Make current user's marker one of these:
<img src=https://user-images.githubusercontent.com/48423418/84194731-78046d00-aa6b-11ea-81a3-fb31c1045d6c.png width=50>

**Comment by lucastbelem** [comment]
If this is doable, that'd be really great. The map is only expected to show the city as a person's location. So if we could default them to the city they entered in their profile sign up, that would solve our GPS to city situation. Would this resolve the possible cost associated with this?

**Comment by JonEsparaz** [comment]
Centering the map should be doable. The issue with using the city the person centers is they could drag the map selector to a different city than they typed, so we might have Toronto showing up as Montreal.

**Comment by JonEsparaz** [comment]
I don’t think we’ll have any cost using the Google reverse geocaching service tho. 40,000 API calls = 8,000 users can edit their location 5 times per month free of charge.

**Comment by lucastbelem** [comment]
Amazing! Let's do it!

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH I'll implement this as we discussed in the meeting - no need for messing around with the API key.
