### ISSUE TITLE
Groups don't have actual location data

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#155]
When I create a group, I can't put actual location data (lat, long).

**Comment by GeorgeBellTMH** [comment]
I think this is by design....

@lucastbelem should groups have location associated with them?

**Comment by JonEsparaz** [comment]
In any case I'm hiding the map on GroupsScreen in a PR that's coming shortly.

**Comment by lucastbelem** [comment]
You got it, @GeorgeBellTMH. No location by design. But if Jon already built something we can keep it hidden for now until JC says "hey, you know what would be cool? If we could add locations to groups". haha

**Comment by JonEsparaz** [comment]
Ok. I'll hide it groups filter from the main map too since it won't do anything.
