### ISSUE TITLE
Dashboard: Multiple event views

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#156]
Currently, on the dashboard, the following event views exist:
- Default
- My events
- Previous events

However, if I click any of these, there is no way to return to my default view without refreshing the page. We need a solution for this.

**Comment by JonEsparaz** [comment]
I think the default view is upcoming events and clicking upcoming/previous toggles between the two.

**Comment by GeorgeBellTMH** [comment]
This is correct, closing.
