### ISSUE TITLE
Overall Styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#158]
@mmacedom In general, when I compare what I see on Beta to what's in Figma, the whole design on Beta seems larger than Figma. Is this just because of the resolution I'm viewing things in?

When I go full screen in Figma, things just seem a bit smaller in general. For example, in Figma, I can always see at least 3 events tiles. But on beta I can only see 2 and 1/2. This pattern continues throughout the site. I.e. groups is the same, and "people to connect with" tiles seem to be too wide as well. In Figma, the grey background the tiles sit on is visible to the right of people to connect with cards.

Let me know if you need clarity here.

**Comment by mmacedom** [comment]
@lucastbelem It'd be great to chat about this to clarify the issue a bit more. 

In terms of things appearing larger on beta, one thing to keep in mind is the fact that every screen on the Figma file was built at 1920px wide where a 13inch laptop is only 1426px wide for instance. So every person's "viewing experience" will vary slightly based on the screen width of their computer. 

Also, it is important to remember that a single Figma screen won't exactly fit full width on a screen like a live site would therefore yielding a different visual context altogether to the user. 

I'd love to chat more about this tomorrow during our call.

**Comment by lucastbelem** [comment]
@mmacedom I had a good chat with the Jesus Collective team. They are happy with our idea to move the default to a smaller screen size so we can scale things to look more naturally like the mock ups. They understand this would effectively mean that we are deviating from the specs in the mock up. A few questions before we proceed:

- How do we decide what screen size to use? 
- What does this look like in terms of work load? Does this mean you need to re-do everything? Or is there a solution that would kind of apply your changes throughout the site (i.e. scale everything by that percentage)? This question is about figuring out whether we should invest this time now or leave it for v2 or v3.

**Comment by GeorgeBellTMH** [comment]
It is my belief that we should design based on how much information we want on the screen...if we want four groups then we scale it to that size...if we want 5 then we scale to that size and fonts get smaller, or we lose some other information...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH, do you say this regardless of screen sizes? As in, it should scale as small or large as it needs to in order to always show the 3 containers we want at any given time?

That would be ideal, but my understanding was that this isn't really possible. If it's possible to accomplish it this way, that would be ideal.

**Comment by lucastbelem** [comment]
Reading your comments further @GeorgeBellTMH, I realized that we're actually talking about the same thing. The goal here is for the content to be dynamic and scale to the screen that's being used, based on the design we have (i.e. 3 containers wide, etc). Everything within that can go down, like font size, etc).

What would we need to decide/determine for this to become a reality @mmacedom?

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH I think a good way to approach this would be to first determine what pieces of content are essential and the smallest font size we want to work with on the components we want to modify. 

Once determined, we can start to tweak the containers to see if they conform to what we are looking for (3 containers on desktop), if not, we need to regroup and determine if we need reduce the font size even further or eliminate content from the containers. 

A good rule of thumb for minimum paragraph size is 16px, however we are already using 14px for <p> in some components.

Let me know your guys' thoughts on this

**Comment by mmacedom** [comment]
@lucastbelem I just pushed a number of changes to address the 3 card view on the dashboard!
