### ISSUE TITLE
Messaging: Text Editor

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#160]
The design for the text editor in Figma is very simple with no formatting provided to the user. Is there a way to hide the format options to match the design? Based on the design, the user doesn't need to do anything (i.e. set fonts, bold, etc). It should just be simple text.

**Comment by JonEsparaz** [comment]
Should be easy to do.

**Comment by JonEsparaz** [comment]
Removed the toolbar entirely. I know the design doesn't call for this, but we might want to add back images and emoji.

**Comment by GeorgeBellTMH** [comment]
Images, emoji and some text formatting...pastors like their bullet points...

@lucastbelem - we need more discussion on this...
