### ISSUE TITLE
Messaging: Design of comment box

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#161]
As per design in Figma, the messaging box in groups/events/etc should look different than it does now (i.e. background of message should be grey. Design found here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=296%3A18522

**Comment by GeorgeBellTMH** [comment]
Are we ok with the current design? Or can we close this?

**Comment by lucastbelem** [comment]
I think we do need to check on this and see if we can get closer to the design. However, this is completely unimportant at the moment.

**Comment by lucastbelem** [comment]
I'm gonna go ahead and close this for now. I suspect things may change in this design before long.
