### ISSUE TITLE
Resources Pages - Overall styling

### ISSUE THREAD

**Issue by mmacedom** [jesus-collective/mobile#178]
@lucastbelem @GeorgeBellTMH I made a few modifications on the resources screens and am looking for some guidance from both of you in terms of what else we need to accomplish on the resource pages. 

I'm finding the Resource mock up screens are a bit confusing given what we have live. Please let me know. Thanks

**Comment by lucastbelem** [comment]
@mmacedom I don't blame you...it's our flow with the least amount of detail. Let me do some thinking on this and get back to you.
