### ISSUE TITLE
Map: On profile view Styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#182]
Currently, the map shows up in my profile, but when I click "change location" the map popup isn't fully visible as per the screenshot here:
<img width="1440" alt="Screen Shot 2020-06-11 at 8 39 37 AM" src="https://user-images.githubusercontent.com/48295718/84386325-20771600-abbf-11ea-896e-6adf29f86b05.png">

**Comment by JonEsparaz** [comment]
This won't be an issue after #187
