### ISSUE TITLE
Resources: Removal of third navigation

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#183]
I got confirmation from the Jesus Collective team that we can make the following changes to Resources:

- [x] Merge 'About' and 'Episodes' pages in Resources to become the 'Series' page
- [ ] Add 'Reviews' at the secondary navigation level and copy reviews from the existing curriculum website here
- [ ] 'About' section should still exist at the series page level, but reviews should be removed and publisher info and contact button should be pulled into the curriculum overview level

**Comment by lucastbelem** [comment]
Jon, I just added you here because you may be working on it...I'm not sure, but didn't want to miss it.

**Comment by JonEsparaz** [comment]
Ideally, I'll have Organizations up and running soon, and we can make the resource publisher/owner TMH (as an Org instead of static data).

**Comment by lucastbelem** [comment]
We've changed requirements on this so I'm closing this.
