### ISSUE TITLE
Resources: Current Series changes

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#192]
Current series playlist should display the following for each video:

- Series title
- ~~Series sub-title~~ (does not exist)
- First 3 lines of description
- "Learn More" Button

**Comment by JonEsparaz** [comment]
Do we intend to add descriptions manually (all descriptions are currently null)?

**Comment by lucastbelem** [comment]
Yeah, episode descriptions don't currently exist, so we'll need to add them manually.

**Comment by GeorgeBellTMH** [comment]
Yes. Lucas is going to add them over time.

Sent from my iPhone

On Jun 16, 2020, at 4:35 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

Do we intend to add descriptions manually (all descriptions are currently null)?

**Comment by JonEsparaz** [comment]
Pretty much done...

![current series](https://user-images.githubusercontent.com/48423418/84850994-32294500-b027-11ea-86ea-f1ea3de75d49.JPG)
