### ISSUE TITLE
Resources: More series playlist

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#194]
This playlist should have the same fields and functions as "Current Series", but no description is needed. This is not a carousel. It should be displayed as a grid.

The design does not accommodate this, but we'll need to add a "load more" button to view more than a 8? series.

**Comment by JonEsparaz** [comment]
Here's what I got so far:

![more series](https://user-images.githubusercontent.com/48423418/84850912-e9718c00-b026-11ea-8f27-1ca108a65271.JPG)

Still need to do the load more button (it just spits all series out right now).

**Comment by lucastbelem** [comment]
Looking great!!

We also need to add a playlist for "Upcoming series". I don't know what this will look like yet (i.e. videos themselves, trailers, graphic placeholder with description?).

**Comment by GeorgeBellTMH** [comment]
Can we clarify what we mean by upcoming vs current series....

Currently: 

A current series is the one that is happening right now...it is published the Monday before the series starts (at which point it is upcoming for 6 days and then becomes current), and is current until the last Sunday it is being used...during that time there is no upcoming series...

In effect all series are "current"...(except for 6 days before they are first used)...

I think the terminology is a bit confusing....

Suggest it might be better to use dates....like:
Series for May 3->June 4

Or seasons:
Season 1 - Episode 4/52

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I know this is closed, but I thought I'd connect about it just in case. 

You're right...the terminology is confusing and we'll need to think about something better. Dates is ideal. I've had a conversation with our curriculum team and they expressed the importance of noting dates because the curriculum is designed in a yearly cycle that goes through the whole bible.
