### ISSUE TITLE
Events and Groups: upload attachments

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#209]
Is it possible to make it so as part of the message board, people can upload documents?

**Comment by JonEsparaz** [comment]
Yes, but it would be a semi-custom solution. 

For design we can probably have a pill with an icon and the first ~10 characters of the file name below the message.

**Comment by GeorgeBellTMH** [comment]
Or a custom description might be a better way to go...will need to figure out which filetypes we are going to support, and if we want to scan them for virus's....

**Comment by lucastbelem** [comment]
Can we add this to the priority list? This may be a silly question, but different is it in terms of functionality to duplicate the "upload your profile picture" functionality?

Can we get at least PDFs done soon? 
I'm not too worried about virus at this point because users have already been vetted personally. We'll need it, but maybe not until Friendships are a thing.

**Comment by JonEsparaz** [comment]
You're correct @lucastbelem, we can reuse some of the profile image code. I will work on the frontend and limit uploads to PDFs for now.

I'm also not super concerned about malicious users, but the actual concern is someone unknowingly uploading an infected file... Virus scanning could be a lot of work though (I'm not sure).

@GeorgeBellTMH should we make a new bucket and/or how should I organize the uploads in S3? One folder per MessageBoard?

**Comment by GeorgeBellTMH** [comment]
I think it goes into the same bucket that it did for images...but a different folder...
