### ISSUE TITLE
Resources: Breadcrumbs

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#210]
Matt raised the possible design issue of a user who may be on The Meeting House kids and youth curriculum Resource page who may need to get back to overall Resources.

A proposed solution would be to create a breadcrumb on the Resource page. For example, if I'm looking at TMH curriculum, there should be something on the design that allows me to see the following: Resources - Kids and Youth Curriculum - TMH Curriculum

This solution presupposes the idea that there is a secondary sort for Resources. For example, currently, if I go to Resources, I see all resources on the platform. Once we have a larger number of resources, we'll need to group these by type or category. I.e. By clicking on Resources, I should land on a page that houses types of resources like "teaching", "kids and youth curriculum", "podcasts", etc.

**Comment by JonEsparaz** [comment]
We might be able to change the back button in the header image to say "Back to Teaching" for example, but if there's a lot of text (ex "Back to Kids and Youth Teaching") things would start looking clunky, especially on mobile.

A web-specific solution would be solving our URL issues (#36, #205). Declarative URLs are breadcrumbs.

**Comment by GeorgeBellTMH** [comment]
If you click on the resources link in the header you go back to all resources....I don't think we need another way to get back there - since it's always universally available...I assume when we have multiple categories of resources it will become a dropdown and "Teaching" will also become a universal navigation option...
