### ISSUE TITLE
Resources: Unvetted library

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#211]
As discussed previously, only Jesus Collective can create Resources and allocate them to the appropriate org. However, there is now discussion of allowing a type of Resource to be created by anyone within the platform. 

The idea for this would be that users could share resources in events and groups through the message board which could be automatically catalogued into a library of resources. However, while we do want to make this possible, we want these to exist in a way that makes it clear for any user that those are not vetted resources. I.e. Maybe it's one of the Resources drop down that says something like "Shared Resources" or "unvetted resources". We don't know the language yet, but I hope that makes sense. 

Please note that these resources do not come into existence from the "create a resource" flow. They come into existence by the simple fact that they are uploaded in a group or event.

**Comment by JonEsparaz** [comment]
A couple challenges/questions for this:
- Will there be a special UI within events/groups for adding resources? Or do resources just get added as links in the message board?
- How would we aggregate the "community resources" from several groups/events?

I'm not sure if this is what Jesus Collective is going for, but the easiest way to achieve this is just have a _single_ group (perhaps owned by JC) dedicated to sharing resources and we can add a link to that group in the resources dropdown menu.

**Comment by GeorgeBellTMH** [comment]
I'm a bit confused why you wouldn't want to use Create Resource....since that's what you want to do...how do you create a resource without creating it? 

We already have a way to define resources as sponsored or not....so I also don't understand why we would need another way to do this...an un-sponsored resource is clearly not sponsored...

Resource's once created can be linked from the message board in groups or events....so it seems logical to me that if you would "Create Resource" and then put the link in the group or event via the message board functionality...

**Comment by lucastbelem** [comment]
Hey guys,

Sorry this answer is long overdue.

Maybe using the word "Resources" for this purpose isn't helpful as it does not have the same meaning here.

The idea of this "unvetted library" is a place (maybe one Resource group in the Jesus Collective sense) where all pdfs attached to groups within the platform end up living. This Unvetted library would have exist somewhere (maybe under the Resources nav) and when someone goes there, they land on a page (for which design doesn't exist) where they can browse every document that has ever been uploaded in the platform (with some caveats - i.e. public groups only).

In any case, this is very much a future dev, so you guys don't need to spend too much time/energy on this.

**Comment by GeorgeBellTMH** [comment]
I'd want to see a design for this before we get to far into it.

**Comment by lucastbelem** [comment]
This probably won't happen for months or even years...so closing.
