### ISSUE TITLE
Groups: memberCount does not update

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#215]
memberCount should update when an individual leaves or joins a group, but the current auth rules don't allow this.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713132214)

**Comment by lucastbelem** [comment]
@JonEsparaz did we solve the memberCount issue?

**Comment by JonEsparaz** [comment]
Not yet.

**Comment by GeorgeBellTMH** [comment]
I think we could probably easily do this with a scheduled lambda that just updates it every couple of hours...

**Comment by lucastbelem** [comment]
@itbel I think you took care of this a long time ago, yeah?
