### ISSUE TITLE
Resources: Preschool images

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#221]
The preschool series images aren't loading. Is there something we need to do?

**Comment by JonEsparaz** [comment]
It's trying to pull a YouTube thumbnail (which doesn't exist), so we need to update some of the code.

I don't know where the actual images are though - not sure if we need to import them @GeorgeBellTMH?

**Comment by GeorgeBellTMH** [comment]
All of our thumbnails come directly from youtube.

If there isn’t one, it’s likely when it was imported it was still processing on youtube or something…repulling the data should get the updated thumbnail (unless there is some reason on youtube it wouldn’t have a thumbnail, but I’ve never seen that).

**Comment by JonEsparaz** [comment]
Pre-school resources don't have videos though. I believe these are the graphics (which aren't YT thumbnails):

![image](https://user-images.githubusercontent.com/48423418/85769035-9f07a380-b6e7-11ea-9a12-b10f6a48df98.png)

**Comment by GeorgeBellTMH** [comment]
Ahh…sorry I thought you were talking TMH…yes…for JC…

The data all came from ResourceScreen/kidsandyouth.json which is an export from the wordpress site…the image url’s should be in there…you can check ImportKidsandYouth.tsx to see if the imported mapped the image field from wordpress to dynamo…you may need to write a quick “re-importer” to just import that value for the pre-school stuff if it’s not there (I wouldn’t try to modify the importer, it was really intended to just be used once…)

G

**Comment by JonEsparaz** [comment]
Will do. Thanks George!
