### ISSUE TITLE
Leadership formation styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#229]
@mmacedom good news! It looks like some leadership formation stuff is up on beta :) Can you take a look to see what you can do for styling?

**Comment by mmacedom** [comment]
@lucastbelem Yes, I will take a look and work on it.

**Comment by mmacedom** [comment]
@lucastbelem after pulling from master this morning, I noticed that the "courses" navigation tab was removed for now. I'm assuming George is working on it? I'll keep styling it once it's back on

**Comment by GeorgeBellTMH** [comment]
You should have access to courses. Let me know if you don't.

**Comment by mmacedom** [comment]
@GeorgeBellTMH There's no courses on my local after I pulled from master tonight.

**Comment by GeorgeBellTMH** [comment]
Closing since this is generic...
