### ISSUE TITLE
Alignment issues on profile creation

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#231]
<img width="315" alt="Screen Shot 2020-07-01 at 11 59 00 PM" src="https://user-images.githubusercontent.com/47749730/86314919-dfd74f00-bbf6-11ea-8abd-053466a490fb.png">

Alignment issues on profile creation...
- [x] Upload Profile Picture (if we want it shorter, it could be Set Profile Photo)
- [x] Short sentance about me should likely show two full lines
- [x] Org name not defined should probably be shorter and hopefully fit on one line
- [x] Public location overflows the left bar
- [x] I think the input text size for describe your location, about me, personality and org info is too big, it should probably match the text size of public location input...
- [x] for those same fields the placeholder text should be grey...so it matches the public location input as well...

**Comment by mmacedom** [comment]
@GeorgeBellTMH These issues have been resolved with the new latest PR. Please let me know if you see any discrepancy on your end. Thx
