### ISSUE TITLE
Issues with Header in profile creation

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#232]
<img width="1400" alt="Screen Shot 2020-07-02 at 12 02 17 AM" src="https://user-images.githubusercontent.com/47749730/86315132-583e1000-bbf7-11ea-8e42-ac4e6a8dcbb8.png">

- [x] Lets put the error text on a new line so we don't have problems with smaller screens
- [x] Lets shorten the Save and Publish Your Profile - maybe something like Save Profile
- [x] There is a new delete Profile button when coming via the edit view...it needs alignment

**Comment by GeorgeBellTMH** [comment]
Note these are all because of the red bar on the left...so I think it makes sense to design it so it works with the red bar first, then see what it looks without the red bar.

**Comment by mmacedom** [comment]
@GeorgeBellTMH I have adjusted the top elements based on the screen with the red bar as requested. On Ipad, I stacked all three elements and shifted them to be justified left so they all fit. (Setup your Profile, top buttons, and error validation). Let me know if everything is good on this one
