### ISSUE TITLE
DM issues in safari

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#243]
- [x] Can't change between rooms
- [x] Messageboard doesn't show up
- [x] Creating new rooms is slow

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/47749730/86527034-e240df80-be68-11ea-96f3-cd10630cc9ac.png">

**Comment by JonEsparaz** [comment]
I'm having trouble recreating the first two issues (everything works on Safari). It's possible that the messages were created before we added the `author` field, so the message board is erroring out. I've added some error checking for this in #251.

I'm working on the slow creation issue on Safari...
