### ISSUE TITLE
Admin group should be able to do a bunch of things

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#244]
If you are in the admin group, you should be able to:

* [ ] Delete groups, events, resources, orgs that aren't yours (should warn it's not yours to delete)
* [ ] Update groups, events, resources and orgs that aren't yours (should warn it's not yours to update)
* [ ] Delete, or disable users
* [ ] Delete messages in groups/events (discuss how we want to handle this)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713132936)

**Comment by lucastbelem** [comment]
Will be addressed by admin design project.
