### ISSUE TITLE
We need an autocompleting Group, User or Org textbox

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#246]
We need an EditableGroupList, EditableUserList, EditableOrgList textbox...

When isEditable=false it should have a list of the groups, users or orgs (optionally they should be clickable)
When isEditable=true it should be a textbox that autocompletes the name, and then turns into a tag with an x
It should have an allowUpToX prop, where if X=1 then only one user/group/org can be added
It should likely be just one object that takes type="group|user|org" unless there is a good reason to separate them
Optionally show profile image
Expandable to Resource/Courses

Useful for forms, useful for DMs....some parts may be re-usable for searching.
Likely uses elasticsearch

**Comment by GeorgeBellTMH** [comment]
@JonEsparaz this is roughed in for users and I put it on the conversation screen temporarily (will hide it when I publish), probably needs a button to create a room...there are some things I still need to do:

- [ ] I enabled @searchable on User model, but we need to push content from dynamodb to elastic search...(only new users will show up for now)
- [ ] fill in the fetchSuggestions to use queries.SearchUsers - autocomplete is hardcoded for now
- [ ] styling

**Comment by GeorgeBellTMH** [comment]
@mmacedom you can style this now, it's on the DM screen...

**Comment by mmacedom** [comment]
@GeorgeBellTMH @lucastbelem All DM screen sizes have been styled
