### ISSUE TITLE
Create default values for all required fields in Orgs and disabled parts of the schema

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#249]
Need to create an AWS script to update the dynamodb before we enable Orgs.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH could you provide a bit more detail? I'm not 100% sure what I need to do here.

**Comment by GeorgeBellTMH** [comment]
So I think we need a .sh script that uses aws-cli - something like:

insertDefaultFieldtoDB.sh [tableName] [columnName] [defaultValue]

Then it just interates through all items in tableName and updates the field with columnName=defaultValue if columnName==null.

**Comment by JonEsparaz** [comment]
I'll probably write this in Python. I think this is what we need: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.update_item

**Comment by GeorgeBellTMH** [comment]
Yup. I have a python folder. Just add it there.

Sent from my iPhone

On Jul 10, 2020, at 12:18 AM, Jon Esparaz <notifications@github.com> wrote:

﻿

I'll probably write this in Python. I think this is what we need: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.update_item
