### ISSUE TITLE
"There are no upcoming events" when events are empty

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#250]
It looks like the events aren't loading, when there are just no upcoming events.

**Comment by GeorgeBellTMH** [comment]
Added text for loading and no upcoming events/groups etc. @mmacedom to style

**Comment by mmacedom** [comment]
@GeorgeBellTMH I added a temporary style to it. How can I visualize the error now that events, groups, resources are populated? Is there a way I can temporarily delete some of them to trigger the error?

**Comment by GeorgeBellTMH** [comment]
You can change the code to just make it always call that branch...(just comment out the other branch...

**Comment by mmacedom** [comment]
@GeorgeBellTMH I just fixed it. I also added "upcoming" to "No upcoming events/groups/resources" and took the apostrophe out so it reads "No upcoming groups" rather than "No upcoming group's". The change is on a new PR
