### ISSUE TITLE
Multiple DMs to same person

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#253]
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/47749730/86555329-0ca0a480-bf1e-11ea-82db-d922cf2af8ad.png">

I went in by clicking on start conversation with Jon, then left and clicked on start conversation with Lucas...but there is now two conversations with Jon....

**Comment by GeorgeBellTMH** [comment]
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/47749730/86555424-4a9dc880-bf1e-11ea-97b2-438f56475590.png">
When going via the profile, there is now only one conversation with Jon

**Comment by GeorgeBellTMH** [comment]
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/47749730/86555487-7e78ee00-bf1e-11ea-918e-de9574b1fdf8.png">
Clicking on start conversation with Chris and this happened...

**Comment by JonEsparaz** [comment]
I figure out what the bug is... Just need to patch
