### ISSUE TITLE
Profile style issues

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#255]
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/47749730/86555672-05c66180-bf1f-11ea-9e24-cc0fa44c69c7.png">

- [x] Remove extra room around Children's ministry
- [x] Current Role->Digital Solutions is cutoff

**Comment by mmacedom** [comment]
@GeorgeBellTMH the PR I opened last night should've addressed the extra room issue around key interests. Let me know if you are still seeing it on your end.
