### ISSUE TITLE
DMs: Name of chat when viewed by other user

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#257]
By example:
- George creates chat with Jon. 
- Chat room is named Jon Esparaz (appears correct to George).
- Jon opens chat with George.
- Chat room is still named Jon Esparaz (appears incorrect to Jon).

**Comment by GeorgeBellTMH** [comment]
Probably should be un-set unless the user sets it...and if it's not set it just shows the list of users (minus the user who is viewing it)
