### ISSUE TITLE
Profile: Mandatory fields issue

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#263]
When creating a new profile, mandatory fields are not all marked properly and so it creates submission issues for profiles.

**Comment by JonEsparaz** [comment]
@lucastbelem you mean we need to add the red asterisk in a few places, right?

**Comment by lucastbelem** [comment]
Yeah. Remember that doc I shared with you that had all of profile fields for different profile types? That doc should say which fields are required and which aren't.
