### ISSUE TITLE
Show all groups bug

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#265]
When I’m looking at all groups and scroll to the bottom of the page, the ones on the bottom row are cut off and I can’t see a join/leave/owner button.

<img width="1440" alt="Screen Shot 2020-07-07 at 4 40 22 PM" src="https://user-images.githubusercontent.com/48295718/86840319-9496c380-c070-11ea-94e9-429c362117aa.png">

**Comment by mmacedom** [comment]
@lucastbelem I have adjusted the height on a new PR.
