### ISSUE TITLE
Account Settings: Change password

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#266]
Can we give the user the ability to change their password right from within their profile edit view?

**Comment by GeorgeBellTMH** [comment]
Yes, this should be possible...

**Comment by JonEsparaz** [comment]
https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#change-password

I think it makes the most sense to first implement the Edit view, then put this change password stuff within the Edit view.
