### ISSUE TITLE
Profiles: Edit View

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#273]
When you go to your own profile, it should look mostly like any other user's profile, but when you click the Edit button on the panel, the page changes to allow edits.

@GeorgeBellTMH I assume the Logout button should always be present on your own profile, but the Save Profile and Delete buttons should only be there after clicking Edit, right?

**Comment by GeorgeBellTMH** [comment]
Yup, sounds correct...some things should likely appear and disappear as well (ie. My Groups should not be visible in edit mode)...
