### ISSUE TITLE
Map: Space out users

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#280]
Since users type in their location now, multiple users end up at the _exact_ same location.

For example, there are 3-4 users in Toronto right now, but it only appears like there is one and I can't interact with the other users on the map.

Best solution is probably to shift users with a duplicate location out some by a some random `(lat, lng)` within a bounding box. We can either do this when the user selects their location or at render.

Bounding box should be around 0.02° latitude by 0.06° longitude.

**Comment by GeorgeBellTMH** [comment]
We now save a randomLat and randomLong, so user should appear in place+randomized distance away - and always be in the same location.
