### ISSUE TITLE
dashboardRightCard

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#283]
Media Query for dashboardRightCard is @media (min-width: 320px) and (max-width: 480px)

When you set to 481px, there is some problems with the "People you may connect with" overlapping other groups...media query likely needs to go bigger until there is two columns again...(720px)

**Comment by mmacedom** [comment]
@GeorgeBellTMH I adjusted the mobile media query to (min-width: 320px) and (max-width: 720px). I checked for overlap on that component and it seems okay. Let me know if you are still seeing the issue. 

One thing that I did notice is that the event cards are overlapping a little bit on mobile. A simple solution would be to change the width of the cards from 350 to 300px. Let me know if I should make that change.
