### ISSUE TITLE
Login screen - extra text

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#296]
Can we remove the extra text "Please sign in/sign up" from below the fillable fields?
<img width="1046" alt="Screen Shot 2020-07-09 at 1 12 38 PM" src="https://user-images.githubusercontent.com/48295718/87069917-ff1d4000-c1e5-11ea-9788-98d027af7b15.png">

Thanks.

**Comment by JonEsparaz** [comment]
After trying a bunch of hacky solutions, this won't be possible until AWS Amplify updates the `<Authenticator/>` component. I bumped an issue in the amplify-js repo - hopefully they get around to it soon.
