### ISSUE TITLE
Church size on login creation

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#297]
Sorry for another one of these requests, but can you make changes to the dropdown options for church size? We need options going up to 10k. We should see the options available, then add:

250-500
500-1000
1000-2000
2000-3000
3000-4000
4000-5000
5000-7500
7500-10000

![IMG_2932](https://user-images.githubusercontent.com/48295718/87070237-7eab0f00-c1e6-11ea-8302-53a943907fa0.JPG)

**Comment by JonEsparaz** [comment]
Should there be a 10k+ or >10k option?

**Comment by lucastbelem** [comment]
Good call. Over 10,000 would be great.
