### ISSUE TITLE
People you may connect with: is verbose

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#298]
@lucastbelem can we change 

People you may connect with:
to
Connect

This will reduce the amount of space taken up by the header in mobile.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH we definitely gotta do that. Can we just hold off a bit? Matt is about to send us a number of copy edits and I'm sure that will be one of them. 

On that note, (this may be a separate issue) can we make that "People you may connect with" more clearly a clickable thing? Maybe an underline? Something that would make people know to click on it.
