### ISSUE TITLE
Map performance

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#301]
Map is usually the last thing to load in safari, lets see if we can speed it up, at least so that it is visible...it's ok if it takes a bit longer for the pins to load.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713133871)

**Comment by GeorgeBellTMH** [comment]
Potentially need to pre-load some more fonts...

**Comment by lucastbelem** [comment]
@itbel can you please check this out and see if it's still an issue?

**Comment by lucastbelem** [comment]
As per new priorities, this issue becomes irrelevant.
