### ISSUE TITLE
Profiles: Current Role disappears

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#304]
As per phone discussion:

Current Role field disappears from profile creation when user selects 7 or so interests.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can we publish this change today once Jon fixes it? Jon Hand wants to get a couple of Hub Leaders on the platform once this is solved.

**Comment by JonEsparaz** [comment]
@lucastbelem you know what browser Jon Hand was using?

**Comment by lucastbelem** [comment]
@JonEsparaz safari.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH Everything is working fine. I deleted my profile and created a new one. All is well.

However, I lied to you - Jon now fixed the profile bugs I told you about...next time you're available, could you publish again? Sorry man!

**Comment by JonEsparaz** [comment]
I think you might be talking about the changes in #286. Not quite done yet (still dealing with #303).

**Comment by GeorgeBellTMH** [comment]
Published….please check
