### ISSUE TITLE
Profile creation: user doesn't exist error message

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#309]
When I'm creating a profile, after I enter the verification code, I'm taken back to the login screen with the error message "user doesn't exist" already displaying (because I immediately tried to login with a non-existing account first). Can we make it so this error message disappears once I'm verified and am taken back to the login screen? It's a bit confusing.

<img width="1011" alt="Screen Shot 2020-07-10 at 2 01 52 PM" src="https://user-images.githubusercontent.com/48295718/87184553-3824e580-c2b6-11ea-814f-114b4eacd9ee.png">

**Comment by JonEsparaz** [comment]
I'll look into it.

**Comment by JonEsparaz** [comment]
As mentioned in #296, we can fix this if we do a fully custom auth flow. I did some tests today and it should be doable, but might time consuming.
