### ISSUE TITLE
Profile creation: Styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#310]
Could we take a look at styling of the profile creation page? The panel on which "Tell us more about you" sits should be white. The text boxes should be the grey pieces. 

Here is a sample of what I'm referring to: 
<img width="1420" alt="Screen Shot 2020-07-10 at 2 12 25 PM" src="https://user-images.githubusercontent.com/48295718/87185344-9605fd00-c2b7-11ea-91c9-1a8c4784a80e.png">

Here is the link to what the colours should look like: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=1464%3A1060

@mmacedom for bonus points, do you think it would if we made the red graphic on the left hand corner narrower to give the area people fill up have more space? Thoughts? I'm sure that's all done to spec, but if you have thoughts to make it look better, that'd be great :)

**Comment by JonEsparaz** [comment]
@mmacedom I'd recommend waiting until #286 is merged so you don't get a merge conflict.

**Comment by mmacedom** [comment]
@lucastbelem I definitely agree with you that the red bar can be narrower. I can reduce the size of it a bit more so the other columns have a bit more "breathing room".

**Comment by mmacedom** [comment]
@lucastbelem I just created a new PR to reduce the red bar from 25% to 15% width. Let me know what you think when it's merged.

**Comment by lucastbelem** [comment]
@mmacedom looks great!

Here are a couple more suggestions:

- Can you add to the width of the 2 columns of the profile creation piece? Especially the second column with all of the text fields?
- Can you make it so that text boxes are a bit larger? As I type in them, because they're generally only about 2 lines tall, the text disappears from view as I keep typing. Could we make so: 1) the boxes are maybe 4 lines tall OR 2) as I type, the box gets bigger to accommodate the amount of text lines I add? Thoughts on UI issues here?
- The text box for personality type, has some sample text underneath it. However, because the text box is only 2 lines tall, I can't read the entire text sample.
- The white space between my interests and current role is quite large. I know it's there to accommodate My Interest selections. However, could we make it so the white space is a lot smaller, and then space gets created as I add Interest selections?

Here is a screenshot for reference.
![Screen Shot 2020-07-13 at 10 36 11 AM](https://user-images.githubusercontent.com/48295718/87318500-6ee93e80-c4f6-11ea-9257-81430b75e7bb.png)

**Comment by mmacedom** [comment]
@lucastbelem absolutely I'll look into that. I created a PR on Friday that should address all of the issues mentioned above (#377). Once it's merged, I'll check and see if the issues mentioned above still remain. @GeorgeBellTMH 

<img width="1150" alt="Screen Shot 2020-07-13 at 1 53 49 PM" src="https://user-images.githubusercontent.com/24467324/87337088-e2984500-c510-11ea-8c22-a8ab19c37706.png">

**Comment by GeorgeBellTMH** [comment]
Merged the PR...please verify
