### ISSUE TITLE
Leadership Development - Public Release

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#316]
Scope: This project endeavours to create, within the existing Jesus Collective platform, a course platform. This platform will allow participants to join a course, engage in conversation about a pre-loaded syllabus, produce written and video assignments, and engage with an instructor who evaluates their performance and progress through the course. As part of this project, here are the functions that need to be created for this project to be successful:

Important
- [x] ability to add/delete weeks
- [x] ability to add/delete lessons (aka days)
- [x] ability to create/delete new triads
- [x] ability to assign coach to triad
- [x] ability to assign members to triad
- [x] ability for leader to see all triads
- [x] Ability to download complete syllabus
- [x] Ability to create cohort (by default this is created when you make triads)
- [x] Ability to create triads
- [x] ability to add/delete assignments
- [x] show course overview with rich text
- [x] ability to set week description via rich text
- [x] ability to set lesson description via rich text
- [x] ability to assign a leader
- [x] ability for members to see their triad and remaining members of cohort 
- [x] Ability to view coach, instructor and other student profiles
- [x] Ability to view at-a-glance course calendar
- [x] Ability to message cohort
- [x] Ability to view course details broken down by week and day
- [x] Ability to view day details
- [x] Ability to join scheduled zoom call
- [x] Ability to write assignment
- [x] Ability to post assignment
- [x] Ability to upload a file
- [x] Ability to view other student's assignments
- [x] Ability to comment on other student's assignments
- [x] Ability to comment on responses to the student's own assignments
- [x] Ability to schedule and display a recorded zoom

Course Content
- [x] show course overview in accordion
- [ ] ability to reorder weeks
- [ ] ability to reorder lessons
- [ ] Ability to watch in-assignment videos

Messaging
- [x] Ability to message instructor
- [x] Ability to message triad
- [x] Ability to message cohort

Assignments
- [ ] Ability to record a video message as assignment
- [ ] Ability to save assignment as draft for later submission
- [ ] Ability to edit submitted assignment
- [ ] ability for coaches to see all of their triads, and remaining members of cohort

Payment
- [x] Make the pay button only show up if there is a valid product setup
- [x] Make the pay button only show up if you haven't paid for the product yet
- [x] Paypal setup for production

Onboarding
- [X] Invitations can be accepted and extra details entered
- [x] Interface to invite 
- [x] Make certain courses/groups only visible to a limited list of users
- [ ] Organization invitations

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can we talk about all of these functions? I'm wondering how you're feeling about everything that needs to be delivered in the next month, in light of vacations, etc? Do we need to talk about cutting scope?

**Comment by GeorgeBellTMH** [comment]
@lucastbelem can you test the following: 

Invites: go to Rocket Admin->CRM->Invite - you may need to delete a non-admin user to test this (or use an email that isn't already in the system)

Add/remove user from group: Rocket Admin->CRM->Groups (add/remove - be careful not to delete your admin access)

Payments in courses: Go to course->click pay->(use a user from the PayPal sandbox)->should get a confirmation (can validate via Admin->CRM->Payments

**Comment by GeorgeBellTMH** [comment]
Note - when testing this functionality make sure you start from the root directory (dev.jesuscollective.com) - if there is stuff after .com in the url it won't work...

**Comment by GeorgeBellTMH** [comment]
Please also test the calendar, todo list, and Learning Collective/Cohort message boxes (the facilitator doesn't work yet)....suggest you add a bunch of users and test with different combo's of them to ensure the messages are visible correctly, the lists of cohort members and coaches is correct etc...

**Comment by GeorgeBellTMH** [comment]
Also note, for coaches (or anyone who is in two separate cohorts) it will show a dropdown in the message area where you can pick them (@mmacedom you will need to do some styling here)...if the user is only in one it doesn't show the dropdown...

**Comment by lucastbelem** [comment]
Could not pay for course. When I clicked "Purchase" I got this screen:
<img width="1118" alt="Screen Shot 2020-09-28 at 9 35 15 AM" src="https://user-images.githubusercontent.com/48295718/94439108-f9445480-016d-11eb-9c5a-6094edfff624.png">

**Comment by lucastbelem** [comment]
@GeorgeBellTMH summary of tests:

- [ ] Invites: go to Rocket Admin->CRM->Invite
- [ ] Add/remove user from group: Rocket Admin->CRM->Groups (add/remove)
- [ ] Payments in courses: Go to course->click pay->(use a user from the PayPal sandbox)->should get a confirmation (can validate via Admin->CRM->Payments
- [ ] Test the calendar
- [ ] Todo list 
- [ ] Learning Collective/Cohort message boxes

**Comment by lucastbelem** [comment]
> [ ] Payments in courses: Go to course->click pay->(use a user from the PayPal sandbox)->should get a confirmation (can validate via Admin->CRM->Payments

Could not perform payment. Could not pay for existing leadership development course - I think this is because I'm an admin. I'll get someone else to test.
When I clicked "Purchase" in test course I created, I received the following screen:
<img width="1118" alt="Screen Shot 2020-09-28 at 9 35 15 AM" src="https://user-images.githubusercontent.com/48295718/94447189-88a23580-0177-11eb-9a80-4ef127d9492a.png">

**Comment by lucastbelem** [comment]
> * Course Activity

Course activity does not pass a test - I submitted an assignment, but it did not reflect in course activity.

**Comment by lucastbelem** [comment]
> * Test the calendar
> * Todo list

Calendar and to-do both work and display entered data (i.e. assignment dates, upcoming assignments). There is no clickable action, but the design doesn't really flesh that out, so I consider this complete.

**Comment by GeorgeBellTMH** [comment]
To make a payment you have to create the product in the admin menu...the id of the product must match the id of the course (visible in the url and formatted like course-xxxx) once the product is made you should be able to buy...

Sent from my iPhone

On Sep 28, 2020, at 10:44 AM, Lucas Belem <notifications@github.com> wrote:

﻿

[ ] Payments in courses: Go to course->click pay->(use a user from the PayPal sandbox)->should get a confirmation (can validate via Admin->CRM->Payments

Could not perform payment. Could not pay for existing leadership development course - I think this is because I'm an admin. I'll get someone else to test.
When I clicked "Purchase" in test course I created, I received the following screen:
[Screen Shot 2020-09-28 at 9 35 15 AM]<https://user-images.githubusercontent.com/48295718/94447189-88a23580-0177-11eb-9a80-4ef127d9492a.png>

**Comment by GeorgeBellTMH** [comment]
You can direct message everyone now by clicking on the start conversation button...it will take you to the direct message window...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH are we able to get video stuff in? There is in-assignment videos and video assignments. Let me know if we can't get it in - I just need to get them a work around (i.e. add a link to the content and have people add videos to youtube and  drop links in their assignment.

**Comment by GeorgeBellTMH** [comment]
@lucastbelem no video...see #477

**Comment by GeorgeBellTMH** [comment]
I'm closing this for individual tickets...
