### ISSUE TITLE
Tooltip: Set font family, resources text

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#322]
Font should be Graphik or at least something sans-serif.

For "Kids & Youth Curriculum", the tooltip is activated even though I can see the full title on the card.

**Comment by mmacedom** [comment]
@lucastbelem @JonEsparaz I adjusted the condition of orgs that will address the second issue mentioned above. As far as font family, I need to be able to create events/groups on my local to adjust that. As of the latest pull from master, I cannot create groups/events. @GeorgeBellTMH

**Comment by JonEsparaz** [comment]
You probably can’t create groups/events because of a sort of bug introduced by organizations. I’ll fix later this afternoon

**Comment by lucastbelem** [comment]
@mmacedom you might be good to look into this one after Orgs got sorted.

**Comment by mmacedom** [comment]
@lucastbelem this has been fixed and pushed in a new PR.
