### ISSUE TITLE
Titles collide in reduced browser window size 

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#325]
**Describe the bug**
When I reduce my browser window to half size, the titles on the dashboard collide.  See 'events' title colliding with red titles below.

![image](https://user-images.githubusercontent.com/68029138/87432240-bb478380-c5b5-11ea-8b8d-69f11a4f4555.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeorgeBellTMH** [comment]
This is fixed now
