### ISSUE TITLE
Event buttons shouldn't say 'Don't Attend' 

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#329]
**Describe the bug**
When I click the attend button for an event it should show something that confirms I have already added it, rather than say "Don't Attend".  I think we talked about this in the design phase? Maybe even turning the button green after you've clicked 'attend'?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeorgeBellTMH** [comment]
Closing for #334
