### ISSUE TITLE
Join/Leave Buttons on Homepage don't work

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#33]
If you go to beta.jesuscollective.com, you'll see your dashboard and the main blocks (events, groups, etc). 

For groups, if you click "join" the button should change as per the design. Currently, the button works (I get added to the group) but the button remains unchanged.
Same for Events with "Attend".

**Comment by GeorgeBellTMH** [comment]
The code for joining and leaving groups is already done in the group and event screens, but we need to generalize it and bring it out to the homepage...the button should be:
1) For owner it should be a text field saying Owner
2) For non-owner it should be either a join or leave button for groups depending on if they are a member or not - or attend/don't attend for events

**Comment by JonEsparaz** [comment]
Within the group/event screen, the button doesn't toggle upon first click - need to reload the page to see state change. I'll prioritize the homepage, then look into this.
