### ISSUE TITLE
Profile picture view in groups

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#337]
A user reports that they uploaded a picture which appears normally in their profile: 
<img width="484" alt="Screen Shot 2020-07-15 at 2 10 16 PM" src="https://user-images.githubusercontent.com/48295718/87580111-f83e7380-c6a4-11ea-96ce-814331a0f3b0.png">.

However, when they joined a group, the icon with their picture displays their image sideways:
<img width="470" alt="Screen Shot 2020-07-15 at 2 11 22 PM" src="https://user-images.githubusercontent.com/48295718/87580589-ba8e1a80-c6a5-11ea-9e34-c188c720d9d3.png">

**Comment by GeorgeBellTMH** [comment]
I've fixed this.

**Comment by GeorgeBellTMH** [comment]
exif in image needs to be handled by sharp
