### ISSUE TITLE
People you may connect with

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#338]
If you go to "people you may connect with" you'll see all of the existing profiles on the platform. However, as you can see in this screenshot, the last row is being cutoff.
<img width="1439" alt="Screen Shot 2020-07-15 at 4 17 42 PM" src="https://user-images.githubusercontent.com/48295718/87591779-d4842900-c6b6-11ea-8459-d559bc01a3df.png">

**Comment by mmacedom** [comment]
@lucastbelem I fixed the issue
