### ISSUE TITLE
Events and Groups permission issue

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#34]
Right now, if I open an event I see on my dashboard, and click "save event", the system switches the event organizer to me and clears all existing attendees. My guess is that this is the case because I'm part of the admin group that is allowed to edit events. However, if someone else on the admin group creates that event, when I make edits and save the event, I should not become the organizer (or at least I should have the option to become or not) and attendees should not be cleared.

Same situation applies to Groups.

**Comment by GeorgeBellTMH** [comment]
This is now working, @mmacedom you will need to apply the styles for readonly events/groups now...

**Comment by mmacedom** [comment]
@GeorgeBellTMH Ok.

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH The issue has been taken care of. Please confirm on your end.
