### ISSUE TITLE
Map Info Window: Functional Changes

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#342]
- [x] When you click on a marker and the info window opens, the space above and below the info window is covered by a `<View/>` (see screenshot) that is used to vertically center the info window. This makes means that users cannot close the info window by clicking on this portion of the map (they have to click the X or click to the left or right of the info window).

- [x] ~~Also, the mobile designs on Figma suggest that the map shouldn't be visible on mobile.~~ Map remains, but mobile UI/UX has been somewhat improved.

![image](https://user-images.githubusercontent.com/48423418/87859419-fc67cc80-c902-11ea-8cd9-27546a7ad2b6.png)

**Comment by lucastbelem** [comment]
@JonEsparaz users also can't go from one profile popup to another by simply clicking on another marker.
