### ISSUE TITLE
Design of Direct Messages page

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#353]
The design is a bit wonky where the names are listed under "Direct Messages" in the direct messages page.  The names are not centred vertically next to the photo circles, the photo circles are not centred vertically in the grey boxes, and the photo circles are pressing up against the left hand side of the grey boxes.

![image](https://user-images.githubusercontent.com/68029138/88053486-e25c0300-cb29-11ea-8cab-f2325720dca3.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mmacedom** [comment]
@MattMilesJC @lucastbelem The last PR created should address all of the issues listed above. Thx
