### ISSUE TITLE
Photo on message box in direct messages

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#354]
The author photo next to the message box in the message window in direct messages is floating too high relative to the message box.

![image](https://user-images.githubusercontent.com/68029138/88053677-31a23380-cb2a-11ea-8503-c59daf474f01.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mmacedom** [comment]
@lucastbelem @MattMilesJC I created a new PR to address this issue.
