### ISSUE TITLE
Button outline weights are not consistent on dashboard 

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#355]
The weight/thickness of the button outlines for white buttons with a red outline are not consistent on the dashboard page.  e.g. See 'Create Event' vs. 'Start Conversation' or 'Jesus Collective Directory'. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeorgeBellTMH** [comment]
They are the same, the difference is the font is bolded in some...as per design.
