### ISSUE TITLE
Carousel arrows missing on dashboard

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#357]
Carousel arrows to the left and right of the carousels (e.g. events, groups, resources) are not present to help the user scroll through the carousel.

Also, the way the carousel scrolls in beta exposes only a portion of the next item in the carousel on the right hand side of the carousel when you scroll, which looks weird.  And there is not enough spacing between the rightmost item in the carousel and the window containing the list of profiles to the right.  It looks jammed together. 

See image below from beta vs. the original figma design -- the original figma design has carousel arrows and more spacing between carousel and profile listings window.

![image](https://user-images.githubusercontent.com/68029138/88055544-2c92b380-cb2d-11ea-816e-955350a3bb9c.png)

![image](https://user-images.githubusercontent.com/68029138/88055462-0c62f480-cb2d-11ea-99ad-052a241f63e8.png)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713144497)

**Comment by GeorgeBellTMH** [comment]
windows users always want the Carousel buttons....Mac users don't seem to care...but then I see that ugly scroll bar and it all makes sense...

**Comment by lucastbelem** [comment]
@branden-eyk let me know what you think of this one. I can re-assign if needed. If you are going for it, please note that arrows should exist on either side of any horizontal list, and when pressed, the next 3 tiles in that list should appear. If there aren't 3, then the next 2 or 1, but we should never see a partial tile like in the screenshot Matt shared. 
On mobile, tiles stack, so implementation does not require arrows.

**Comment by branden-eyk** [comment]
Hi guys, sorry I'm so late on this one! @GeorgeBellTMH question for you regarding this: am I correct in assuming that we currently lack a carousel as a component and would need to add one in? 

If so, what are your thoughts on that? Are we ok pulling in any free and open source REACT native code/libraries for things like this, or are there any limitations on what you would want us using?

**Comment by GeorgeBellTMH** [comment]
We aren't using a carousel component per-se...but we already have most of the functionality with just regular components...it would probably be easiest just to add two buttons and make them scroll it left/right if there is space to do so...if you want you can replace everything we have with a carousel if you can keep all the existing functionality/style (on web/mobile)
