### ISSUE TITLE
Names and roles not centred next to profile photos in conversation panel on dashboard 

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#358]
People's name and profile and the 'start converation' button are not centred vertically relative to the profile photos in the conversation panel on the dashboard.

![image](https://user-images.githubusercontent.com/68029138/88056121-0faab000-cb2e-11ea-829c-9ba8e74920d9.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mmacedom** [comment]
@MattMilesJC @lucastbelem I just created a new PR to vertically align the content.
