### ISSUE TITLE
Start conversation buttons not aligned on profile directory page

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#359]
Start conversation buttons are not left justified with the name and role of the person next to their profile image on the partner profile directory page.

Also the buttons look really chunky here -- too tall vertically relative to their width.  Start converation buttons seem like they should be a standard size and shape across the site?

![image](https://user-images.githubusercontent.com/68029138/88057361-fb67b280-cb2f-11ea-9071-b8b0157c06f3.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mmacedom** [comment]
@MattMilesJC @lucastbelem The issue has been fixed with a new PR that was just opened.
