### ISSUE TITLE
URL flow as you dig deeper into the platform

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#36]
Currently, when you click "create a group" (this applies to other places too), the url displayed is as such: https://beta.jesuscollective.com/app/group/undefined/true

Can we do something to have the url displayed more simply?

**Comment by GeorgeBellTMH** [comment]
Yes - this url should be something like app/group/create

**Comment by GeorgeBellTMH** [comment]
Closing, need more specific fixes going forward...
