### ISSUE TITLE
Profile pictures inconsistent -- some are ovals and some are circles

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#360]
Profile pics on the list on the dashboard are ovals but are circles in other areas of the site like the profile directory page. Should be consistent?  Ovals is our thing so that would be my preference.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeorgeBellTMH** [comment]
@mmacedom if this is an obviously easy style fix lets try and do it...if it's more complicated don't worry about it.

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH @MattMilesJC I just adjusted the images so they are all ovals now.
