### ISSUE TITLE
Text spacing on profile page; and profile name font 

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#361]
'The line spacing in the "about me" copy on the profile page is very tight.  

Also, in general, the spacing between headings and text on the profile page is very tight (e.g. between About Me heading and copy, between Interests heading and interest buttons, spacing in Organization Info section).

Also, the person's profile name should be in a bolder typeface.  

See beta vs. original Figma design below.

![image](https://user-images.githubusercontent.com/68029138/88058983-38cd3f80-cb32-11ea-908b-d6d4d89a7fcb.png)

![image](https://user-images.githubusercontent.com/68029138/88059077-569aa480-cb32-11ea-8d94-5acebda6e9e5.png)

**Comment by mmacedom** [comment]
@MattMilesJC @lucastbelem this has been addressed with a new PR. Please advise if there needs to be further changes to spacing on it. Thanks
