### ISSUE TITLE
Resource: Header text

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#364]
Can we fix a couple of things here:

1. Header text is too large compared to Figma
2. Text box for header text should be wider (i.e. I need to write "Youth Curriculum")
3. Description text box is too short and narrow. I need to be able to put a couple lines of text in there.
4. Header text, boxed-in text, and description text need to be unique for each resource page (i.e. kids, jr. high, etc). Currently, when I add boxed-in text for Jr. High, it display that text for every page.

**Comment by mmacedom** [comment]
@lucastbelem I just pulled from master and still can't get into Resources. I will fix these issues once I am able to.

**Comment by GeorgeBellTMH** [comment]
Can you create a new resource?

**Comment by mmacedom** [comment]
@GeorgeBellTMH Yes I can now. The hero image is not appearing at this point though. Is it because it hasn't been populated on the back end for this particular resource?

**Comment by GeorgeBellTMH** [comment]
You have to create a hero image by uploading it...click the icon...

**Comment by GeorgeBellTMH** [comment]
You can change fields in the header by long clicking...then they change to text boxes...

**Comment by GeorgeBellTMH** [comment]
Also, I have just pushed a change, so you should be able to add series and add episodes now...

**Comment by mmacedom** [comment]
@lucastbelem I fixed the height of the description so it can fit 3 lines as requested. As far as the size of the size of the header, it is set at 100px (like the mockup) let me know if you still like it to be smaller. 

As far as point 2 and 4, I had pushed a PR with adjustments addressing this. I will see if I can find them. If not, I will adjust as well.

**Comment by mmacedom** [comment]
@GeorgeBellTMH Would you know why the changes on this PR "resource - hearderGroupBoxText Conditions #317" are not reflected on the up to date ResourcesHeader file?

**Comment by GeorgeBellTMH** [comment]
We modified it so that it is an editable text box...instead of hardcoded values.

**Comment by GeorgeBellTMH** [comment]
https://github.com/jesus-collective/mobile/commit/8c59fe004c8ff50398d58199c2d7cdb97b20b717 you can see the changes there...

**Comment by mmacedom** [comment]
@lucastbelem I adjusted everything now as requested. The header font size is smaller than the mock up's but it is smaller now. Let me know what you think. Thanks
