### ISSUE TITLE
Initial CRM

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#391]
* [x] List users and their status
* [x] Show user groups
* [x] Add user to group
* [x] Remove user from group
* [x] Invite User
* [x] Payment status

Messaging - Admins can:

* [ ] Ability to message individual users via email, txt, phone or mobile alert
* [ ] Ability to create a group of users and message via email, txt, phone or mobile alert
* [ ] Ability to message all members of a resource or organization
* [ ] Ability to message all friends, partners, admins, verifiedUsers or unverifiedUsers
* [x] Ability to invite someone to join JC by email, phone or txt
* [ ] Receive messages from users who have been messaged
* [ ] See stats on messages sent (% opened, etc.)

Stats/Usage - Admins can:

* [ ] See when user last logged in
* [ ] See users activity/history
* [x] See users payment history

Access - Admins can:

* [x] Force convert someone to Friend, Partner, Admin
* [ ] Force delete or block someone
* [ ] Force delete messages
* [ ] Force a user password reset

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713144931)

**Comment by GeorgeBellTMH** [comment]
For inviting users we need to implement https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html as part of the admin query

**Comment by GeorgeBellTMH** [comment]
@lucastbelem once we deliver the next version can you test out the CRM functions, specifically inviting users...(click the rocket ship, go to CRM and then enter an email and click invite)

**Comment by GeorgeBellTMH** [comment]
- [ ] Added ability to add/remove payments

**Comment by lucastbelem** [comment]
Turns out the initial CRM will likely be the on-going CRM.
