### ISSUE TITLE
Need a mini version of MessageBoard

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#396]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/47749730/89458434-0415d680-d735-11ea-99cb-a9440ac801cb.png">

@mmacedom: 

I've added a this.props.style="mini"|"regular" on the MessageBoard component...so you should be able to do different things with the style to get it to work...essentially you can do:

style={this.props.style=="mini"?style.miniButtonStyle:style.regularButtonStyle}

Regular is what we currently have on the main message board screens, mini is the 1/3 screen we have in courses right now.

**Comment by GeorgeBellTMH** [comment]
I'm fine in this view if you want to get rid of the profile image, and you can probably just have the icon on the upload file button...

**Comment by mmacedom** [comment]
@GeorgeBellTMH Thanks! You read my mind. I made a note last night to write you about this message board!

**Comment by mmacedom** [comment]
@GeorgeBellTMH I pushed some changes. Let me know what you think of them

**Comment by GeorgeBellTMH** [comment]
Yup, it's good (I made some changes to remove some duplicate code)...can you get rid of the margin around it? Make it take up the full width of the header, and remove the gap between the line and it...the more room for writing the better...

**Comment by mmacedom** [comment]
I adjusted it.
