### ISSUE TITLE
Profile - User name

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#399]
Most profile fields are editable, however the a person's name isn't. Can we make it so people can change their names? I.e. someone who gets married.

**Comment by GeorgeBellTMH** [comment]
When we update user name/email we also need to update cognito.

**Comment by lucastbelem** [comment]
Manually or from the user's edit?

**Comment by GeorgeBellTMH** [comment]
Yah, it's just I have to update it in two places...not a big deal, just put a note to remind myself...
