### ISSUE TITLE
Resources: Podcasts

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#406]
For V1 of podcasts, we'd like to replicate as much of the marketing website design of podcasts as possible as seen here: https://www.figma.com/file/IblPMRd9fD1XdImFYRBeuG/JC-Website?node-id=1234%3A10900

**Comment by mmacedom** [comment]
@lucastbelem Do we have this feature up? I can't find it on my local.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH did we get this done? It's not needed yet, but I remember that you did some work on this already, so I wanted to check. If we have it, Mateus can get on to it. We want to replicate as much of design style found here as possible: https://jesuscollective.com/media/podcasts. @mmacedom it's not priority yet, so it might not be ready.

**Comment by GeorgeBellTMH** [comment]
Not done yet...bascially we need to create an RSS reader component and then get it pointing at different podcasts...likely each resource should be able to contain multiple RSS readers...

**Comment by lucastbelem** [comment]
Closing for now as resource design won't change.
