### ISSUE TITLE
Courses: Can't access on dev

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#407]
There used to be a button called "go to course". I get why it's gone, but is there a way to see what courses are looking like in the meantime?

**Comment by GeorgeBellTMH** [comment]
Is this fixed? If you have joined the course you should see it...

**Comment by lucastbelem** [comment]
<img width="974" alt="Screen Shot 2020-08-24 at 11 39 03 AM" src="https://user-images.githubusercontent.com/48295718/91065426-7116e080-e5fe-11ea-86ff-cfd77daeffef.png">

Still don't see the "Go to course" button.
