### ISSUE TITLE
Message board is busy...

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#409]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/47749730/90356097-56e86b80-e01c-11ea-9e41-cf12bc6e6716.png">

I think you can make it have the date below, and just show the first name (with full name in a tool tip when you hover).

**Comment by GeorgeBellTMH** [comment]
Probably don't need to have their role...

**Comment by mmacedom** [comment]
@GeorgeBellTMH I just fixed it. I reflowed the date below the name on the "mini" board. It seems like there is enough space for both the first and second name. Let me know your thoughts
