### ISSUE TITLE
Timezone is unclickable, and should be regular height dropdown (on events and courses)

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#412]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/47749730/90850909-1309a500-e341-11ea-8c95-f3a71b9548a3.png">

**Comment by mmacedom** [comment]
@GeorgeBellTMH Please let me know if you are still seeing this issue on your end.

**Comment by mmacedom** [comment]
@GeorgeBellTMH @lucastbelem Please let me know if you guys see this issue. Thx
