### ISSUE TITLE
Can't create new courses

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#426]
When I click "create new course" I get a blank screen. Similar to the events issue and the issue Matt Miles is having. Something is broken.

**Comment by GeorgeBellTMH** [comment]
Can you validate this works on dev and then I will publish it to beta tomorrow...

**Comment by lucastbelem** [comment]
Just checked dev and am able to create courses now :)

Thanks man!

Before you publish to beta, can you please re-label:

Learning Groups to Cohorts;
Cohorts to Learning Collective;

Thanks!
