### ISSUE TITLE
input errors show up at bottom of screen

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#429]
Can we bring the warnings up closer to the button, so when you click the save button if there is a warning/error on the input that we see it...right now it's at the very bottom of the page...

**Comment by mmacedom** [comment]
@GeorgeBellTMH We certainly can. Can you let me know on what screen?

**Comment by lucastbelem** [comment]
@mmacedom George is referring to the event creation screen.

**Comment by mmacedom** [comment]
Thanks @lucastbelem. I just fixed it
