### ISSUE TITLE
Events moved to previous too soon

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#430]
It looks like events on the platform are moved to 'previous events' as soon as the START time of the event has passed.  For example, an event that starts at 2pm on Sept 20 becomes a previous event at 2pm.  This causes confusion because people try to log on at 2 pm (or after) and can't find the event unless they look in 'previous' events.  The event should not be classed as a 'previous' event until it is over.

**Comment by lucastbelem** [comment]
We don't currently ask the user for an event end time, and therefore, cannot use that parameter to move the event to "previous". For now, can we make it so the event doesn't move to previous until the end of the day?
