### ISSUE TITLE
Can't see my pin on the map

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#431]
I (Matt) can't see my pin on the map.  Wondering if this means other pins may also not be visible, or if it's just because it's my own pin and users can't see their own pins.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeorgeBellTMH** [comment]
I think we filter your pin out...but there is currently a limit on the number of pins, so you can't see everyone on the map...
