### ISSUE TITLE
Hyper sensitive dashboard carousel on mobile

### ISSUE THREAD

**Issue by MattMilesJC** [jesus-collective/mobile#432]
When I try to swipe the carousels on the dashboard it immediately clicks the one I touch first rather than letting me swipe.  I'm using a Samsung S8 with Chrome.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucastbelem** [comment]
Closing this for Nathan's scope.
