### ISSUE TITLE
Blank screen at profile creation persists

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#434]
Message from Angela Lam:

"Two members of my Hub are still getting the blank screen issue when they try to create their profiles on the JColl platform.  I know we thought the bug was fixed, so perhaps this is an issue with cache on their specific computers?  I have no idea how ignorant that question may be :)

In case it's helpful, one partner reported that they've tried on both Chrome and Safari.  Thanks for any guidance you can provide!"

**Comment by GeorgeBellTMH** [comment]
Can I get their names, also were they trying to do an organization or regular login?

**Comment by lucastbelem** [comment]
David Hines is one.

I believe regular - did we make orgs available on beta already?

**Comment by lucastbelem** [comment]
The blank screen on my end seems to be solved now.

**Comment by lucastbelem** [comment]
Just waiting to hear back from David to confirm problem is solved.

**Comment by lucastbelem** [comment]
I can confirm this problem is solved.
