### ISSUE TITLE
Instructor description field design

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#447]
Instructor description in course design is not matching figma - it seems there a box surrounding the text.

<img width="1066" alt="Screen Shot 2020-09-28 at 9 20 30 AM" src="https://user-images.githubusercontent.com/48295718/94437614-ff393600-016b-11eb-84b1-c5f23d461273.png">

**Comment by mmacedom** [comment]
@lucastbelem I am trying to replicate this bug on my local but have not been able to do so both on edit and non edit mode on the course home description (please see attached). I'll bring this up with George to see why there's such thing happening. 
<img width="1413" alt="Screen Shot 2020-09-28 at 8 27 07 PM" src="https://user-images.githubusercontent.com/24467324/94498866-3f7ad180-01c9-11eb-908c-bde77ea8be44.png">

**Comment by lucastbelem** [comment]
@mmacedom this seems to be resolved, so I'm closing.
