### ISSUE TITLE
Cohorts do not appear

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#448]
I created a test course and see the learning collective as I add people to cohorts. However, when I save it, the learning collective appears with everyone I've added to any cohort, but the cohorts themselves do not appear.

<img width="819" alt="Screen Shot 2020-09-28 at 9 23 40 AM" src="https://user-images.githubusercontent.com/48295718/94437918-68b94480-016c-11eb-9e1c-73ed9fe7cc42.png">

**Comment by lucastbelem** [comment]
My mistake.

**Comment by GeorgeBellTMH** [comment]
Cohorts only appear if you are assigned to one as a coach or member. Probably for admins it should list them all...

Sent from my iPhone

On Sep 28, 2020, at 10:20 AM, Lucas Belem <notifications@github.com> wrote:

﻿

Reopened #448<https://github.com/jesus-collective/mobile/issues/448>.
