### ISSUE TITLE
Bug creating zoom url

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#449]
When I create a new zoom assignment in courses, there is a bug occurring where as I type into the field, the characters get jumbled and the url does not form as I typed it.
<img width="782" alt="Screen Shot 2020-09-28 at 9 26 24 AM" src="https://user-images.githubusercontent.com/48295718/94438237-d5344380-016c-11eb-96e9-7d36db9c165c.png">

**Comment by lucastbelem** [comment]
I can paste the url, so that's not as high priority as I thought.

**Comment by lucastbelem** [comment]
@itbel I think you fixed this, but I never assigned the issue right? Can you confirm please?

**Comment by itbel** [comment]
> @itbel I think you fixed this, but I never assigned the issue right? Can you confirm please?
I didnt I finish it.
