### ISSUE TITLE
Course marketing page styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#450]
When I put a lot of content into the course marketing page right column, the text box stays the same size and content is scrollable. As seen here: 
<img width="920" alt="Screen Shot 2020-09-28 at 9 38 47 AM" src="https://user-images.githubusercontent.com/48295718/94439541-89829980-016e-11eb-9e77-22ec88276186.png">

I need this content to fill the page instead and when saved, it should not look like a text box (as per figma design).

**Comment by mmacedom** [comment]
Sorry for the question @lucastbelem but can you clarify how you arrived at this screen. I found it on the mock up but have not been able to find this screen on local.

**Comment by lucastbelem** [comment]
@mmacedom sure thing. This page is available by being a course user who hasn't paid for a course yet. You can also create a new course to see what the page is supposed to look like.

**Comment by mmacedom** [comment]
@lucastbelem the issue has been fixed. Please let me know if you still see the scrolling behaviour and the grey border on the right side. The left side has been adjusted as well

**Comment by mmacedom** [comment]
@lucastbelem I have adjusted this on all devices.
