### ISSUE TITLE
Menu items in courses

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#451]
Menu items should change to "Week 1", "Week 2", etc as the user creates new menu items/weeks. Currently, the button says "new menu item", but once the first item is created, it should change to whatever the user calls that item (i.e. Week 1).

**Comment by GeorgeBellTMH** [comment]
You can click and hold to rename menu items.

Sent from my iPhone

On Sep 28, 2020, at 9:47 AM, Lucas Belem <notifications@github.com> wrote:

﻿

Menu items should change to "Week 1", "Week 2", etc as the user creates new menu items/weeks. Currently, the button says "new menu item", but once the first item is created, it should change to whatever the user calls that item (i.e. Week 1).
