### ISSUE TITLE
Text box around assignment description

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#452]
Similarly to the instructor description, a text box is wrapped around the assignment description. The ideal behaviour would be for there not to be a text box around the text when in view mode and more importantly,  rather than scroll within the box, the text would push contents below it further down so that the page is scrollable (rather than the text box). 

<img width="1199" alt="Screen Shot 2020-09-28 at 10 14 09 AM" src="https://user-images.githubusercontent.com/48295718/94443768-8d64ea80-0173-11eb-9a9d-eb7cdc198620.png">

**Comment by mmacedom** [comment]
@lucastbelem I just took a look at this and similarly to my previous comment about the grey box, for whatever reason, I am not able to replicate this bug on my local. However, I did fix the overscroll. The copy content should push everything down once in place. I'll also ask George about this

**Comment by mmacedom** [comment]
<img width="1368" alt="Screen Shot 2020-09-28 at 9 27 05 PM" src="https://user-images.githubusercontent.com/24467324/94502108-69d08d00-01d1-11eb-9565-8b7c31c6d6fc.png">
<img width="1385" alt="Screen Shot 2020-09-28 at 9 27 12 PM" src="https://user-images.githubusercontent.com/24467324/94502109-6b9a5080-01d1-11eb-96d5-0728f800a180.png">

**Comment by lucastbelem** [comment]
Seems to have resolved itself as well.
