### ISSUE TITLE
Todo list issues

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#455]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/47749730/94507513-ea958600-01dd-11eb-9a70-0092837dbdf6.png">

**Comment by mmacedom** [comment]
hey @GeorgeBellTMH. What browser is this on? I'm on Chrome and my local is showing this (see below). Let me know so I can sort this out. Thx

<img width="1413" alt="Screen Shot 2020-09-28 at 8 27 07 PM" src="https://user-images.githubusercontent.com/24467324/94508643-64c70a00-01e0-11eb-8de3-7f03552b1b5c.png">

**Comment by GeorgeBellTMH** [comment]
Safari.

Sent from my iPhone

On Sep 28, 2020, at 11:15 PM, mmacedom <notifications@github.com> wrote:

﻿

hey @GeorgeBellTMH<https://github.com/GeorgeBellTMH>. What browser is this on? I'm on Chrome and my local is showing this (see below). Let me know so I can sort this out. Thx

[Screen Shot 2020-09-28 at 8 27 07 PM]<https://user-images.githubusercontent.com/24467324/94508643-64c70a00-01e0-11eb-8de3-7f03552b1b5c.png>

**Comment by GeorgeBellTMH** [comment]
I've fixed this.
