### ISSUE TITLE
Courses secondary nav styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#463]
We decided today to not follow the Figma designs for this menu (i.e. Week 1, Week 2). Can we please make it so that the week that is select gets its font changed to white so the user knows which week they are looking at?

**Comment by mmacedom** [comment]
@GeorgeBellTMH. How do you suggest I approach this? I tried using state.activeWeek as a condition trigger to change styles but by itself it's not enough to trigger the change. When I console.log(activeWeek), I get integers indexes for each label position (0, 1, 2, 3, 4). Let me know if this makes sense to you.

**Comment by GeorgeBellTMH** [comment]
I have done this.
