### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#471]
Clicking any links in courses (i.e. embedded links in assignments, zoom links, etc) should open in new window.

**Comment by GeorgeBellTMH** [comment]
Should be able to fix this by changing the navigation.push (or navigate) to window.open(path);

**Comment by GeorgeBellTMH** [comment]
Links in rich text box should be able to be customized to alway open in new tab....need to investigate how to do that...

**Comment by mmacedom** [comment]
@GeorgeBellTMH @lucastbelem This has been fixed
