### ISSUE TITLE
Zoom assignment design

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#472]
When I click on a zoom assignment, it should look like this:
![HEADER](https://user-images.githubusercontent.com/48295718/94682869-9b417980-02f3-11eb-9ef2-9c1b5555664c.png)

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH Are we also moving the mini message board from the right side to underneath all of call content?

**Comment by GeorgeBellTMH** [comment]
That's a separate ticket...let's not worry about mini message board now...I want to focus on flipping assignments first...I have some work to do on it first...there is also a bunch of stuff to get mini message boards expandable/contractable etc...I have a bunch of work on that.

**Comment by mmacedom** [comment]
Ok

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH, all of those screens have been re styled to match the mock up. (zoom, assignment and response)
