### ISSUE TITLE
Profiles should have events and group membership

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#48]
When looking at my own profile, I should be able to see a list of events and groups I'm a part of or own as per design found here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=415%3A13

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713146150)

**Comment by GeorgeBellTMH** [comment]
All profiles should show the events and groups that the user is a member of.

**Comment by GeorgeBellTMH** [comment]
My groups now exists on the homepage, just need to put MyGroup into the profile and hide some things...

**Comment by JonEsparaz** [comment]
Not necessarily a priority, but adding this resurfaces the conversation of having an actual edit profile page/button. If people are going to their profile to see their events and groups, wouldn't they want an cleaner experience without all the text fields?

**Comment by lucastbelem** [comment]
Yeah, this can be a v2 improvement, but I do think we should make their own profiles clearer without all of the text edit fields.
