### ISSUE TITLE
Reorder Weeks/Lessons

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#483]
Not sure if this is needed...

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713146220)

**Comment by GeorgeBellTMH** [comment]
You can delete and recreate...

**Comment by JonEsparaz** [comment]
https://github.com/jesus-collective/mobile/pull/843/commits/6b46353ec1f6b89b1421e4907bac4aad399fbe9a handles this for lessons.
