### ISSUE TITLE
Watching in assignment videos

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#484]
Need to test if you can embed a YouTube in rich text boxes...

This in theory does work for zoom and zoom recordings

**Comment by GeorgeBellTMH** [comment]
Ok, you can now add a YouTube lesson type! Select YouTube from dropdown and enter the id...on the lesson page you can click edit and change the description below it...

**Comment by lucastbelem** [comment]
@mmacedom anything we need to do with the design?

**Comment by mmacedom** [comment]
@lucastbelem I just took at look at it and it seems like things are in place. Please let me know otherwise
