### ISSUE TITLE
Save and edit assignments as drafts

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#485]
Need ability to save and edit assignments, as of right now they can only be posted.

* [ ] When user is seeing their own assignment, there should be an "edit" button that allows them to change their assignment post.
* [ ] When user re-submits (or saves) the assignment, a tag indicates when the assignment was last updated for other users to know.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713146274)

**Comment by itbel** [comment]
done
