### ISSUE TITLE
Implement Activity

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#489]
Need to implement activities in courses...

**Comment by lucastbelem** [comment]
Design: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=1528%3A0

Implement an activities table on the course home page to indicate to the user recent activities: i.e. assignment submissions

**Comment by lucastbelem** [comment]
Fields to include:
- Creator of activity
- What group to connect it to: type as course
- Time
- Date
- Ability to link to it
