### ISSUE TITLE
Assignment Responses Flip

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#491]
Assignments Responses now show as follows:

[Assignment - always shows at top]
[Load More Button if needed]
[Messages with oldest at top, newest at bottom]
[Message Input Box]

Clicking Load More will load more items in the load more spot (currently we load 100)

Coach and Admin will see a message that no assignments are submitted until an assignment is posted

**Comment by GeorgeBellTMH** [comment]
cc: @lucastbelem @mmacedom

**Comment by GeorgeBellTMH** [comment]
Let me know if I can close this....

**Comment by mmacedom** [comment]
@GeorgeBellTMH I haven't been able to check the latest pull tonight. Something went wonky with the code. I sent you an email with the error
