### ISSUE TITLE
Todo list is static

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#493]
The Todo list should show only the upcoming/incomplete items...right now it shows everything...

**Comment by GeorgeBellTMH** [comment]
I've limited it to the first 7 items for now....

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can we enable this by March 16 and make it show no more than 7 and only upcoming items, rather than all items?

**Comment by JonEsparaz** [comment]
Per my discussion with Lucas, implementation is as follows:
- Only upcoming items are displayed
- 7 (or whatever integer) items are displayed to start
- Infinite scroll for the remaining items
