### ISSUE TITLE
Spaces in uploads are not handled correctly

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#494]
Need to do further improvements on file uploads to handle all encodings...(profile, resource and course)

**Comment by branden-eyk** [comment]
@GeorgeBellTMH is this issue still relevant? @lucastbelem has me digging through issues looking for ones I think I can handle, and I might be able to help with this. I'm at least familiar with validating/re-formatting user input/file names in other languages so I at least have an idea of what could be done in other contexts.

**Comment by GeorgeBellTMH** [comment]
yup

**Comment by lucastbelem** [comment]
@GeorgeBellTMH @branden-eyk I think we're good here now :)
