### ISSUE TITLE
Maps: Map on profile page

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#50]
When viewing my own or someone else's profile, a map should appear that pinpoints their location as per the design here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=415%3A13

**Comment by GeorgeBellTMH** [comment]
Also their location should not be shown as GPS coordinates

**Comment by GeorgeBellTMH** [comment]
Should be able to use existing, just need to pass in the map item and enable the map on the profile page.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH so we definitely need an [API key](https://developers.google.com/maps/documentation/geocoding/get-api-key) and billing has to be enabled. GCP has $200 USD free credit per month, which is 40,000 requests. After that its $5 USD per 1000 requests. Probably best to make an API request only when a user saves their location to stay within the free tier. Alternatively, we could just use the city and province the person types in, thoughts?
