### ISSUE TITLE
Test: Email Messages Alerts work for group/events/orgs/resources/courses

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#501]
This is done in dev now...please test:

- [x] Direct messages should send an email saying user got DM with the content
- [x] Content is well formatted and no problems with weird content
- [x] All email Fields are correct, chrome around the message is correct
- [x] Messages from Groups/Events/Resource/Courses/Orgs should all come through with subject saying what they are
- [x] Messages only sent to people who are following the group (and only once)
- [x] setting alert configs under user profile to false should prevent emails from being received

**Comment by GeorgeBellTMH** [comment]
Can you also discuss with the team about when we can turn this on...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH 
> * All email Fields are correct, chrome around the message is correct
I'm not sure what you mean. Nothing chrome coming through the email, but everything looks fine.

- Emails are not being sent to group/event owner.
