### ISSUE TITLE
Test: Mobile

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#502]
I think it would be good to do a run of tests on mobile (both browser and iOS/Android app)

* RichTextBox doesn't work
* MessageBoard and courses won't work as well
* We can add users on TestFlight and Android now

The following should work at this point:

* [ ] Login process
* [ ] Create a new user process
* [ ] Create a new org process
* [ ] Reset PW, pin, invitations
* [ ] Styling issues
* [ ] homepage
* [ ] Menu
* [ ] All the list pages (Events, Groups, Resources)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713146507)

**Comment by lucastbelem** [comment]
Login doesn't work. Tried to login with existing JC account and couldn't. Kept saying "user doesn't exist". Then tried to create a new account and couldn't either. Confirmation code never delivered.

**Comment by GeorgeBellTMH** [comment]
Is this on prod or dev?

**Comment by lucastbelem** [comment]
What is this for @GeorgeBellTMH? Is it still relevant?
