### ISSUE TITLE
Kids and Youth Profile Questions

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#504]
Please let me know what they are

**Comment by lucastbelem** [comment]
[Here](https://docs.google.com/spreadsheets/d/1axqz0NfQRLuemFfh6lBnCBNXlM0ZYXvc0cJlJZqf9A4/edit?usp=sharing) is the google doc with fields. You can see them in the tab "pilot" under "Kids and Youth Curriculum". 

Let me know if you have questions when you get there.

**Comment by lucastbelem** [comment]
You'll see that it's not so much that they are different (some are) than the other profiles, but rather, that we want to ask less questions of kids and youth people.

**Comment by lucastbelem** [comment]
This is now in the main kids and youth sign in issue.
