### ISSUE TITLE
Customize login experience for Kids and Youth

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#505]
- [ ] Invitations
- [x] Can determine where user is coming from K&Y or JC
- [ ] Asks user if origin is unknown
- [ ] Customized profile for K&Y users
- [x] K&Y Permissions
- [x] K&Y Payment
- [ ] Determine if they should go to homepage or not

**Comment by lucastbelem** [comment]
As part of this conversation, please also note:

- New unified profile fields AND product questions found [here](https://docs.google.com/spreadsheets/d/1axqz0NfQRLuemFfh6lBnCBNXlM0ZYXvc0cJlJZqf9A4/edit?usp=sharing). I simplified it as much as I could. Let's chat on Monday to make sure we're on the same page. Bottomline - we now have 1 profile for all users with some dependencies.
- Partner applications is cancelled on the platform. Partners apply via formstack from the marketing site. Once approved manually, we should be able to invite them into the platform, to the appropriate payment screen, followed by the profile screen.
- Leadership Development application: Same as above. These users receive partner status on the platform during their course and for 3 months after, at which point they are asked if they'd like to apply for partnership or not.
- Users who purchase only kids and youth curriculum are considered friends in the a la carte level and have the same experience, whether they signed up via the curriculum OR Jesus Collective marketing sites.
- All access friends - future offering. These are friends who get access to all resources. Detailed user journey will need to be fleshed out next year.

**Comment by GeorgeBellTMH** [comment]
Closing as most of this is already individual tickets, or outdated.
