### ISSUE TITLE
"Show All" Group or Events design

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#51]
When I go into "Show All" for events or groups, the "People you may want to connect with" and "Latest conversations" should disappear. The events and groups should extend to the whole page displaying all events as per design here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=415%3A13

**Comment by GeorgeBellTMH** [comment]
@mmacedom I have removed the right column sections on the show all pages, you can change this to a grid now (it should scroll vertically in desktop, and be however many cards wide that fit on the screen...)

**Comment by GeorgeBellTMH** [comment]
@mmacedom you can use the following code in MyGroups for picking the style depending on whether the items should wrap or not...(wrap is true if it should wrap)

style={this.state.wrap?styles.firstStyle:styles.secondstyle}

**Comment by mmacedom** [comment]
@GeorgeBellTMH great!

**Comment by mmacedom** [comment]
@GeorgeBellTMH I added the code you sent above in that container, created the classes in style.ts, modified the class name in the code above and also checked that the prop was set to boolean in the interface Props on line 22 of MyGroups and the component is not wrapping in the "Event" or "Group" screens. 

The "this.state.wrap" was giving an error saying that "wrap was not set in readOnly<State> so I added "wrap: boolean" to State on line 40. It still didn't work. Any suggestions?

**Comment by mmacedom** [comment]
@GeorgeBellTMH Shouldn't the wrap prop be initialized?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH is this done?

Also, I got confirmation today that past events can actually disappear from dashboards, EXCEPT when a resource was added to that event by means of a message board upload.

**Comment by GeorgeBellTMH** [comment]
Not sure what that means....resources can't be uploaded...do you mean file attachments?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH sorry for the lack of clarity - yes, file attachments.
