### ISSUE TITLE
Payments features and flow - One Story

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#512]
Payment features:

- [x] Users should be able to purchase products on the platform via Stripe.
- [x] These product purchases should generate customers, invoices, and subscriptions in Stripe.
- [ ] Users should be able to choose between monthly or annual billing.
- [x] Users should be billed based on this preference automatically (i.e. if monthly, payment should be processed automatically after the initial payment method set up)
- [x] Users should be able to purchase more than 1 curriculum product in one sale (i.e. Early years AND Kids AND Youth).
- [ ] If the user comes from existing kids and youth website (current curriculum users who are transitioning), we want to be able to ask them if when they want to defer their payment by 1, 2, or 3 months. There are more details on this, but it's doable through Stripe - let's talk.

Bonus for this round:
- [ ] Platform CRM should show user payment status (i.e. up to date, or overdue, etc - this is an extra win as JC admins can see this info in Stripe)

**Comment by GeorgeBellTMH** [comment]
I'm closing this for now, please create individual tickets for the remaining items.
