### ISSUE TITLE
Without admin, I cannot login

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#517]
I removed my admin permission to test the payment function and hit the white screen below. 

<img width="1431" alt="Screen Shot 2020-12-12 at 9 02 51 AM" src="https://user-images.githubusercontent.com/48295718/101985939-e9122080-3c58-11eb-839a-c0b925c756b3.png">

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this still occurs. Invited user is created, but is presented with a blank screen rather than the payment screen.

**Comment by GeorgeBellTMH** [comment]
Should be fixed.
