### ISSUE TITLE
"Add page item" not working properly

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#521]
When I add a new page item and choose header, this happens:

<img width="1046" alt="Screen Shot 2020-12-16 at 2 50 00 PM" src="https://user-images.githubusercontent.com/48295718/102399096-2acefe00-3fae-11eb-918f-364dcd027fb9.png">

**Comment by lucastbelem** [comment]
@GeorgeBellTMH also this:

<img width="678" alt="Screen Shot 2020-12-16 at 7 26 19 PM" src="https://user-images.githubusercontent.com/48295718/102422388-ad6ab400-3fd4-11eb-8630-5d2d7bb880f8.png">

**Comment by GeorgeBellTMH** [comment]
This should work....please try again....

**Comment by lucastbelem** [comment]
@GeorgeBellTMH the problem seems to persist, at least when "header" is the item selected.

<img width="1102" alt="Screen Shot 2020-12-18 at 9 38 37 AM" src="https://user-images.githubusercontent.com/48295718/102626575-ff1a5800-4114-11eb-9906-468e35cabe30.png">

**Comment by lucastbelem** [comment]
@GeorgeBellTMH ok, so here is what's going on...remember when you made tons of changes to courses and I couldn't see them and it turned out it was because of something in the dev console? Something about service workers? So I can see the fix now, but to do so I had to go to the dev console and in the service worker in applications and manually change the status by pressing "skip waiting". Is it possible we've made a change somewhere along the way that reverted to how it was in September, where the changes made by you didn't propagate?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this however is still happening:

<img width="631" alt="Screen Shot 2020-12-18 at 9 48 52 AM" src="https://user-images.githubusercontent.com/48295718/102627517-4e14bd00-4116-11eb-9f86-b8c9a9f6b58a.png">

**Comment by GeorgeBellTMH** [comment]
I have turned off service workers…so hopefully this is no longer an issue...

**Comment by GeorgeBellTMH** [comment]
This is fixed now.
