### ISSUE TITLE
Still hitting blank payment screen for invited email

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#522]
As attached below. Is it because I need to created a product and then link it to the resource and then invite the person to it? Then they can actually see the payment screen?

<img width="1413" alt="Screen Shot 2020-12-16 at 9 13 03 PM" src="https://user-images.githubusercontent.com/48295718/102434865-a13a2300-3fe3-11eb-8019-8af72a3373bc.png">

**Comment by GeorgeBellTMH** [comment]
Try again...
