### ISSUE TITLE
Header image colour

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#524]
In the previous design, the header image had a black and white filter. In the new design, it should not. Here is what it looks like now:
<img width="1440" alt="Screen Shot 2020-12-18 at 9 50 16 AM" src="https://user-images.githubusercontent.com/48295718/102627678-84ead300-4116-11eb-975b-6ff85506865a.png">

**Comment by GeorgeBellTMH** [comment]
I have removed the filter.
