### ISSUE TITLE
Payment processes but user can't go anywhere

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#527]
<img width="1439" alt="Screen Shot 2020-12-18 at 10 50 28 AM" src="https://user-images.githubusercontent.com/48295718/102635530-748c2580-4121-11eb-8e96-e15a4fe2d2c0.png">
 
<img width="1420" alt="Screen Shot 2020-12-18 at 10 49 34 AM" src="https://user-images.githubusercontent.com/48295718/102635545-7b1a9d00-4121-11eb-90a4-e713ae0d53f9.png">

**Comment by GeorgeBellTMH** [comment]
Make sure you include verifiedUsers and subscriptionValid groups in the price in stripe
