### ISSUE TITLE
Payment confirmation screen

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#530]
Payment confirmation screen. Design update needed:
![](https://user-images.githubusercontent.com/48295718/102664722-5dfdc280-4151-11eb-8990-e489efb8185c.png)

Figma mock up:
![20 10 - SIGNUP](https://user-images.githubusercontent.com/48295718/102664741-6ce47500-4151-11eb-9eb2-5dc90b16195f.jpg)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713147280)

**Comment by lucastbelem** [comment]
@mmacedom this is another one for you if you're waiting for the stuff from George.

**Comment by GeorgeBellTMH** [comment]
I've changed the text and buttons, so this is almost done...

**Comment by lucastbelem** [comment]
@mmacedom you can find this screen now:

- Go to dev and sign up with a new account;
- Process a payment with the credit card number I emailed you. It'll take a few minutes to process. 
- You're now at the processed payment screen.

**Comment by mmacedom** [comment]
@lucastbelem. I pushed some changes to the page but will need to revisit this because I have to create a new profile every time I save the file as I cannot go back to the payment page again. Can you check on dev?  

@GeorgeBellTMH Is there a way to access the payment confirmation page without creating a new user every time?

**Comment by lucastbelem** [comment]
@mmacedom Sounds good.

I've reset all of the users you entered to no access (meaning that they'll see the payment screen again). Basically, I have to reset those users in the backend each time. So let me know when you need a user reset.

**Comment by mmacedom** [comment]
@lucastbelem I just tried a new account and got this error (see image below). 
<img width="902" alt="Screen Shot 2021-01-31 at 10 11 32 PM" src="https://user-images.githubusercontent.com/24467324/106410679-5fd5c980-6411-11eb-9f84-9da1e80b577b.png">

Can you reset this user again? Thx

**Comment by lucastbelem** [comment]
Just sent you a reset password.

**Comment by mmacedom** [comment]
@lucastbelem Just tried and got this error 
<img width="588" alt="Screen Shot 2021-01-31 at 10 43 26 PM" src="https://user-images.githubusercontent.com/24467324/106412431-c2c95f80-6415-11eb-94b7-2a20d1c63e7b.png">

**Comment by lucastbelem** [comment]
@mmacedom this user is already confirmed...I can't un-confirm an account from my end...you may just need to reset password at this point.

**Comment by mmacedom** [comment]
@lucastbelem Thanks. It worked but I need to get access to it again. Can you reset the same user? Thx

**Comment by lucastbelem** [comment]
@mmacedom done :)

**Comment by mmacedom** [comment]
@lucastbelem I'm literally stuck on this screen and cannot log out of this lol...
@GeorgeBellTMH I already re ran npm (install and start) and my local is bringing me back to this screen. Any clue how to get out of this?
<img width="1382" alt="Screen Shot 2021-01-31 at 11 28 44 PM" src="https://user-images.githubusercontent.com/24467324/106415354-e47a1500-641c-11eb-9768-a0b5f63b7233.png">

**Comment by lucastbelem** [comment]
@mmacedom I can give you admin. That will bypass that screen, but you won't get to the payment screen.

**Comment by lucastbelem** [comment]
@mmacedom nevermind what I said...I raised an issue for this in git for George. The webhook is not sending the groups to AWS so that page is stuck. I can set the group manually if you need to move forward with that account.

What are you trying to fix?

**Comment by mmacedom** [comment]
@lucastbelem Thanks for the info. I need to go back into that screen to add the checkmark symbol.

**Comment by lucastbelem** [comment]
@mmacedom Ok I think I figured it out...George changed something, so now, when you pay, but something goes wrong, you face that screen, rather than nothing happening. I'll delete your user and you can create it again and go through payment.

It's possible that George made it so that the user doesn't sit on that screen for more than a few seconds, so you may not actually be able to see it long enough to style it.

Your user is deleted now.

**Comment by mmacedom** [comment]
@lucastbelem That did it. thanks

**Comment by mmacedom** [comment]
@lucastbelem could you reset the user above again? Thank you

**Comment by lucastbelem** [comment]
@mmacedom finally got around to this!! Sorry! The account is reset.

**Comment by lucastbelem** [comment]
@mmacedom the page still doesn't seem to be styled as per the figma file. Can you take a look when you have a moment? This is what I'm currently seeing.

<img width="1437" alt="Screen Shot 2021-03-30 at 4 43 57 PM" src="https://user-images.githubusercontent.com/48295718/113054283-3cac6980-9177-11eb-91bd-9e20906e88bc.png">

**Comment by mmacedom** [comment]
@lucastbelem I adjusted the payment messages. The font size from the screen shot above is the same as in the figma file. I made it a little smaller. The only thing missing on that screen is the checkmark which I cannot get from the figma file. Can you provide it to me?
