### ISSUE TITLE
Sign in issues

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#536]
Liam tried to create a profile, but profile could not be submitted, and he encountered this screen:
<img width="1152" alt="Screen Shot 2020-12-21 at 2 50 56 PM" src="https://user-images.githubusercontent.com/48295718/102823960-e4acdc80-43a9-11eb-876b-40d44d657872.png">

**Comment by GeorgeBellTMH** [comment]
This will be fixed in next release

**Comment by GeorgeBellTMH** [comment]
Please verify

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this issue is resolved, but another occurs. This user now sees a white screen and cannot proceed. As an admin, I also see a blank screen at first login, but upon refreshing, I can get in.

<img width="1436" alt="Screen Shot 2021-01-14 at 10 04 26 PM" src="https://user-images.githubusercontent.com/48295718/104676112-be324680-56b4-11eb-9ddf-0f23a3f0e6d3.png">

**Comment by GeorgeBellTMH** [comment]
Should be fixed.
