### ISSUE TITLE
Curriculum product delivery completion

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#542]
I thought I'd put everything that is still needed for pilot launch early January in one place:

- [x] Remaining resource modules: dev and design
- [x] Episodes and series
- [x] Payments functionality completion
- [ ] Invitations to the platform to specific product (i.e. One Story or Partnerships)
- [x] Ability to hide a product from the "add another product" so users can't pay for partnerships unless they are specifically invited to it
- [x] Ask user if they want to pay March 1, April 1, or May 1. 
- [ ] A contact us field if the options above don't work for you. support@onestorycurriculum.com
- [x] Add One Story logo to JC login flow for those coming from One Story website
- [x] Add text to the first account creation screen for all users

Logo
![OneStory-Logo-RGB (1)](https://user-images.githubusercontent.com/48295718/103044306-0e066d80-454e-11eb-8647-9b8c12c9e7f3.png)

Paragraph for login screen:

You are in the right place to sign up for One Story Curriculum! One Story is excited to partner with Jesus Collective in this tangible way and provide our curriculum through the Jesus Collective platform. Through this platform, you not only access these great discipleship resources for kids and youth in a super easy to use way, but you also get the benefit of having meaningful interaction and engagement with other One Story users to give feedback, share ideas and more.

What is Jesus Collective, you ask?

Jesus Collective is a relational Jesus-centred network that provides a place of belonging, learning and resourcing for like-minded churches and leaders, develops and supports future ready leaders, and equips churches to make more disciples in a post-Christian context. Jesus Collective wants to give greater voice and visibility to this Jesus-centred, third-way movement God is raising up around the world. Isn’t that exciting? Learn more here: jesuscollective.com. Apply for Partnerships (this is a button taking them to the get involved page of jesuscollective.com).

**Comment by GeorgeBellTMH** [comment]
To hide a product make it not visible for the org tier or the individual tier...then include it in the link you send to people (ie in the invite).

**Comment by GeorgeBellTMH** [comment]
To show the One Story copy include productType="OneStory" in the url

**Comment by GeorgeBellTMH** [comment]
@mmacedom I have added the RichText, there is H1->H4 and Body1->Body3

**Comment by GeorgeBellTMH** [comment]
Invites now create a user in the dynamodb table and also in stripe

**Comment by GeorgeBellTMH** [comment]
@lucastbelem Episodes now have YouTube, images are fixed,

**Comment by GeorgeBellTMH** [comment]
@mmacedom styling can be done now on cards for episodes (YouTube etc.)

**Comment by lucastbelem** [comment]
> @mmacedom styling can be done now on cards for episodes (YouTube etc.)

@mmacedom please prioritize this one over the mobile issues.

Thanks!

**Comment by mmacedom** [comment]
how do we set up a youtube video with a card?
[image: Screen Shot 2021-01-12 at 12.11.50 AM.png]

**Comment by GeorgeBellTMH** [comment]
Show all resources
Click show more
Go to this is my test curriculum
Go to kids in the menu
Go to Luke son of god

This is the video page.

**Comment by GeorgeBellTMH** [comment]
@lucastbelem branding is done

**Comment by GeorgeBellTMH** [comment]
To use ?brand=oneStory on the url

**Comment by GeorgeBellTMH** [comment]
?brand=jc or nothing will show just the jc...if you want copy let me know...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH closing this as there are smaller issues with the specific outstanding items.
