### ISSUE TITLE
Message Board Updates [Courses]

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#543]
This issue primarily applies to courses, but the features updates can be applied to all message boards.

**Threaded conversations:**
- [x] Add Reply table to schema
- [x] One-to-many connection: Message to Reply (schema)
- [x] One-to-many (recursive) connection: Reply to Reply (schema)
- [x] Add reply button and client-side logic to handle replies 
- [x] Display conversation threads by indenting replies

Note: the Figma mockups suggest that replies only go three layers deep (i.e. top level message, replies to that message and replies to those replies), but a recursive connection will be used to maintain future flexibility.

**Other updates:**
- [x] Implement infinite scroll
- [x] Load messages incrementally
- [x] Update styling and UI to better match mockups

**Comment by GeorgeBellTMH** [comment]
Sounds good! Can you also make a allowReplies="true|false" so we can disable it in cases where it doesn't make sense to have replies...

**Comment by GeorgeBellTMH** [comment]
Also, I think it might also not be clear in the design, but in some cases we have newest->oldest and some cases oldest->newest and top/bottom message input...

I think it also would be useful if we could have ability to have profileImage="big|small|none" and name="show|hover" and editorTools="show|hide" as there are times/places where we can hide some of that stuff....

**Comment by JonEsparaz** [comment]
Yes, I'll definitely add those props to the component.

**Comment by JonEsparaz** [comment]
Progress report: everything is mostly done - I did run into a couple unexpected issues.

Just testing and cleaning up the UI a bit. PR will be up on Monday by the latest.
