### ISSUE TITLE
Overlapping drop down menu items

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#552]
<img width="1431" alt="Screen Shot 2021-01-07 at 10 58 54 AM" src="https://user-images.githubusercontent.com/48295718/103914179-70777600-50d7-11eb-8ec7-a78d46d03822.png">

**Comment by GeorgeBellTMH** [comment]
This should be fixed.

**Comment by lucastbelem** [comment]
Not fully...
<img width="1434" alt="Screen Shot 2021-01-11 at 9 30 08 AM" src="https://user-images.githubusercontent.com/48295718/104194697-a5453f00-53ef-11eb-85fe-3c48691d83e4.png">
