### ISSUE TITLE
Mobile view bugs

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#556]
Below are some issues I came across on mobile that need fixing:

Too much white space
![Screenshot_20210109-085235_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093619-9c226980-5259-11eb-8924-791cb202b0e8.jpg)
![Screenshot_20210109-085324_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093626-a80e2b80-5259-11eb-8d21-ae17fd1a6a43.jpg)
![Screenshot_20210109-085330_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093634-b52b1a80-5259-11eb-9c30-d70dbf4d48ba.jpg)
![Screenshot_20210109-085324_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093643-c542fa00-5259-11eb-8b73-e52ee3e457ea.jpg)

Overlapping options and headers
![Screenshot_20210109-085146_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093660-e277c880-5259-11eb-8aba-c212c2a05de4.jpg)
![Screenshot_20210109-085151_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093667-ec013080-5259-11eb-8984-d17d52e67dbe.jpg)
![Screenshot_20210109-085201_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093676-f6bbc580-5259-11eb-8be1-a320d87a9927.jpg)
![Screenshot_20210109-085206_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093679-ff140080-5259-11eb-830c-1f2d685d1b58.jpg)
![Screenshot_20210109-085218_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093686-0804d200-525a-11eb-930c-ac83bfa02b46.jpg)

Out of view items
![Screenshot_20210109-085655_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093701-2b2f8180-525a-11eb-86a7-6f8b0acac0bd.jpg)
![Screenshot_20210109-090040_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093707-384c7080-525a-11eb-9d81-40e2ceb1da15.jpg)

Text components overlapping with other components
![Screenshot_20210109-085859_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093718-48fce680-525a-11eb-8698-c96818ce75ab.jpg)
![Screenshot_20210109-085846_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093730-6631b500-525a-11eb-8e01-955e76079890.jpg)

Font on course header too big on mobile
![Screenshot_20210109-085846_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093735-76499480-525a-11eb-99ff-d2c7deebe884.jpg)

**Comment by lucastbelem** [comment]
@mmacedom here is the design for what the "connect with others" should look like, spacing wise: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=1819%3A130890

**Comment by mmacedom** [comment]
@lucastbelem I started fixing these and have most of them fixed and in a PR. Still pending: drop down menus on dashboard, course and profile issues. I'll keep working on this tomorrow night.

**Comment by mmacedom** [comment]
@lucastbelem I just fixed the course home. The dashboard menus are still pending. All of the other screens should be fixed. Can you confirm?

**Comment by GeorgeBellTMH** [comment]
@itbel I think most of this is fixed....can you and @lucastbelem verify...

I think it would be helpful to do another mobile testing pass on login/payment and fix any issues there as well...

**Comment by mmacedom** [comment]
@lucastbelem can you confirm that the changes pushed addressed these issues on your end? Thx

**Comment by lucastbelem** [comment]
@mmacedom almost everything. Here are a couple others:

Role title isn't centred under name in the profile directory screen. But it's fine in the dashboard.

![Screenshot_20210210-220554_Chrome.jpg](https://user-images.githubusercontent.com/48295718/107598678-7be52200-6bec-11eb-8df0-101a3f27fe34.jpg)

Out of screen content - it got much better, but on my Samsung galaxy s8 it's still a bit out of the screen view
![Screenshot_20210210-220442_Chrome.jpg](https://user-images.githubusercontent.com/48295718/107598710-99b28700-6bec-11eb-8a91-5cea3b6d391f.jpg)

**Comment by lucastbelem** [comment]
@mmacedom let's remove the word "receive" from all of those lines. The user, I think, knows that's what it's for.

**Comment by lucastbelem** [comment]
A couple more:

Text overlap on account choice screen:
![Screenshot_20210210-221246_Chrome.jpg](https://user-images.githubusercontent.com/48295718/107599236-e21e7480-6bed-11eb-98bb-0334b3b7a068.jpg)

Can we centre the buttons and remove the "or"? Is it needed? Should the options be 2 buttons or mobile or a checkbox thing?

![Screenshot_20210210-221201_Chrome.jpg](https://user-images.githubusercontent.com/48295718/107599261-fb272580-6bed-11eb-9ed7-0f7d1b55b245.jpg)

![Screenshot_20210210-221308_Chrome.jpg](https://user-images.githubusercontent.com/48295718/107599286-0712e780-6bee-11eb-83c4-68bd4d551f86.jpg)

**Comment by mmacedom** [comment]
@lucastbelem Ok. I pushed some fixes to the profile screen and will keep working through the remaining items tomorrow.

**Comment by mmacedom** [comment]
@lucastbelem I pushed some more changes to fix the sign in/sign up screens. Can you please let me know if that was solved on Android? Thanks

**Comment by mmacedom** [comment]
@lucastbelem I pushed some more changes here. Let me know if the text still overlaps on your phone. Thx
