### ISSUE TITLE
Header on course shouldn't be locked to top on mobile

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#557]
It makes it very difficult to navigate on mobile.
![Screenshot_20210109-085846_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104093772-b9a40300-525a-11eb-855e-1b63e24e943a.jpg)

**Comment by lucastbelem** [comment]
@mmacedom is this is change you can make?

**Comment by lucastbelem** [comment]
@mmacedom as discussed, let's remove that header from mobile for now.

Thanks.

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH I just removed the header from mobile.
