### ISSUE TITLE
Remove map from mobile

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#558]
As per figma design, map should not appear on mobile. It also currently appears out of the screen. Can we please remove the map from mobile?
![Screenshot_20210109-085604_Chrome.jpg](https://user-images.githubusercontent.com/48295718/104094626-0807d080-5260-11eb-8ab6-2f3ae49ad80f.jpg)

**Comment by GeorgeBellTMH** [comment]
Map will now default to off if you are on a screen size of less than 720, it will default on if bigger...toggle is still visible in both mobile and desktop and once set it remembers the setting.
