### ISSUE TITLE
Profile creation cannot be completed

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#562]
User cannot complete profile creation. Additionally, address, email, and phone number are not included in the profile fields.

<img width="1434" alt="Screen Shot 2021-01-11 at 1 08 38 PM" src="https://user-images.githubusercontent.com/48295718/104220978-404d1180-540e-11eb-9e54-fef1d796bca3.png">

Then I pressed "log out" and tried logging back in. This time, I was taken to this blank screen:
<img width="1439" alt="Screen Shot 2021-01-11 at 1 11 46 PM" src="https://user-images.githubusercontent.com/48295718/104221216-9f128b00-540e-11eb-9232-e50aa345617e.png">

Refreshing the page took me back to the profile creation screen.

**Comment by lucastbelem** [comment]
Maybe the issue has to do with the "messages" button, which until you create a profile, doesn't do anything.
<img width="1440" alt="Screen Shot 2021-01-11 at 2 09 19 PM" src="https://user-images.githubusercontent.com/48295718/104226986-accc0e80-5416-11eb-8fc9-cd99ae327657.png">

**Comment by GeorgeBellTMH** [comment]
This is fixed.
