### ISSUE TITLE
Blank screen at first login

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#566]
Similar to previous payment screen issue, but now I get this screen. Refreshing takes me in.
<img width="1439" alt="Screen Shot 2021-01-11 at 7 53 02 PM" src="https://user-images.githubusercontent.com/48295718/104255559-5b884300-5447-11eb-87be-1399c7126f24.png">

**Comment by GeorgeBellTMH** [comment]
fixed

**Comment by lucastbelem** [comment]
This is recurring.

**Comment by GeorgeBellTMH** [comment]
Should be resolved.
