### ISSUE TITLE
Line break in menu

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#571]
@mmacedom I think this needs to be styled still...it's not lining up properly in the menu.
<img width="776" alt="Screen Shot 2021-01-12 at 4 39 09 PM" src="https://user-images.githubusercontent.com/48295718/104377627-ccd1ff80-54f4-11eb-9d67-526f7d4b56e9.png">

**Comment by mmacedom** [comment]
@lucastbelem Are you referring to the indented labels? If so, these are supposed to be indented to indicate that they are sub pages of the label above. Please let me know if this makes sense or if you are referring to something else.

**Comment by GeorgeBellTMH** [comment]
I think he is referring to the horizontal line that can be added (click the plus button and choose break)

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH I have styled it. Can you confirm on your end? Thx
