### ISSUE TITLE
When edit modals get long they're out of view

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#577]
As seen in the attached screenshot, I cannot scroll the modal, so I can't click the button to save the options added.

<img width="1439" alt="Screen Shot 2021-01-14 at 8 52 08 PM" src="https://user-images.githubusercontent.com/48295718/104671053-051b3e80-56ab-11eb-8807-94e559ae3b19.png">

**Comment by mmacedom** [comment]
@lucastbelem it's been fixed.
