### ISSUE TITLE
Forms: Enable tabbing through Form Inputs

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#58]
When creating my profile, I should be able to press "tab" and have the cursor go straight to the next field to be filled. Currently, tabbing takes me to the next non-editable field (the field title).

**Comment by GeorgeBellTMH** [comment]
I looked into this, there are some problems getting it done...we will need to wait for a bit until the library allows for this...

**Comment by GeorgeBellTMH** [comment]
This is working now it seems...
