### ISSUE TITLE
Additional email notifications

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#581]
We need to add email notifications for the following:

- [ ] Threaded replies
- [x] Group/Event owner

As per our discussion, I'm tagging you @JonEsparaz, if you have time in the next few days. There is an extra thing here, so let me know if you have questions or if that's more involved.

**Comment by JonEsparaz** [comment]
@lucastbelem - unassigned myself as classes are starting to pick up quickly and I'm reserving my last bit of time for the TMH work.

**Comment by GeorgeBellTMH** [comment]
Group/Event Owners now automatically join the group as well as own it.

**Comment by GeorgeBellTMH** [comment]
I am delivering this now, please test.

**Comment by lucastbelem** [comment]
Beauty! I'll test it out in the am.
