### ISSUE TITLE
Videos on series page should not auto play

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#582]
Videos on this page are currently auto playing when the user lands on the page. They shouldn't do that.
<img width="1436" alt="Screen Shot 2021-01-14 at 10 38 51 PM" src="https://user-images.githubusercontent.com/48295718/104678505-95608000-56b9-11eb-9620-a8dff3b5f5cc.png">

**Comment by GeorgeBellTMH** [comment]
Fixed
