### ISSUE TITLE
Series page styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#583]
- Text appears too large;
- video numbers are misaligned;
- iFrame is too small;

**Comment by mmacedom** [comment]
@lucastbelem I adjusted the iframe as well as the number. Please let me know if I missed something. 

As far as the font sizes, we have 3 different paragraph sizes according to the mock ups (27px - body 1, 18px - body 2, 16px - body 3). The paragraph used on the series seems to be 27px (body 1). Is that paragraph font you are referring to? Let me know and I can make things a little smaller.

**Comment by lucastbelem** [comment]
Awesome thx.

Yep, that's the one. If you could reduce it a bit I think it'd be great.

**Comment by GeorgeBellTMH** [comment]
Closing...please create separate tickets for remaining items.
