### ISSUE TITLE
Series page styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#584]
Series page is looking great, @mmacedom! Just a couple more things:

- [x] We need to style the 2 dropdown buttons to match the Figma mockup found here: https://www.figma.com/file/IiGPCZjFKi8avWdc6CoU7Z/One-Story-JC-Platform?node-id=219%3A2390
- [x] I think the text still might be too big. The Figma mock up says it should be 16px (line height 24px). If I'm looking at things correctly, it's currently set to 22px. 
- [x] Same applies to the resource name plus the name shouldn't be bolded (i.e. kids - year 1). I have no idea if I'm doing this right, but I did the console, inspect thing to see how to check this out. Here is what I think it should look more like (but let me know if I'm way off). 
<img width="1437" alt="Screen Shot 2021-01-15 at 9 03 22 AM" src="https://user-images.githubusercontent.com/48295718/104736254-ad172300-5710-11eb-9810-28febbcaa5db.png">

**Comment by mmacedom** [comment]
@lucastbelem In terms of the fonts, I did take a look at the sizes and everything has been set up according to the mock ups. When we create the RichText components, we will have to select the appropriate heading or paragraph type on the dropdown menu. 

In essence, there are 4 different heading sizes and 3 different body sizes: 
**The headings are:** 
- RichTextH1: font size: 36px, line height: 43px.(found on main heading on the "Overview" page on the mock up)
- RichTextH2: font size 24px, line height: 34px (found on heading - "Early Years" and "Kids" on the "Overview" screen)
- RichTextH3: font size 14px, line height: 21px (found on heading - "Early Years" above the first set of cards on the "Overview" screen)
- RichTextH4: font size 12px, line height: 18px (found on red heading inside the cards "Early Years - current series")

**The paragraphs are:** 
- RichTextBody1: font size 22px, line height 38px (found on "first large paragraph on the "Kids" screen. The actual size was 27px)
- RichTextBody2: font size 18px, line height: 27px (found on paragraph under the main heading on the "Overview" page on the mock up)
- RichTextBody3: font size 16px, line height: 24px (found inside the cards) 

<img width="346" alt="Screen Shot 2021-01-17 at 10 20 41 PM" src="https://user-images.githubusercontent.com/24467324/104868813-71e44200-5912-11eb-8912-4b3f145dec50.png">
<img width="424" alt="Screen Shot 2021-01-17 at 10 35 48 PM" src="https://user-images.githubusercontent.com/24467324/104869602-70b41480-5914-11eb-960c-cf21c831a185.png">
<img width="436" alt="Screen Shot 2021-01-17 at 10 35 58 PM" src="https://user-images.githubusercontent.com/24467324/104869603-71e54180-5914-11eb-80f6-2e7a0a4cc6b5.png">
<img width="429" alt="Screen Shot 2021-01-17 at 10 36 07 PM" src="https://user-images.githubusercontent.com/24467324/104869606-727dd800-5914-11eb-82ac-b8173548bcda.png">

**Comment by mmacedom** [comment]
@lucastbelem As far as the resource name, are you referring to the large name in the white container in the Hero? If so, the size of it on the mock up says font size 54px, line height 54px and font weight 600 which is in between normal and bold. Since we don't have that weight (semi bold), we either have to use bold or normal. 

Please let me know if you'd like me to modify any of the font sizes, line heights, font weight.

**Comment by lucastbelem** [comment]
@mmacedom this is super helpful. As per our discussion earlier today, the page I was referring to for which font size elements need to be modified is the series page. This is the same page with the iFrames which can be found by clicking on "kids" in the menu and then clicking on the first series in the list of series.

**Comment by lucastbelem** [comment]
@mmacedom I just heard back from our designer on this project. He asked me to apologize. He said there are a couple of mistakes and a couple of things that just need clarification from him. So he's adding a Type artboard to the project so you can see what each size is supposed to be.

**Comment by GeorgeBellTMH** [comment]
Is this fixed?

**Comment by lucastbelem** [comment]
For now...We'll have to connect further about fonts, but we're de-prioritizing this for now.

**Comment by lucastbelem** [comment]
Closing this and opening a font specific issue.
