### ISSUE TITLE
Dashboard Dropdown menu on mobile

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#588]
Each category in the dashboard includes items like "create", "show all", "my events/groups/etc", "previous event". We need the horizontal component for this dashboard menu to be disabled and a new dropdown style menu component to be made and enabled for mobile.

**Comment by GeorgeBellTMH** [comment]
@itbel so here is some more details on this one...basically when the home screen gets below a certain horizontal width the homepage becomes cluttered...we wanted all the group action items to get combined into one dropdown with a "...". I think some of the buttons could then have a check to show if they are on/off...or the icon/text could change depending on what the state is - if it makes sense...also this needs to work on all the "show all" pages...

**Comment by lucastbelem** [comment]
@itbel also you won't find this in the mockups, so in terms of UI, just create the dropdown functionally, and @mmacedom can style it for us.
