### ISSUE TITLE
Cannot add series to resource - BETA

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#593]
Nothing happens when I click "add series" to a resource. 

<img width="1440" alt="Screen Shot 2021-01-22 at 6 57 06 PM" src="https://user-images.githubusercontent.com/48295718/105561048-b3df0080-5ce3-11eb-8a22-544f8e517f59.png">

**Comment by lucastbelem** [comment]
Update: The series do appear...but randomly. I left the page, and came back...then I left the resource and came back. No lock. Then I added a grid to another page and used the resource in question for the grid. Then I noticed that there were series' attached to them. When I went back to the "configure resource" page, the series were all there as "new title".

**Comment by GeorgeBellTMH** [comment]
Basically right now when you add/remove or edit anything on this page you have to fully refresh to see the updated content....working on a fix...

**Comment by GeorgeBellTMH** [comment]
This should be working better now...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I'm being able to do it as long as refresh.
