### ISSUE TITLE
Map icon bug

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#594]
There is a weird bug with the map icons.

Profiles and orgs are displayed by default. No orgs exist, but the icon that displays by default is the org icon. If I toggle orgs off, the icon changes. 

if I click on the org icon, it display a user profile. 

I think that the map is set up in such a way that it is displaying user profiles, but depending on what toggle you have on, the profiles are displayed with the orgs or profile icon, even though user profiles should only have the blue profile icons.

**Comment by mmacedom** [comment]
@lucastbelem I made a few changes to it but the logic is still not quite right when 2 or more toggles are selected. I will have to consult George on this.

**Comment by itbel** [comment]
I'm unable to get the map to work on localhost. I get the following error:
`Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: http://dev.localhost:19006/app/home`
@GeorgeBellTMH 

Any thoughts?

**Comment by itbel** [comment]
I got it. Was using dev. instead of just localhost
