### ISSUE TITLE
View profile button on map popup is wrong

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#595]
<img width="1393" alt="Screen Shot 2021-01-22 at 7 03 15 PM" src="https://user-images.githubusercontent.com/48295718/105561376-8e9ec200-5ce4-11eb-9339-5f8b1927e64e.png">

**Comment by mmacedom** [comment]
Fixed

**Comment by lucastbelem** [comment]
@mmacedom can you make this more closely resemble the mock ups? "View profile" should be a link rather than a button, and it should appear beside the "start conversation" button (though maybe that doesn't work for smaller screens?)

This might make the card a little bit wider, but less long.
<img width="515" alt="Screen Shot 2021-02-23 at 8 30 51 PM" src="https://user-images.githubusercontent.com/48295718/108931739-29f1c280-7616-11eb-960a-c8462eae02ac.png">

**Comment by mmacedom** [comment]
@lucastbelem that's so bizarre that it went wonky again. I just pushed a fix for this.
