### ISSUE TITLE
Since beta update, users face a blank screen

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#597]
The url ends in /payment3. As an admin, I was able to get around this by logging out and logging back in, but this wouldn't be ideal for other users as they may not know to do that. 

As a non-admin user, the url ends in /payment1. Payment page flashes quickly and then the user faces blank screen and can't get in.

**Comment by GeorgeBellTMH** [comment]
Can you confirm this is ok?

**Comment by lucastbelem** [comment]
Did you publish it? I'll test in a couple hours. It was definitely fixed in
dev.

**Comment by GeorgeBellTMH** [comment]
Yup everything from today is published in beta now, dev is a bit behind....
