### ISSUE TITLE
Series page buttons design

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#598]
@mmacedom buttons seem to not be wide enough to accommodate some of the text needed. Here is the mock up:

<img width="384" alt="Screen Shot 2021-01-22 at 7 27 07 PM" src="https://user-images.githubusercontent.com/48295718/105562389-f4407d80-5ce7-11eb-9401-48f148ec9505.png">

Here is what it currently looks like on the site:
<img width="1434" alt="Screen Shot 2021-01-22 at 7 28 13 PM" src="https://user-images.githubusercontent.com/48295718/105562399-00c4d600-5ce8-11eb-86e5-7e872d030f96.png">

**Comment by mmacedom** [comment]
@lucastbelem I adjusted the width of the button in the series page. I couldn't find the exact page above with the drop items but it the fix should address the issue. Please let me know if it's adjusted on your end.
