### ISSUE TITLE
Parts of the resource are randomly not available

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#599]
This is me clicking "Year 1" under kids. 

<img width="1440" alt="Screen Shot 2021-01-22 at 7 29 45 PM" src="https://user-images.githubusercontent.com/48295718/105562478-441f4480-5ce8-11eb-8808-b8726b8e1071.png">

**Comment by GeorgeBellTMH** [comment]
I believe you might need to set the description for each item...

**Comment by GeorgeBellTMH** [comment]
This happened because there was an object that was added as something else, then changed to a richtext...deleting this menu item and recreating should resolve it, and it shouldn't happen again in the future.
