### ISSUE TITLE
Messaging: Direct Message viewing

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#60]
As per design found here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=415%3A13 there should be a "Messages" link on profiles so the person can find their personal/direct messages.

**Comment by JonEsparaz** [comment]
@lucastbelem where is this supposed to go? The profile page is basically the profile editor atm.

**Comment by GeorgeBellTMH** [comment]
I added the button yesterday. You can turn it on in constants. Mateus is working on styling it.

I’m not sure at this point it’s worth doing a read only version of your own profile...it should just always be editable.

Sent from my iPhone

On Jun 2, 2020, at 5:34 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@lucastbelem<https://github.com/lucastbelem> where is this supposed to go? The profile page is basically the profile editor atm.

**Comment by lucastbelem** [comment]
Agreed. Let's leave own profile as editable only.
