### ISSUE TITLE
Resource in product id

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#601]
Do we have to change the default product id for resources like we do for courses? If so, that isn't working currently. I can't update a product id in the platform.

<img width="1440" alt="Screen Shot 2021-01-23 at 12 05 51 PM" src="https://user-images.githubusercontent.com/48295718/105608870-8a6db580-5d73-11eb-9777-9489cc802a5d.png">

**Comment by GeorgeBellTMH** [comment]
I'm not sure what you mean?
