### ISSUE TITLE
Something wonky with resource menu navigation

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#604]
Tabbed menu items aren't appearing at first, but appear when I press the first age group. Maybe a user error and I need to re-do the menu items? But if so, odd that all of the tabbed items don't appear when in the first overview item.
<img width="1440" alt="Screen Shot 2021-01-23 at 12 22 53 PM" src="https://user-images.githubusercontent.com/48295718/105609230-ecc7b580-5d75-11eb-805c-32ce59de717a.png">
<img width="1440" alt="Screen Shot 2021-01-23 at 12 22 46 PM" src="https://user-images.githubusercontent.com/48295718/105609231-ed604c00-5d75-11eb-869a-352a39805d3b.png">

**Comment by GeorgeBellTMH** [comment]
This is fixed.
