### ISSUE TITLE
Clicking on course assignment not working

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#605]
When I click on an assignment in a course, I see a blank screen. Here are the errors. @JonEsparaz I'm tagging you because I see something in the error box about direct message rooms, so tagging you just in case it has something to do with your work from the holidays. 

<img width="1437" alt="Screen Shot 2021-01-23 at 12 29 35 PM" src="https://user-images.githubusercontent.com/48295718/105609373-e8e86300-5d76-11eb-8ac3-351193ec5696.png">

**Comment by lucastbelem** [comment]
Hey @JonEsparaz! Wanted to check and see if you think you'll have time this week to tackle this one?

**Comment by JonEsparaz** [comment]
@lucastbelem done. Turned out to be a trivial mistake and fix.

**Comment by lucastbelem** [comment]
Thanks man!!!
