### ISSUE TITLE
Auto Card doesn't load content when "none" episode is selected

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#614]
When I select the card component and select the auto version, if I select a series, but don't select an episode, the series content doesn't load. 

<img width="1436" alt="Screen Shot 2021-01-25 at 4 42 50 PM" src="https://user-images.githubusercontent.com/48295718/105769810-61445500-5f2c-11eb-8a9f-05f3b5c8813d.png">

**Comment by GeorgeBellTMH** [comment]
Fixed
