### ISSUE TITLE
Updated font styles

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#615]
As discussed on our call, we need updated font styles as per the design guide found here: https://www.figma.com/file/IiGPCZjFKi8avWdc6CoU7Z/One-Story-JC-Platform?node-id=510%3A63

- [x] Update fonts
- [x] Style pages

**Comment by GeorgeBellTMH** [comment]
I have added the fields to the drop down...you should just have to add them to the stylesheet.

**Comment by mmacedom** [comment]
@lucastbelem can you clarify what "style pages" entail? Thanks

**Comment by mmacedom** [comment]
@lucastbelem heads up, there is no style set for H2Small and H5Small despite they appear on the drop down.
