### ISSUE TITLE
Maps: Finding profiles on map

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#62]
When I look at the map on the dashboard, I only see 2 points: A which is pinned on Toronto, and B which is pinned on George (which actually shows George in a different location that his). I should be able to see all profiles created.

**Comment by GeorgeBellTMH** [comment]
Second bit is v2

**Comment by lucastbelem** [comment]
Ok. Moving second bit to a different issue.

**Comment by GeorgeBellTMH** [comment]
This is working, it's just that everybody is over in Asia....zoom out...
