### ISSUE TITLE
Payments: price is sometimes not correct

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#623]
The price is sometimes not correct if you enter values quickly. We need to invalidate old PreviewInvoice queries if there is a new query.

**Comment by itbel** [comment]
I have hit a wall with this issue. I will circle back again in a day or two.

**Comment by GeorgeBellTMH** [comment]
Hey, so I have another idea on how to do this...let's make a queue of the promises...and we can just pop them off the queue as they finish...that should get us the most recently successful result...

**Comment by GeorgeBellTMH** [comment]
(we can ignore all items except the last Promise in the queue, and if it's not complete then show the "loading" screen...

**Comment by itbel** [comment]
Hey George, did you get a chance to go over my proposed solution in #660 ? I implemented a counter that increments every time createInvoice() is called. When the promise resolves, if the counter is greater than 1 it will disregard it, and decrement the counter. setState only occurs when there is only 1 left. Thoughts?

**Comment by GeorgeBellTMH** [comment]
Promises don’t resolve in order…so I think they need to be in a queue based on when they were called…only the one created on the last button click should ever show up on screen…

In this case:
(counter=0)
Click 1 (counter=1)
Click 2 (counter=2)

Promise 2 resolves (counter=1) - Ignored
Promise 1 resolves (counter=0) - Now we are showing Promise 1 but we should be showing promise 2


In the case of a queue

Click 1, Click 2, Click 3, Click 4

Only ever show Promise 4 (we can ignore promise 1-3)

If something is added to the queue then we can ignore 4 and 5 is the only one that matters...

G

**Comment by itbel** [comment]
Thank you. I will work with this
