### ISSUE TITLE
Payments: Show errors/warnings

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#624]
The stripe fields on the payment screen will return useful warnings, as will the lamda's if there are failures.

We should show the user these warnings in a red text near the button.

**Comment by lucastbelem** [comment]
@itbel I meant to ask for this earlier today and completely forgot...sorry!

Any chance you can add a line of text to the screen that the user sees with the spinner after they press "process payment"? The process takes a while (maybe 30-60 seconds) and I want to make sure the user knows things are working in the background. Something like:

"Please wait while we process your payment. This may takes several seconds."

**Comment by itbel** [comment]
> @itbel I meant to ask for this earlier today and completely forgot...sorry!
> 
> Any chance you can add a line of text to the screen that the user sees with the spinner after they press "process payment"? The process takes a while (maybe 30-60 seconds) and I want to make sure the user knows things are working in the background. Something like:
> 
> "Please wait while we process your payment. This may takes several seconds."

Will do.

**Comment by GeorgeBellTMH** [comment]
I believe this is working now...

**Comment by itbel** [comment]
There are still some errors that are not caught/ displayed. A valid credit card number getting declined does not redirect the user back to the payments page. Page hangs on "Processing payment". I'm working on this
