### ISSUE TITLE
Mobile view login screen

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#625]
When I open my keyboard on the login screen, things look wonky.
![Screenshot_20210127-063433_Chrome.jpg](https://user-images.githubusercontent.com/48295718/105985786-f862f700-6069-11eb-9441-9bf211ef97b6.jpg)

**Comment by mmacedom** [comment]
@lucastbelem this has been fixed and pushed. 
<img width="284" alt="Screen Shot 2021-01-31 at 10 32 43 PM" src="https://user-images.githubusercontent.com/24467324/106411865-44b88900-6414-11eb-8ab3-61c68061a65c.png">
