### ISSUE TITLE
Threaded replies email notifications

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#626]
We need to add email notifications to threaded replies in all message boards

**Comment by GeorgeBellTMH** [comment]
This one almost already existed, but then I spent a couple hours fighting with AWS and it wouldn't let me deploy with this configured....it was either the replies, or the messages but not both....I am going to play around some more with this...

**Comment by GeorgeBellTMH** [comment]
Done!

**Comment by lucastbelem** [comment]
You're my favourite!!

On dev or Beta?

**Comment by lucastbelem** [comment]
Just so I know where to test.

**Comment by GeorgeBellTMH** [comment]
Both.
