### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#63]
We need to make use of the amplify and expo notification functionality to alert when there are new:

-DirectMessages
-Messages in groups we are members of
-Jesus Collective CRM
-New Resources in resources we follow

Notifications should go out on the appropriate channel (if they are mobile or web or email) and be throttled appropriately.

Notifications should be able to link directly to the related item.

**Comment by GeorgeBellTMH** [comment]
If user is logged in this should be notified in app via a toast item or some other mechanism.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I'm closing this for #503.
