### ISSUE TITLE
"Reply" button style

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#630]
@mmacedom can you make some changes to the "reply" button in the message board?

Currently, a message in the message board looks like this (you'll see "reply" circled):
<img width="1440" alt="Screen Shot 2021-01-27 at 7 56 22 PM" src="https://user-images.githubusercontent.com/48295718/106074567-16684000-60da-11eb-90ed-fb25dd3ff793.png">

Can we make it look more like this (i.e. red "comment" button, but still say "reply"):
<img width="670" alt="Screen Shot 2021-01-27 at 8 02 09 PM" src="https://user-images.githubusercontent.com/48295718/106074848-92628800-60da-11eb-904e-7c5eaa6640c5.png">

If possible, can you put the "reply" button in the message card itself, to match the screenshot above more closely? I guess we would need to move the date/time, but I'd ok to move it under the person's title if you agree that it would make sense.

**Comment by lucastbelem** [comment]
@mmacedom In the mini-message board, it's already arranged that way - the date/time is already under the profile.

**Comment by mmacedom** [comment]
@lucastbelem This has been fixed
