### ISSUE TITLE
Map pop design changes

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#632]
@mmacedom can you change the "View Profile" button to a red link similar to the "Show All" link in the dashboard? Also, can you make it fit beside the "start conversation" button rather than below, as per design. 

Here is what it looks like now:
<img width="674" alt="Screen Shot 2021-01-27 at 9 34 01 PM" src="https://user-images.githubusercontent.com/48295718/106081851-a1036c00-60e7-11eb-9de6-59a1f167ab63.png">

Here is the mock up:
<img width="607" alt="Screen Shot 2021-01-27 at 9 36 07 PM" src="https://user-images.githubusercontent.com/48295718/106081883-afea1e80-60e7-11eb-9010-cfcea74f1f93.png">

**Comment by mmacedom** [comment]
@lucastbelem this has been fixed
