### ISSUE TITLE
Resources: Fade in images only after they have loaded

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#635]
Currently the fade starts before image loading is complete

**Comment by GeorgeBellTMH** [comment]
This is for all images being loaded throughout the platform...but focus on the resource images (header and card) for now.

**Comment by mmacedom** [comment]
@GeorgeBellTMH I adjusted the fade length. Let me know if this is better.

**Comment by GeorgeBellTMH** [comment]
I don't see this fix...

**Comment by GeorgeBellTMH** [comment]
But likely you need to change when the trigger happens as well...it shouldn't start until the image is fully loaded...

**Comment by mmacedom** [comment]
@GeorgeBellTMH by mistake, I didn't push this change that's why you don't see it. My apologies. I am pushing it up now. I am changing the fade delay on the image.

**Comment by mmacedom** [comment]
@GeorgeBellTMH Let me know if this works for you

**Comment by GeorgeBellTMH** [comment]
I reverted this change...you should use the image's unload event to trigger the animation instead of the view's onlayout event...a

**Comment by mmacedom** [comment]
@GeorgeBellTMH done. the trigger has been changed to onLoad on the image and I also modified the duration of it.
