### ISSUE TITLE
Users still getting blank screens

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#639]
An existing admin user (Zulema) tried accessing the platform via firefox which remembers they are logged in and was faced with a blank screen. She is able to login via Chrome. Here is the screenshot of what is happening:
![image (2)](https://user-images.githubusercontent.com/48295718/106218773-fef68900-61a5-11eb-8e2b-d7fd28adb03e.png)

**Comment by GeorgeBellTMH** [comment]
More data is being collected, hopefully we can figure out why this happens...
