### ISSUE TITLE
Invited user getting wrong screen

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#640]
I invited a user to beta and when the user set up their account, and then verified it, rather than going straight to the payment screen, he was taken to the "your payment was successful screen". After several seconds, the page updated to the payment screen. 

The user was lucastbelem@gmail.com which previously existed on the platform, but I deleted it to try again. Is it possible that this is a cache issue because the user already existed before?

**Comment by GeorgeBellTMH** [comment]
yes. ensure you shut browser after deleting users.
