### ISSUE TITLE
Something seems to have broken in the payment UI

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#643]
I'm guessing this won't be an issue once Igor's payment improvements are merged, but thought I'd mention it here:

<img width="1435" alt="Screen Shot 2021-01-29 at 9 16 05 AM" src="https://user-images.githubusercontent.com/48295718/106285777-e07aa700-6212-11eb-89a8-ef634ad43b5b.png">

**Comment by itbel** [comment]
It will be fixed with PR #629

**Comment by lucastbelem** [comment]
Another UI thing I noticed:
<img width="1436" alt="Screen Shot 2021-01-29 at 9 51 47 AM" src="https://user-images.githubusercontent.com/48295718/106289753-a8299780-6217-11eb-8e87-d2d0800f0620.png">

**Comment by lucastbelem** [comment]
@itbel When users sees the confirmation screen, and press "continue to profile" the platform takes a long time to take the user in. Can we please add a spinner on that page for now?

I actually have to press "continue to profile" twice to make it work...I don't know if there is an issue or just takes too long.

**Comment by itbel** [comment]
Ok! I'm looking into it.

**Comment by GeorgeBellTMH** [comment]
I think there might be a way to get rid of the screen with the continue to your profile button. 

once this.state.processing changes to complete, we repetitively run updateGroups() with a one second delay...then check if the user is a member of subscriptionValid...then if they are run recheckUserState()...

If it doesn’t happen after 2 minutes we can put a “please try later, or contact support” screen.
