### ISSUE TITLE
Mobile Screen bugs

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#646]
When creating the account, this is what the screen where the user is asked whether they are an individual or organization looks like:
![Screenshot_20210129-142058_Chrome](https://user-images.githubusercontent.com/48295718/106319542-978d1780-623f-11eb-9c52-a6684d999574.jpg)

On the landing page, if I click on the email or password fields to trigger my mobile keyboard, something funny happens with the "create account" button.
![Screenshot_20210127-063433_Chrome](https://user-images.githubusercontent.com/48295718/106319543-9825ae00-623f-11eb-9764-625218718b43.jpg)

After the user performs the payment on mobile, the button appears for them to proceed (payment successful) but nothing happens. Then when the user refreshes, this blank screen appears. Also, text on the header looks jumbled.
![Screenshot_20210129-142553_Chrome](https://user-images.githubusercontent.com/48295718/106319544-9956db00-623f-11eb-8759-6b1134fc953c.jpg)

**Comment by mmacedom** [comment]
@lucastbelem I pushed a number of changes to these components. Please let me know how it looks on your Android. Thx

**Comment by mmacedom** [comment]
@GeorgeBellTMH @lucastbelem The back button (in the "sign up - individual/org" is not working on mobile. Not sure if you guys already have that noted but I thought I'd bring it up.

**Comment by lucastbelem** [comment]
Thanks for finding that. I didn't know about it, but it's listed now :) let's close this issue and I'll add what's outstanding from it to the other mobile bugs issue.
