### ISSUE TITLE
Updated onestory brand url content

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#648]
Below is the updated paragraph for the one story branded url content:

You are in the right place to sign up for One Story Curriculum! One Story is excited to partner with Jesus Collective in this tangible way and provide our curriculum through Jesus Collective. Through this platform, you not only access these great discipleship resources for kids and youth in a super easy to use way, but you also have the benefit of meaningful interaction and engagement with other One Story users to give feedback, share ideas and more. Welcome!

**Comment by GeorgeBellTMH** [comment]
I have updated this on the signing page...let me know if it should also be changed on the billing page...(there is more there, with links...let me know if I should keep the links etc.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I'm not sure I follow. 

The brand doesn't carry through, so we probably should make sure it does so the user still sees the One Story logo. I see the logo if I manually enter ?brand=oneStory in the billing page though.

What more is there on that page? I don't think we need other paragraphs on it...just the logo visibility. On that note, could you reduce the thickness of the + sign between the logos?
