### ISSUE TITLE
Pricing summary works in a confusing way

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#650]
The price works like this: 

Tier 1: $55/kid
Tier 2: $575 flat
Tier 3: $775 flat
Every other tier is flat

The total is correct, but it displays twice for each age group. Once at $0 and once at the correct price. I think the reason for this is that every tier has 2 prices in stripe: a per unit price and a flat price. But we use one or the other. Can we make it so that the $0 ones don't show up?

<img width="1440" alt="Screen Shot 2021-01-29 at 9 40 28 PM" src="https://user-images.githubusercontent.com/48295718/106345019-2ff4bd80-627b-11eb-9003-775d932ec589.png">

**Comment by GeorgeBellTMH** [comment]
This is what is going to show on their receipt/bill in stripe...so...I think it wouldn't be good to show them something different than what will be on their bill...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH here is the invoice in Stripe...it doesn't show the duplicates with $0s. I'd love to get rid of those in the payment page.

[Invoice-4E827CB8-0001.pdf](https://github.com/jesus-collective/mobile/files/5898056/Invoice-4E827CB8-0001.pdf)

**Comment by GeorgeBellTMH** [comment]
I'm filtering anything that =0 

Publishing now...
