### ISSUE TITLE
Profile Page Billing Enhancements

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#652]
- [X] Billing section in your profile
- [x] Ability to see invoices
- [ ] Ability to cancel subscription
- [ ] When subscription is cancelled remove permissions
- [ ] Ability to change credit card
- [ ] Ability to update subscription numbers
- [ ] If user deletes themselves, stop billing them!

**Comment by GeorgeBellTMH** [comment]
I have mocked this page up in the profile section and added a note that these features are coming soon, but for any billing concerns to contact Jesus Collective directly.

**Comment by GeorgeBellTMH** [comment]
cc: @lucastbelem I'm just publishing the invoices list...it's at: profile->Billing

**Comment by GeorgeBellTMH** [comment]
It needs some design/layout work

**Comment by lucastbelem** [comment]
Beauty!

**Comment by lucastbelem** [comment]
@itbel @mmacedom if either of you is working today and could tackle this one, that'd be great :)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I'm closing this because what's left here is probably multiple issues.
