### ISSUE TITLE
Webhook sending "wrong" information to AWS

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#656]
I tested signing up for 2 out of the 3 age groups, but when I checked AWS, the user received all 3 age category groups.

**Comment by lucastbelem** [comment]
So I don't think it's that the webhook sent the wrong info, but rather than Stripe is receiving that 0 kids item as a subscription to that group.
<img width="1114" alt="Screen Shot 2021-01-31 at 8 22 38 AM" src="https://user-images.githubusercontent.com/48295718/106385290-95d96600-639d-11eb-8034-8290e6a8becb.png">

**Comment by GeorgeBellTMH** [comment]
Fixed in the next release
