### ISSUE TITLE
Resources: Ability to add/delete/update new resource episode and resource series

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#66]
Series and Episodes should be able to be created and all fields editable
- [x] add resource/series/episode code
- [x] update resource/series/episode code
- [x] delete resource/series/episode code
- [ ] reorder resource/series/episode code
- [x] add resource /series/episode ui
- [x] update text fields /series/episode ui
- [ ] update link fields /series/episode ui
- [x] delete resource /series/episode ui
- [ ] re-order resource /series/episode ui

**Comment by lucastbelem** [comment]
@GeorgeBellTMH @JonEsparaz A decision was confirmed today that Resources cannot be created by anyone except for the JC admin team.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH could you please give me the ability to make changes to kids and youth curriculum? I need to update info on the page (i.e. titles, descriptions, etc.)
