### ISSUE TITLE
Font size of series page

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#662]
On series page (the one where text is added not on the page, but on the resource, the font sizes are off:

Title is correct, but breadcrum is set to 36px. Should be 16px.
Series description is set to 27px. Should be 18px.
<img width="1412" alt="Screen Shot 2021-01-31 at 9 09 26 PM" src="https://user-images.githubusercontent.com/48295718/106406862-a246d880-6408-11eb-8118-8b391df84acb.png">

**Comment by mmacedom** [comment]
@lucastbelem this has been fixed and pushed
