### ISSUE TITLE
BETA: User never left this screen and webhook didn't go through

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#663]
I ran a real transaction on beta, and checked Stripe. User received the subscription as planned, with trial and everything. However, no webhooks were fired and user was faced with this screen and it never moved them forward to their profile:

<img width="1394" alt="Screen Shot 2021-01-31 at 9 17 01 PM" src="https://user-images.githubusercontent.com/48295718/106407451-10d86600-640a-11eb-9b34-15bad3bf78c9.png">

This screen didn't exist before. User would press "proceed to profile" and spinner would run until their profile was ready for them. I'm assuming this is an error handling screen? If so, it makes sense that the user couldn't get through as no webhooks were fired and therefore no groups were added.

**Comment by lucastbelem** [comment]
When I manually added subscriptionValid to the user via AWS, user went through to profile creation.

**Comment by GeorgeBellTMH** [comment]
Resolved...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH is this resolved in beta? I'd like to test again, but they're real transactions, so I'm trying to keep them to a minimum.

**Comment by GeorgeBellTMH** [comment]
Yes…the webhook wasn’t setup...
