### ISSUE TITLE
Better way to handle inaccessible resource 

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#665]
If a user does not have a group permission for an age group, the age group doesn't appear in their resource menu. This behaviour is expected.

On the overview page of the resource, we display a summary of all age groups, showing current and upcoming series for age groups the user is not permitted to access. This behaviour is expected.

However, if the user clicks on a resource they do not have permission to see (i.e. user only has subscriptionkykids, but clicks on a youth series) the browser refreshes (because the url starts from beta.jesuscollective.com) and then reloads the curriculum. We successfully keep the user from accessing the resource.

Can we make it so that if the user clicks on such a resource, they are prompted with a modal (as designed in Figma) with text that says they have not purchased that age group. But they are welcome to do so. And then include a button "buy this age group" which takes them through a payment process to purchase that product?

Alternatively (and temporarily) could we make a modal popup with text that tells the user they do not have access to that resource and if they wish to purchase it, to contact us? Just to provide user with some kind of feedback as to why they can't access the resource.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH alternatively, I could at least for now create multiple overview pages and have them link to resources/series that have previous with different text, but no download buttons.

Thoughts?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I just don't know if creating multiple overviews would cause a navigation problem?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH actually, my suggestion would not work as the user who purchases all 3 products will end up seeing 3 overview pages.

**Comment by lucastbelem** [comment]
2 more ideas:

1. Modify our plan for the overview page to not include series links (temporary until more permanent solution). Or;
2. Keep overview page as is, but series as a dummy copy without download buttons and a note for the user to access the real resource in the age specific page. 

I'm leaning more towards option 1 so as to not confuse the user.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH latest updates we discussed yesterday:

- For now, we'll leave things as is. Overview will contain resources user does not have subscription for as a marketing strategy. 
- By February 15th, we need a solution whereby the user can click that resource, but not be able to download items and a modal or extra message that says something like "as you have not purchased this age group, this page is a preview of this resource. If you are interested in purchasing this age group, please contact us at ....".
- Longer term solution: same as above, but give user ability to buy a new subscription for that product in that modal (or it takes them to the payment screen with the age group they already own blocked out so they can't buy it again.

**Comment by lucastbelem** [comment]
@JonEsparaz if we could implement option 2 for now, that would move us a long way on this.

**Comment by JonEsparaz** [comment]
@lucastbelem please let me know what the modal should say.

**Comment by lucastbelem** [comment]
"You haven't subscribed to this age group yet. If you'd like to, please reach out at support@onestorycurriculum.com. In the meantime, feel free to look around and check out this resource."
