### ISSUE TITLE
Bypass dashboard possibly not working

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#667]
I have tried logging out, clearing cache, closing browser before signing in with the appropriate account and the user does not seem to bypass the dashboard.

**Comment by GeorgeBellTMH** [comment]
Which user?

**Comment by lucastbelem** [comment]
lucastbelem@gmail.com

**Comment by GeorgeBellTMH** [comment]
User is only in verifiedUser group…so will hit the homepage (but shouldn’t be able to because they don’t have a subscription)….have you modified it since this was tested?

G

**Comment by lucastbelem** [comment]
Yes. I had the user set to subscriptionValid and kids manually to test
this. Then reverted back. I'll test again and let you know.

**Comment by lucastbelem** [comment]
Bypass is working now...must've been user error on my part.
