### ISSUE TITLE
Changes to "preparing your account copy"

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#669]
@GeorgeBellTMH after the user pays and clicks proceed to profile, they are faced with this screen while the webhook works in the background. But I'm guessing you wrote this copy in case there is trouble and the user never gets redirected in. For example, yesterday, when the webhooks weren't firing, this screen was helpful. Today, they were firing, but they take a few seconds. Is it possible to add a spinner to that page, but in a such a way that it only shows if it's actually working. If it's not working, then it doesn't show the spinner? I just want to make sure users don't walk away right away when they see that page. Maybe it's a matter of changing the language too...something like: "Please wait a few moments while we set up your account." The problem with this one is that it doesn't address users for whom the webhook just isn't working. Thoughts?

<img width="1382" alt="106415354-e47a1500-641c-11eb-9768-a0b5f63b7233" src="https://user-images.githubusercontent.com/48295718/106467497-b9b6ad80-646a-11eb-803b-67ff60dcbd5f.png">

**Comment by lucastbelem** [comment]
@mmacedom please update copy on this page to: "Please wait a moment while we set up your account."

**Comment by mmacedom** [comment]
@lucastbelem fixed
