### ISSUE TITLE
"Need Help" feature

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#681]
What would it take to implement this:

Design can be found here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=662%3A11162

- [ ] We need to add a get help function so that users can easily and quickly get help on the platform. 
- [ ] Icon should appear on every page throughout the platform (though the priority is to place it on the One Story Curriculum page).
- [ ] Clicking on the icon, for now, should trigger some kind of modal that allows them to message a pre-entered email address and it should send from the user's email address on file
- [ ] Once the message is sent, user should get on-screen confirmation that message is sent with some copy (i.e. thanks for your message. We'll get back to you within a day." and provide the user with a button that says "return to your...curriculum/resource/platform" (don't know the best word, but you get the idea). 

@itbel @GeorgeBellTMH doable? How complex is this?

**Comment by itbel** [comment]
This does not sound too complex to me. Is there a design for the modal? 
Could we do this in a similar way as was done on the TMH Mobile app @GeorgeBellTMH?

**Comment by lucastbelem** [comment]
@itbel no specific design for this modal. But I have 2 thoughts:

- What if we used the modals from the profile designs? Too much of a takeover experience?
- What if we use something similar to the chat feature in courses? You know, the one that pull a third of a screen overtop of the screen the user is at, and they can chat through there? If we did it this way, I kind of think it'd be best to not make the screen takeover fullscreen (vertically) but rather more like a chat box. Here are a couple of examples (not specific models, just inspiration):
<img width="1440" alt="Screen Shot 2021-02-04 at 9 57 08 AM" src="https://user-images.githubusercontent.com/48295718/106910618-6a24eb80-66cf-11eb-8089-1ba4b3511ab1.png">
<img width="1434" alt="Screen Shot 2021-02-04 at 9 56 55 AM" src="https://user-images.githubusercontent.com/48295718/106910644-6d1fdc00-66cf-11eb-8797-38deb1b6388a.png">
<img width="1428" alt="Screen Shot 2021-02-04 at 10 00 21 AM" src="https://user-images.githubusercontent.com/48295718/106911066-d3a4fa00-66cf-11eb-91af-b190fb6d3bc5.png">
<img width="1438" alt="Screen Shot 2021-02-04 at 10 00 10 AM" src="https://user-images.githubusercontent.com/48295718/106911079-d6075400-66cf-11eb-80a9-6142aa889eff.png">

**Comment by lucastbelem** [comment]
@itbel I'd like to prioritize this for you.

@GeorgeBellTMH any thoughts before Igor gets started?

**Comment by GeorgeBellTMH** [comment]
I'm fine with just putting a ? next to the profile image on the menu that goes to a new page, or pops up a modal...I'm not a huge fan of the bottom right floating thing because it may cause more trouble over time than it's worth...

**Comment by GeorgeBellTMH** [comment]
For now lets just use email...we can use the ask-a-question backend on JC...just need to move over the lambda...

**Comment by lucastbelem** [comment]
> I'm fine with just putting a ? next to the profile image on the menu that goes to a new page, or pops up a modal...I'm not a huge fan of the bottom right floating thing because it may cause more trouble over time than it's worth...

I'm good with this plan, but rather than a "?" could we use the designed icon? If not, maybe we just write "need help"?

**Comment by itbel** [comment]
How should look like on auth flow screens?

**Comment by GeorgeBellTMH** [comment]
Ahh...good point, maybe it does need to be a floating thing in the bottom right....

**Comment by GeorgeBellTMH** [comment]
There is a component that does that...maybe it will work?

**Comment by GeorgeBellTMH** [comment]
https://docs.nativebase.io/Components.html#fabs-def-headref

**Comment by itbel** [comment]
Okay. I'll work with this. Which pages should this button be displayed in? @lucastbelem

**Comment by lucastbelem** [comment]
All of then, except courses because that main nav doesn't appear in courses.

**Comment by lucastbelem** [comment]
Sorry, just following the message trail. Definitely at sign in flows, curriculum pages, dashboard, events, groups etc...basically everywhere...but we'll need to think about placement.

The priority if you have to pick would be the resource One story and sign up flow.

**Comment by JonEsparaz** [comment]
Quick FYI: the Native Base floating action button is a little finicky. 

If you're having trouble, I implemented a FAB for the course chat, which could be reused: https://github.com/jesus-collective/mobile/blob/master/components/CourseViewer/ChatButton.tsx

**Comment by itbel** [comment]
> Quick FYI: the Native Base floating action button is a little finicky. 
> 
> If you're having trouble, I implemented a FAB for the course chat, which could be reused: https://github.com/jesus-collective/mobile/blob/master/components/CourseViewer/ChatButton.tsx


I see it. Thank you
