### ISSUE TITLE
Mobile Dropdown styling and icons

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#682]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/47749730/106950663-ba667280-66fc-11eb-81da-0a299b546eaa.png">

@mmacedom so can you:
1) get the gear icon to be centered and probably remove a bit of the padding...
2) pick some relevant icons for the dropdown items
3) determine if there is any other styling we should do? (not sure if this should be orange, or maybe transparent, or with a border?
4) for events make sure all the items show up without the scrolling

**Comment by mmacedom** [comment]
@GeorgeBellTMH Is this on the dashboard? I just pulled from master and I'm not seeing these drop downs. Let me know. Thx

**Comment by GeorgeBellTMH** [comment]
Ya, I think maybe there is some logic problem....it only shows up ifMobile...but it should probably show up even if it's desktop....just <720px...

**Comment by mmacedom** [comment]
@GeorgeBellTMH weird.  I'm not even seeing it on mobile. Once you merge my PR, I'll pull again and try again.

**Comment by mmacedom** [comment]
@GeorgeBellTMH I fixed these issues. Tried different colours for the button and it seemed like the orange seems to work best. Let me know what you think. PS: the cog svg needs to be crop so that the icon is totally centred.
