### ISSUE TITLE
Text box on profile

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#683]
User cannot see entire placeholder text in text box. Can we make the text box a bit longer vertically?

<img width="739" alt="Screen Shot 2021-02-04 at 3 43 25 PM" src="https://user-images.githubusercontent.com/48295718/106953045-ecc59f00-66ff-11eb-8140-5cc3453d267c.png">

**Comment by mmacedom** [comment]
@lucastbelem what screen size is this?

**Comment by lucastbelem** [comment]
1440px @mmacedom

**Comment by mmacedom** [comment]
@lucastbelem Thanks for letting me know. I'll work on it as soon as I get the npm issue resolved. I ran the new packages and I can't get my local to work. I messaged George about it already.

**Comment by mmacedom** [comment]
@lucastbelem this has been fixed
