### ISSUE TITLE
NPM 7 Issues

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#685]
Following error when running (v7.5.2) npm install (works on 6.14.11)

The following does work:
npm install --legacy-peer-deps 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: webpack@5.21.1
npm ERR! node_modules/webpack
npm ERR!   peer webpack@">=2" from babel-loader@8.2.2
npm ERR!   node_modules/babel-loader
npm ERR!     peer babel-loader@"^8.0.2" from @cypress/webpack-preprocessor@5.5.0
npm ERR!     node_modules/@cypress/webpack-preprocessor
npm ERR!       dev @cypress/webpack-preprocessor@"^5.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.18.1" from @cypress/webpack-preprocessor@5.5.0
npm ERR! node_modules/@cypress/webpack-preprocessor
npm ERR!   dev @cypress/webpack-preprocessor@"^5.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/georgebell/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/georgebell/.npm/_logs/2021-02-06T22_09_58_320Z-debug.log

**Comment by JonEsparaz** [comment]
```
$ npm install --save-dev @babel/core @babel/preset-env babel-loader webpack
$ npm install --save-dev cypress-file-upload@latest
```

How I fixed:
- Error message complains about `@cypress/webpack-preprocessor`
- Go to https://www.npmjs.com/package/@cypress/webpack-preprocessor#installation
- Install peer deps like the Readme says
- Oh wait, there's a new error:
```
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^3.0.0" from cypress-file-upload@3.5.3
```
- Let's get the latest version of `cypress-file-upload` to go with a newer version of `cypress`
- It works!

Notes:
- Tests run, but fail (seems like they were failing anyways)
- App compiles/runs on localhost
- Unsure if this will affect build

Hope this helps!!

**Comment by JonEsparaz** [comment]
```diff
"devDependencies": {
- "@babel/core": "~7.12.13",
+ "@babel/core": "^7.12.13",
+ "@babel/preset-env": "^7.4.5",
  "@cypress/code-coverage": "^3.8.1",
  "@cypress/webpack-preprocessor": "^5.5.0",
  "@expo/webpack-config": "~0.12.58",
  "@sentry/cli": "^1.55.2",
  "@sheerun/mutationobserver-shim": "^0.3.3",
  "@types/draft-js": "^0.10.44",
  "@types/googlemaps": "^3.39.8",
  "@types/react": "~16.9.35",
  "@types/react-dom": "~16.9.8",
  "@types/react-draft-wysiwyg": "^1.13.0",
  "@types/react-native": "~0.63.2",
  "@types/react-places-autocomplete": "^7.2.6",
  "@types/uuid": "^8.3.0",
  "@typescript-eslint/eslint-plugin": "^4.6.0",
  "@typescript-eslint/parser": "^4.6.0",
  "aws-sdk": "^2.704.0",
+ "babel-loader": "^8.1.0",
  "babel-plugin-dynamic-import-node": "^2.3.3",
  "babel-plugin-istanbul": "^6.0.0",
  "babel-plugin-transform-class-properties": "^6.24.1",
  "cypress": "6.4.0",
- "cypress-file-upload": "^3.5.3",
+ "cypress-file-upload": "^5.0.2",
  "dynamic-cdn-webpack-plugin": "^5.0.0",
  "eslint": "^7.3.1",
  "eslint-plugin-prettier": "^3.3.1",
  "eslint-plugin-react": "^7.20.0",
  "expo-cli": "^4.1.6",
  "husky": "^4.3.8",
  "lint-staged": "^10.5.3",
  "module-to-cdn": "^3.1.5",
  "nyc": "^15.1.0",
  "prettier": "^2.2.1",
  "start-server-and-test": "^1.11.0",
  "typescript": "~4.0.0",
+ "webpack": "^4.43.0",
  "webpack-bundle-analyzer": "^4.4.0",
  "webpack-cli": "^4.5.0",
  "webpack-merge": "^5.1.2"
}
```
