### ISSUE TITLE
Event dashboard sorting/querying

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#692]
When I create an event, and then refresh the page, it doesn't appear in the dashboard. The dashboard says no upcoming events.

<img width="1440" alt="Screen Shot 2021-02-10 at 9 54 56 AM" src="https://user-images.githubusercontent.com/48295718/107526742-2b3ade00-6b86-11eb-9bce-12a28e0096a6.png">

When I click "show all", no events appear, until I press "show more". At least the first 4-10 events should appear right away.
<img width="1440" alt="Screen Shot 2021-02-10 at 9 55 09 AM" src="https://user-images.githubusercontent.com/48295718/107526861-486fac80-6b86-11eb-8df9-d93b3730a09e.png">
<img width="1440" alt="Screen Shot 2021-02-10 at 9 55 04 AM" src="https://user-images.githubusercontent.com/48295718/107528369-c08aa200-6b87-11eb-91bd-b7145b3c3c40.png">

**Comment by lucastbelem** [comment]
@JonEsparaz if you have time this week.

**Comment by JonEsparaz** [comment]
I renamed the issue to be clearer because the events save, but there's something wrong with the dashboard.
