### ISSUE TITLE
Home - Sub pages mobile design

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#7]
We need to get the sub home pages from the navigation to adjust for mobile view properly. 

Access design files here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=21%3A18

Let me know if there are questions. The design is not as organized as the TMH work.

**Comment by GeorgeBellTMH** [comment]
I think we can close this?

**Comment by lucastbelem** [comment]
Yep. This was a general note for when Mateus was just starting out. Let's
close it and I'll create specific issues I encounter.
