### ISSUE TITLE
"Need Help" feature function

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#702]
The UI is all done, but we need something in the backend done in order for the button to work properly.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713127865)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH could you tackle this one please?

**Comment by GeorgeBellTMH** [comment]
Ok the function is added, just need @itbel to connect it up and do some testing...

**Comment by itbel** [comment]
I'm on it.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH let's de-prioritize this on your end. There is a lot of courses issues we need to solve pretty quickly, so I'd rather focus on those for now.

**Comment by lucastbelem** [comment]
Obsolete.
