### ISSUE TITLE
Course Details header

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#704]
The "Course Details" header appears below the text I add to the course details content.

<img width="1415" alt="Screen Shot 2021-02-12 at 11 32 35 AM" src="https://user-images.githubusercontent.com/48295718/107795429-a1764680-6d26-11eb-90c7-53fd65e29939.png">

**Comment by mmacedom** [comment]
@lucastbelem I changed the order of the elements (details above and then the copy).

**Comment by GeorgeBellTMH** [comment]
Note, this wasn't actually an error...

The Course Details is the header for the accordion that should show up here, but is not...

**Comment by mmacedom** [comment]
@GeorgeBellTMH I'm confused. lol... so what needs to be done?

**Comment by GeorgeBellTMH** [comment]
Nothing at this point, once the accordion works it will make sense...
