### ISSUE TITLE
Password feedback for user

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#708]
It tells the user their password is not long enough, but not how long it should be or what should be in it.

**Comment by GeorgeBellTMH** [comment]
Ya, we need to move that logic over from TMH…

**Comment by itbel** [comment]
![Screenshot from 2021-02-15 14-09-01](https://user-images.githubusercontent.com/42515854/107985094-62026100-6f97-11eb-9e35-f35b430b3da3.png)
This seems to be working for me. Could it have something to do with smaller resolutions not showing the error message at all?

**Comment by lucastbelem** [comment]
Huh. Could be. Maybe this is ok then.

But seeing that error message, it's really confusing. Could we simplify
that for the user?
