### ISSUE TITLE
Filter out text from product summary

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#710]
Here is what the product calculation summary looks like:

<img width="424" alt="Screen Shot 2021-02-12 at 4 33 26 PM" src="https://user-images.githubusercontent.com/48295718/107824783-0eea9d00-6d50-11eb-9040-67a0808135d5.png">

It's too much information, it's confusing, and the tier language is one we want to get away from. We want the summary to always only say:

One Story Curriculum - Early Years
One Story Curriculum - Kids
One Story Curriculum - Junior High

And prices are only needed in the bolded section.

**Comment by GeorgeBellTMH** [comment]
Can you confirm, essentially just get rid of the stuff between the ( and ) as well as everything before and including: " x "

**Comment by lucastbelem** [comment]
You got it.
