### ISSUE TITLE
Automatically delete head branches [repo quality]

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#712]
Detail: https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

Rationale: There's 150+ branches at the moment, most of which are stale. The extra branches make fetching from upstream marginally slower and makes the repo look untidy.

**Comment by JonEsparaz** [comment]
Deleting the existing stale branches is probably a good idea.

**Comment by GeorgeBellTMH** [comment]
Done

**Comment by JonEsparaz** [comment]
I deleted most of the existing stale branches, but I didn't want to accidently delete an active branch.

@mmacedom please delete any of your remaining stale branches - thanks!

**Comment by mmacedom** [comment]
@JonEsparaz I'll do

**Comment by mmacedom** [comment]
@JonEsparaz just cleaned all of my stale branches on the remote

**Comment by JonEsparaz** [comment]
Thanks @mmacedom 🙏
