### ISSUE TITLE
Ensure testing doesn't fail for Style issues

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#72]
Currently the tests are failing because some fields are not fully visible in mobile and tablet...styles should allow for all elements to be visible during testing.

**Comment by mmacedom** [comment]
@GeorgeBellTMH Can you elaborate? What fields are not visible?

**Comment by GeorgeBellTMH** [comment]
If you run npm test and then click on the test that pops up you will see.

Sent from my iPhone

On Jun 1, 2020, at 7:00 PM, mmacedom <notifications@github.com> wrote:

﻿

@GeorgeBellTMH<https://github.com/GeorgeBellTMH> Can you elaborate? What fields are not visible?

**Comment by mmacedom** [comment]
@GeorgeBellTMH I adjusted the width of the fields that were overflowing beyond the container width. Should have done the trick now. Let me know on your end if it's solved

**Comment by lucastbelem** [comment]
@GeorgeBellTMH is this done?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can we close this?

**Comment by GeorgeBellTMH** [comment]
Yup, testing is a bigger issue we will have to tackle later...
