### ISSUE TITLE
Null value(s) causing One Story page to crash

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#720]
I'm trying to add a menu item to the One Story resource. The menu item adds, and I'm able to edit the page. However, when I navigate away and try to click the menu item, it gives me the following:

<img width="1440" alt="Screen Shot 2021-02-15 at 9 39 26 PM" src="https://user-images.githubusercontent.com/48295718/108012009-4d918900-6fd6-11eb-8015-3f4293f8f454.png">

I've deleted the menu item for now so users don't encounter the error.

**Comment by GeorgeBellTMH** [comment]
Is this still happening?

**Comment by lucastbelem** [comment]
I thought this was resolved, but it seems it's back or wasn't fixed.  @GeorgeBellTMH @JonEsparaz whoever can tackle it first, I'd appreciate it.

**Comment by JonEsparaz** [comment]
I've got a fix. PR coming.
