### ISSUE TITLE
As a non-admin user, manual card navigation does not work

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#726]
@GeorgeBellTMH @JonEsparaz 
When I log in with my non-admin user account and click on cards that were manually created for which a navigation url was added, I am not taken to the appropriate series page. 

The platform reloads (as is currently designed because the url I pasted is the entire platform url) but it only reloads back to the overview page, rather than take me all the way into the resource.

This is an issue because it basically takes away the purpose of the overview page.

Text for questions.

**Comment by JonEsparaz** [comment]
I was having the same issue yesterday.

@GeorgeBellTMH can you give me an explanation of the logic behind the reload to check permissions?

**Comment by JonEsparaz** [comment]
Also, how is a specific resource even protected? `readGroups` only exists in the ResourceMenuItem and Group tables, not the Resource table. Is this an oversight in the schema?

Need to figure this out for #665.

**Comment by JonEsparaz** [comment]
Additional info on the issue itself: the URL is https://beta.jesuscollective.com/auth/signin after the reload finishes, but we see the One Story overview page.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH @JonEsparaz 

Here is a possible workaround:

The issue only seems to appear for manual cards. I only use manual cards for series because I need the attributes "title 1" and "title 2". If I have that in auto cards, then I can change all of them to auto cards. Auto cards also don't produce the full reload, so that would take care of that too.

Long term we'd still need to fix this more fully as some resources require the manual card, but for now, when series is the bulk of what we do, this could solve the problem.

**Comment by GeorgeBellTMH** [comment]
Ok...so here is the story...

Initially the plan was only to protect the menu items...and the resources were going to be under the menu items...

After the redesign it became clear the resources needed to be separate of the menu items...

To get it working I decided not to protect the resources since that was going to add a lot of time/complexity and components that didn't exist at the time...the plan was always to go back and protect the resources once more of the components existed...so we are here now...

**Comment by GeorgeBellTMH** [comment]
Those components exist now, so it would be good to go and add permissions on the resource table...

**Comment by GeorgeBellTMH** [comment]
That way auto cards can decide to show or not show themselves if the user has permissions...

**Comment by JonEsparaz** [comment]
I think the manual cards are following the `if` branch of this arrow function:

```typescript
onPress={() => {
  if (this.props.pageItem.url) {
    window.location.href = this.props.pageItem.url ?? ""
  } else {
    this.props.navigation.navigate("ResourceDisplayScreen", {
      id: this.props.resourceState.groupData?.id,
      resource: this.props.pageItem.resourceID,
      series: this.props.pageItem.seriesID,
      episode: this.props.pageItem.episodeID,
    })
  } 
}}
```

Auto cards seem to navigate directly. I think we can get rid of the `if` branch and solve the problem.

**Comment by GeorgeBellTMH** [comment]
Manual cards were always a workaround for not having fully built all the functionality of permissions etc...

**Comment by GeorgeBellTMH** [comment]
Ideally we just get rid of the "url" part of manual cards and make them point directly to a resource/series/episode...still with the ability to customize the description and title...

**Comment by GeorgeBellTMH** [comment]
To do that we need to modify the admin piece as well as that url section you have....

**Comment by GeorgeBellTMH** [comment]
I think it might still be good to have an "External Card" that pops up a new window and uses the url...but there isn't any examples of that right now...

**Comment by JonEsparaz** [comment]
> That way auto cards can decide to show or not show themselves if the user has permissions...

I though the cards are supposed to be seen by all users, so they can preview the resource, but when they try to download, a modal says, "you didn't pay for this, plz give JC more money"

**Comment by GeorgeBellTMH** [comment]
Sorry, you are correct...instead of not showing, it should redirect to the message...

**Comment by JonEsparaz** [comment]
> I think it might still be good to have an "External Card" that pops up a new window and uses the url...but there isn't any examples of that right now...

Why would there be resources hosted outside the platform?

**Comment by GeorgeBellTMH** [comment]
On the overview page we might want to do something like link to YouTube, or point users to some external resource...again, we have no examples of that...but it may be useful....

**Comment by lucastbelem** [comment]
I actually added an example of what you're describing yesterday, @GeorgeBellTMH.

I made a resource card that just points the user to the one story blog, externally. One day, blogs will exist in the platform, but for now, they'll point externally.
