### ISSUE TITLE
Reset to defaults when Switching between autocard and manual cars

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#731]
When switching between auto and manual cards reset all the values to their defaults.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713127212)

**Comment by lucastbelem** [comment]
Case study for issue found at #688. When solving this, please close both issues.

**Comment by lucastbelem** [comment]
Will be addressed by admin project.
