### ISSUE TITLE
Profile creation issue

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#74]
A few people have performed tests on beta and came across issues creating their profile. As this isn't generalized, I suspect the issue is due to human error, though I wonder how much of it is related to how the design is showing. Here is an example of the error someone was getting: 
<img width="418" alt="Screen Shot 2020-05-31 at 2 20 26 PM" src="https://user-images.githubusercontent.com/48295718/83360103-b3f15100-a34c-11ea-8bdb-e61ff909a6e0.png">.

The error didn't make it clear to them what the problem was. Could we make all fields that have errors or that the person forgot to fill highlight red so it's clear to them where the error is?

**Comment by GeorgeBellTMH** [comment]
@mmacedom can you see if there is a better place to put the error message (maybe make it bold/red) for now...we can try to make it highlight the missing fields in v2

**Comment by mmacedom** [comment]
@GeorgeBellTMH Yes, I'll look into it.

**Comment by GeorgeBellTMH** [comment]
Can we make sure the logout button is visible too...

**Comment by mmacedom** [comment]
@GeorgeBellTMH @lucastbelem Can you tell me what medium (desktop, tablet, mobile) that button was being cut off?

**Comment by GeorgeBellTMH** [comment]
Desktop and ipad – the private information fields are extended past the column when creating an account.

I think the other ones I saw are fixed…

**Comment by mmacedom** [comment]
@GeorgeBellTMH  @lucastbelem the error validation has been fixed (red and bold). Please confirm on your end
