### ISSUE TITLE
UI Changes to mini-message board in Courses

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#752]
@mmacedom here is one that I have for you. The mini-message board in courses needs a few tweaks. There is a lot of wasted space in there. Here are some changes:

- [x] As per the Figma design, can you please remove the profile picture from the text box and have it outside? This should shrink the size of the text box header (grey part) and should bring the text closer to the name/title.
- [x] Make photos for replies appear smaller as per figma design
- [x] Extend the message board all the way down the page so that more messages are visible at a glance.
- [x] Move the "post" button into the text box
- [x] Remove the grey frame around the text box for posting a message
- [x] Remove drop shadow from bottom of messages
- [x] Remove timestamp from messages
- [x] Make "reply" button smaller

**Comment by mmacedom** [comment]
@lucastbelem I made all of the changes but am still tweaking the UI a bit.

**Comment by GeorgeBellTMH** [comment]
Closing
