### ISSUE TITLE
Remove "partners" and "friends" legend from map (for now)

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#753]
Friends don't exist yet and that's language that hasn't been communicated. Please hide the legend as circled here:

<img width="1440" alt="Screen Shot 2021-02-23 at 8 24 01 PM" src="https://user-images.githubusercontent.com/48295718/108931202-3d505e00-7615-11eb-8dd8-a0b85acaef6b.png">

**Comment by mmacedom** [comment]
@lucastbelem, just pushed a fix for this.
