### ISSUE TITLE
Course adjustments

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#757]
On the main page of a course, in regards to the instructor:

- [x] Change "start conversation" to send a message"
- [x] Picture for the instructor is not centred above "start conversation"
- [x] Name and role should not be displayed here (instructor is the role already, so it's repetitive and name is not in the design...instructor is expected to write that in their bio.

**Comment by mmacedom** [comment]
@lucastbelem these changes were made. They are in the open PR
