### ISSUE TITLE
Course navigation styling

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#758]
What would it take to change the menu to match our Figma design?

<img width="829" alt="Screen Shot 2021-02-26 at 9 46 22 AM" src="https://user-images.githubusercontent.com/48295718/109314594-8c65e100-7817-11eb-9804-4c899bda2e8a.png">

**Comment by lucastbelem** [comment]
@mmacedom if there are things preventing it from looking exactly the way it's supposed to be, can we get closer to it? I.e. not black?

**Comment by mmacedom** [comment]
@lucastbelem are we still holding off on this change?

**Comment by lucastbelem** [comment]
@mmacedom yes please hold off.
