### ISSUE TITLE
Links in Week descriptions

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#759]
I entered hyperlinks in the description for a week in a course. Then created the lessons. Then went back to the description to edit the hyperlinks, but suddenly, the hyper links stopped working. It appears that hyperlinking only works when I create the description the first time.

<img width="1223" alt="Screen Shot 2021-02-26 at 10 03 49 AM" src="https://user-images.githubusercontent.com/48295718/109316956-2464ca00-781a-11eb-98f2-b5dd93cecc61.png">

**Comment by itbel** [comment]
I'm unable to replicate this issue. It seems to work for me.

**Comment by GeorgeBellTMH** [comment]
Note - you have to click off the text field after you enter the value for it to save...closing unless there is a way to duplicate.
