### ISSUE TITLE
Assignment submission issues

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#763]
- [ ] Assignment submissions are not visible until after the user refreshes or leaves the page.

**Comment by GeorgeBellTMH** [comment]
The last time I asked this the word count was a suggestion, not a hard limit. We can change it if you want, but it's a bit easier to just leave it as a suggestion....

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I remember that too - I wasn't sure, but now that you said it, it's ringing a bell.

**Comment by lucastbelem** [comment]
I removed the word count requirement from this issue. If we can fix the refresh issue that'd be great. Maybe @itbel can help?

**Comment by GeorgeBellTMH** [comment]
I believe this is fixed in the next release.
