### ISSUE TITLE
Replies in assignments

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#764]
Do these exist? It's been tricky getting enough people to test courses properly. From a test I did today, with only one user, when they went to reply to an assignment, they could not "reply" or "comment" on the assignment submitted. Anything they wrote was added as another assignment.

**Comment by GeorgeBellTMH** [comment]
Replies do not exist in the assignment section right now...

**Comment by GeorgeBellTMH** [comment]
They do exist in the mini-message board...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH @JonEsparaz Oh! That's bad...I thought we implemented replies everywhere?

Replies in the assignments is the piece that stopped the OLC last time. What do we need to do to make this happen?

**Comment by GeorgeBellTMH** [comment]
We need to implement replies for DM's...which is what it's built on...give me a minute to think about it...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH sounds good. Text or call if you need answer on anything right away. I'll need to log off for a couple hours, but can be available if you need me.

**Comment by GeorgeBellTMH** [comment]
I'm going to implement this one tonite...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I can submit assignments from different users. However, users cannot see each other's assignments and therefore cannot reply to them. They can only see their own assignment.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH  Also note replies don't seem to be working in the mini-message board now.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this checks out. Mini-message board working properly now.

Just assignments now.

**Comment by GeorgeBellTMH** [comment]
This works now.
