### ISSUE TITLE
CRM manual payment adding issue

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#765]
When I try to choose a payment group in the CRM for a user so that they can bypass payment (i.e. for a course) usually I'm able to. It seems I cannot do this for one user in particular though: rachel.meredith@themeetinghouse.com. 

Every time I click "payments" in the CRM to select a payment group, I'm taken to a blank screen. This works for other users though.

<img width="1432" alt="Screen Shot 2021-02-26 at 5 10 21 PM" src="https://user-images.githubusercontent.com/48295718/109360625-8d1d6800-7855-11eb-8d26-65bf3bea4e70.png">

**Comment by lucastbelem** [comment]
@JonEsparaz this wouldn't be related to any CRM work you did right? I don't think so, but wanted to just check.

**Comment by JonEsparaz** [comment]
Correct, the admin message board is isolated - completely separate part of the API.

**Comment by lucastbelem** [comment]
The weird thing about this one is that it only happens with one user.

**Comment by GeorgeBellTMH** [comment]
This should be fixed now...
