### ISSUE TITLE
Member visibility

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#766]
One Story users are only supposed to see other one story users. Can we make this possible soon? 

Additionally, the team has now requested that partners only see partners. 

The first is a must, the second is a change and therefore lower priority.

This would be both on the map and the directory.

Could we use SubscriptionValid and SubscriptionPartner for the logic?

Pending: what does this mean for groups and events? Should partners and one story users see each other if they land in the same group? I'd say yes, but need to confirm this.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713126731)

**Comment by GeorgeBellTMH** [comment]
did we get an update on this? can we close?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH got an update for you:

Stakeholders have confirmed that we need to adjust the visibility between users, but affirm your suggestion to not altogether hide them and instead provide a user-managed filter based on permission groups. This is needed for the map and the directory. Groups, events, etc aren't impacted by this because you've already implemented permission setting in those. Can we do the following:

- [ ] Add a toggle to the map (where the toggles already are) that says "show all Jesus Collective users"
- [ ] For partners, when the toggle is off, only other partners are seen
- [ ] For subscriptionEarlyYears, subscriptionKids, and subscriptionYouth, when the toggle is off, only users in those 3 groups are seen
- [ ] I'm not sure what to use, but can we do the same thing in the directory? Provide that toggle? Maybe in the directory page it can be a checkbox?
- [ ] In the vertical scroll directory, can we display only the default group visibility (i.e. only partners for partners, only one story for one story)?

This is the more immediate need when it comes to user visibility. Please note that there could be a future in which they ask us to add further options in this user-managed toggle (i.e. see only subscriptionKids) but that is not a need at the moment.

**Comment by lucastbelem** [comment]
@GeorgeBellTMHI forgot to explain this:

If a user is a partner and a curriculum user, for the purposes of the toggle, they should be seen as a partner as they are partners first.

So if the toggle "show all users" is off for a partner who is a curriculum user, that user should only see partners. 

Cool?

Groups and events shouldn't be a problem because you already gave us the ability to permit individually. So if I want a group just for partners, I already can make it so.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH a summary of what needs to be accomplished here:

- [ ] Filter (dropdown) available on the map to switch between viewing other users who are members of the same group as you (i.e. partners) and all members of the platform
- [ ] Filter (dropdown) available on the profile directory to switch between viewing other users who are members of the same group as you (i.e. partners) and all members of the platform
- [ ] Fix function responsible for displaying user category (i.e. currently displays "un-verified" for everyone)

I'll post the titles for curriculum users and JC staff as soon as I get confirmation from Matt.

**Comment by GeorgeBellTMH** [comment]
Ok I think this is working on the profile page now...there is a dropdown.

**Comment by GeorgeBellTMH** [comment]
Users should also no longer show up as un-verified.

**Comment by GeorgeBellTMH** [comment]
The Connect With Others section always just shows your users....the map shows whichever users are visible (so on the homepage it will always be just your group...but on the profile page if you turn on show all then it will show them all on the map)

**Comment by GeorgeBellTMH** [comment]
Note, admins will always default to All....

**Comment by GeorgeBellTMH** [comment]
I believe the user groups are updated once every hour...so new users will show up incorrectly for the first hour or so...

**Comment by lucastbelem** [comment]
This has evolved so many times...I'm gonna close this and start fresh.
