### ISSUE TITLE
User stuck on payment screen

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#771]
Credit card got declined for fraud as user was setting up and paying for a OneStory account. They've corrected the issue, but when they come back into the payment page it seems to freeze up on "processing your account." Text me if you want the user email.

User is trying to pay us so I'd like to get this resolved asap.

Reproduce:
Process payment with invalid credit card

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713126513)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I guess I could delete their account and tell them to start again?

**Comment by lucastbelem** [comment]
The user has a failed subscription in Stripe. Could that be the problem? Is the platform checking for a subscription and says he has one, but doesn't know that it failed? If so, deleting the failed subscription should resolve the problem?

**Comment by GeorgeBellTMH** [comment]
Yes. I think there is no way to resume a subscription that is paused. I think if stripe shows the right card is attached you could unpause it and it should get paid. 

We may have to do more testing around pausing and starting subscriptions again.
