### ISSUE TITLE
Course marketing page (landing page)

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#772]
@mmacedom can you please update this page to match our design here: https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=1526%3A53093

In particular, I'm looking for that accordion to get updated to add a bit of visual grab to the page. If you need mock data to work with, use the data that's in the course: Pastoral Leadership in a post-Christian culture.

The accordion uses data from within the course to exist. Weeks are determined by the menu items in the course (i.e. week 1, week 2) and the items inside the accordion are determined by the lessons/assignments that exist in each week.

A couple other changes:

- [ ] Can we update button styles on that page to solid fills?
- [x] Can we include icons for the course attributes as per the design? i.e. effort, start date, etc.
- [ ] Could we possibly remove the titles from attributes as well? The design calls for the icons to be the way the user identifies what attribute they're looking at. @GeorgeBellTMH what do you think of this? @mmacedom leave this one for last depending on what George thinks.

**Comment by GeorgeBellTMH** [comment]
Why do we want the buttons to look different from the same buttons on events/groups pages?

**Comment by GeorgeBellTMH** [comment]
I would suggest keeping the titles for accessibility...

**Comment by mmacedom** [comment]
@GeorgeBellTMH How have you been manipulating colours of the svg icons we have?

**Comment by GeorgeBellTMH** [comment]
Can we close this one?

**Comment by mmacedom** [comment]
We can close. the only thing is I need to know where you got the svg icons from so I can find new ones that have the same style. Let me know

**Comment by lucastbelem** [comment]
@mmacedom I'm guessing George got it from the Figma mock ups here:https://www.figma.com/file/aJzmRbxyuoqkRPUikSVwUgwk/Jesus-Collective?node-id=105%3A564

**Comment by GeorgeBellTMH** [comment]
I don’t know…they came from figma design…

**Comment by lucastbelem** [comment]
@mmacedom the accordion is not done yet, right? It works, but it's not styled. Here is what I see currently:
<img width="1411" alt="Screen Shot 2021-03-11 at 11 30 59 PM" src="https://user-images.githubusercontent.com/48295718/110892362-eb206580-82c1-11eb-9ff6-4d6d385deccc.png">

**Comment by mmacedom** [comment]
Great. Thx! I'll get it from there and will update the icons on the screen

**Comment by mmacedom** [comment]
I just pushed the new icons!
