### ISSUE TITLE
Text wrapping in courses

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#773]
@mmacedom you'll see in the image attached that the chat button that moves with the screen overlaps the title underneath it. Can you change the text wrapping to account for the button being on the page?

<img width="1437" alt="Screen Shot 2021-03-05 at 5 07 14 PM" src="https://user-images.githubusercontent.com/48295718/110178981-48557c00-7dd5-11eb-9975-3aa7ed37854c.png">

**Comment by GeorgeBellTMH** [comment]
I don't think we should fix this...it's a hovering object...if you change the wrapping based on where it is the text will jump around...and if we have to move everything out of the right 50 pixels the margins will be messed up...note that there will also be a hover for the help, and we can't make room for that either...

This page will scroll once it has courses on it, so it should be relatively straight forward for the user to see what is below this...

Other solution is to move the chat hover out of the right side and into the top menu...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH fair enough. Let's leave it :)
