### ISSUE TITLE
Mini message board: cannot access text input

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#774]
The text input renders below the bottom of the screen. I'm on a laptop; window resolution is 578x1280 according to Dev Tools. The height of the container should scale with the screen height.

Screenshot from https://github.com/jesus-collective/mobile/commit/dba5cc5ec2012da51bb9a3fa735d355f56c5014b (breaking commit):
![image](https://user-images.githubusercontent.com/48423418/110181570-1bf02e80-7dda-11eb-9d1c-e515384ef284.png)

Screenshot from https://github.com/jesus-collective/mobile/commit/e833b06612189842a229ce2e9ba5dda63184744a (one commit before):
![image](https://user-images.githubusercontent.com/48423418/110181444-cf0c5800-7dd9-11eb-95c8-2c0a46247001.png)

**Comment by lucastbelem** [comment]
@JonEsparaz thanks Jon. I made a comment about this, but I think I put it in the merged PR. @mmacedom can you take a look?

**Comment by mmacedom** [comment]
@lucastbelem @JonEsparaz This has been fixed. There was an issue with how the reply component was rendering with and without the inspect tool. With the inspect tool deployed (on the sides of the screen), the component was rendering higher than what it did without the inspect tool. See screen shots
<img width="1440" alt="Screen Shot 2021-03-07 at 9 32 34 PM" src="https://user-images.githubusercontent.com/24467324/110267993-ea6c9400-7f8e-11eb-931a-18b93a1f40c5.png">
<img width="1440" alt="Screen Shot 2021-03-07 at 9 32 54 PM" src="https://user-images.githubusercontent.com/24467324/110267996-eb9dc100-7f8e-11eb-8c87-6165799fe4dc.png">
