### ISSUE TITLE
Admin/Coach view does not display assignments submitted

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#777]
Exactly as titled. All users were added and only then were assignments submitted. However, when I logged in as a coach, I could not see assignments submitted.

**Comment by lucastbelem** [comment]
<img width="1440" alt="Screen Shot 2021-03-08 at 10 10 23 AM" src="https://user-images.githubusercontent.com/48295718/110356607-6fe05a80-8008-11eb-8733-db808dc9d854.png">

**Comment by GeorgeBellTMH** [comment]
Fixed
