### ISSUE TITLE
Response assignment screen width

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#779]
Response assignments should extend the width of a screen for everything that's above the green bar.

<img width="1436" alt="Screen Shot 2021-03-08 at 10 08 23 AM" src="https://user-images.githubusercontent.com/48295718/110359225-3ceb9600-800b-11eb-9065-7b1fc2d5f319.png">

**Comment by GeorgeBellTMH** [comment]
This is fixed.
