### ISSUE TITLE
Time removal from assignment headers

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#780]
Any reason to keep this here from your perspective, @GeorgeBellTMH? If not, @mmacedom can we please omit the time from the circled element for every lesson? Let's keep the icon and the date, but remove the time. Or keep the time, but can we clean it up? I.e. add it to a second line?

<img width="1429" alt="Screen Shot 2021-03-08 at 12 40 46 PM" src="https://user-images.githubusercontent.com/48295718/110359649-bd11fb80-800b-11eb-9cc5-ef33d7241adf.png">

**Comment by GeorgeBellTMH** [comment]
It should just be formatted better...and the date should be in a nice text format instead of timestamp.

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH I just formatted the time to (Month day, year time). Ex: March 11, 2021 11:00 AM

**Comment by GeorgeBellTMH** [comment]
Fixed
