### ISSUE TITLE
Can't save links in week descriptions

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#781]
I think this is a design thing, but when I try to add a link, I can't. I think it's a design thing because maybe there is a button to close the dialogue box or save it, but it's hidden behind the lesson?

<img width="1433" alt="Screen Shot 2021-03-08 at 12 45 23 PM" src="https://user-images.githubusercontent.com/48295718/110360131-550fe500-800c-11eb-9da1-43f1660b39f9.png">

**Comment by mmacedom** [comment]
@lucastbelem This has been fixed.
