### ISSUE TITLE
Dropdown box for picking courseUser is jumbled

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#782]
Easier to just see than describe it. Marking it as low priority because I think it's only an issue when there are many people with the same name.

<img width="1440" alt="Screen Shot 2021-03-08 at 9 44 37 AM" src="https://user-images.githubusercontent.com/48295718/110360256-7ec90c00-800c-11eb-95cf-4421411352d3.png">

**Comment by GeorgeBellTMH** [comment]
I've been trying to think of the best way to deal with this...I think if we sort by alphabetical, followed by created date then the newest users will be at the top...

**Comment by mmacedom** [comment]
Sounds like a reasonable approach. Would alphabetically be the default?

**Comment by mmacedom** [comment]
@GeorgeBellTMH we can limit the height of the drop down and add a scroll as well. Thoughts?

**Comment by mmacedom** [comment]
@GeorgeBellTMH I added a zIndex property to the component so they render above the others. let me know what you think about the solutions mentioned above.

**Comment by mmacedom** [comment]
@GeorgeBellTMH Where is the drop down <ul> being rendered from? Inside Chips (EditableUsers.tsx line 87)?

**Comment by mmacedom** [comment]
@GeorgeBellTMH Please let me know how to proceed with this element and where the drop down is rendering from.

**Comment by mmacedom** [comment]
@GeorgeBellTMH is the dropdown being rendered from (EditableUsers.tsx line 87)?

**Comment by mmacedom** [comment]
@lucastbelem, please let me know if the changes made took care of the issue. Thanks
