### ISSUE TITLE
Email notifications for courses not working

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#785]
Email notifications for course assignments and mini-message board not triggering.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I tested this more today. Emails are not triggering for the chat hover, assignment submissions or assignment responses.

**Comment by GeorgeBellTMH** [comment]
This should be fixed....I have made some changes ...also make sure you have the alerts permissions setup correctly in your config..
