### ISSUE TITLE
Mini messageboard input box moving the wrong way

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#786]
If I add lines of text, the box moves down, pushing the "post" button out of sight.

<img width="1436" alt="Screen Shot 2021-03-08 at 4 44 16 PM" src="https://user-images.githubusercontent.com/48295718/110386155-f3607280-802d-11eb-8801-f3b2ad1a4d8e.png">

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH I spent some time today trying to figure this out and I'm out of ideas to make the text area scale upwards. I haven't been able to find anything about it either. The only solution I can come up with is setting a height limit to the area and setting it to scroll if the text is longer than the container. Any ideas here would be great. Thanks

**Comment by GeorgeBellTMH** [comment]
This is fine for now.
