### ISSUE TITLE
Course UI improvements

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#794]
@mmacedom now that George implemented replies in assignments, can you do some work to clean it up? Here are a couple of things I'm thinking: (if you need a mock course with data, use the course titled: March 10 test 4.)

- Can we unlock the course header? With the design we have implemented, too much space is taken on the course page by the header. I think you already did this for mobile.
- Can we make the assignment replies look a bit more like the UI for the chat drawer? A bit cleaner, better spacing, etc? 
- Increase the height of the assignment response container so user can see more responses at a time.
- Increase the width (where appropriate based on screen sizes) to accommodate for more responses.

Some context for the last 2 comments above:
The audience engaging with courses is primarily made up of pastors. Pastors write A LOT. The more we can do to make that experience clean and easy to navigate the better.

**Comment by GeorgeBellTMH** [comment]
Note if we keep the header and make it move, then the menu will also move and eventually be off screen...which will be a problem. Getting rid of the header, or putting the menu above the header will allow us to lock it to the top of the page.

**Comment by lucastbelem** [comment]
Agreed. Let's keep the header on the "home" screen of courses and remove it
from the "courses" screen altogether.
Menu at the top instead.

**Comment by mmacedom** [comment]
@lucastbelem @GeorgeBellTMH I commented out the header on all "courses" screens so it doesn't appear, I also fixed the reply box in assignment (taller and wider). Where did you guys get the small svg icons from? I need to find new icons (for the course main page) that have similar style to keep all of them consistent.

**Comment by mmacedom** [comment]
@lucastbelem Can you clarify a bit more on the second comment, please? (Can we make the assignment replies look a bit more like the UI for the chat drawer? A bit cleaner, better spacing, etc?)

**Comment by lucastbelem** [comment]
@mmacedom sure! I was referring to the changes related to #752 that you already made to the mini messageboard. 

We'll need to consider nesting threaded replies in a collapsable dropdown in the future, but for now, we just need to give users as much clarity as possible to navigate all of the messages displayed.

**Comment by GeorgeBellTMH** [comment]
Mostly fixed? Please make new tickets as needed.
