### ISSUE TITLE
Threaded replies don't notify recipients

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#799]
Assignment notifications are working beautifully. However, if person A replies to person B in person C's assignment, an email notification is not triggered.

**Comment by GeorgeBellTMH** [comment]
I think this is fixed, can you do a few...if it doesn't work - let me know what time you did it, it will help with debugging...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I just tested this. I replied to a response in Mandie's assignment in a course. The assignment post notified, the original responses notify, but when I replied to a response in Mandie's assignment, that did not notify. This was done tonight at 8:35pm in the course called "March 23 test 1" in dev under the only "respond" type assignment in that course.

**Comment by GeorgeBellTMH** [comment]
Ok, this is fixed...old replies in courses will be unavailable (so don't worry if a bunch are showing as unavailable)...should work on new replies going forward...
