### ISSUE TITLE
Course Marketing page accordion

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#800]
The accordion uses data from within the course to exist. Weeks are determined by the menu items in the course (i.e. week 1, week 2) and the items inside the accordion are determined by the lessons/assignments that exist in each week.

**Comment by lucastbelem** [comment]
@mmacedom if you want to see a course with a fully build accordion, check this one out on beta: https://beta.jesuscollective.com/app/courseoverview?create=false&groupType=null&id=course-1616018842166

**Comment by mmacedom** [comment]
@lucastbelem I made an initial push with some fixes for this. I still have some stuff to do on it though

**Comment by mmacedom** [comment]
@lucastbelem this has been completed.
