### ISSUE TITLE
Assignment response module adjustments

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#801]
@mmacedom as per our discussion today:

- [x] "Write response" input field is top of posted assignment responses as seen in the image below:
<img width="1440" alt="Screen Shot 2021-03-15 at 10 31 23 AM" src="https://user-images.githubusercontent.com/48295718/111202798-adaa2980-859a-11eb-97be-08e31b8f9596.png">

- [x] Can you please make the input field large enough for 300 words to be seen at once and anything beyond 300 words gets contained in the scroll? Feel free to expand the white background this sits on further down the page to accommodate for this. In fact, maybe do that anyways so that the user can see more responses at once as well.

**Comment by mmacedom** [comment]
@lucastbelem This has been fixed.
