### ISSUE TITLE
Chat drawer minor design adjustment

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#802]
@mmacedom as per our discussion today:

- [x] Can you please increase the height of the input text field by enough to accommodate 1 more line of text? 
- [x] Can you please lock the input text field so that anything more than 3 lines is in a self-contained scroll rather than expanding the box? Unfortunately, expanding the box isn't working out and takes the "post" button out of view.

**Comment by mmacedom** [comment]
@lucastbelem done.
