### ISSUE TITLE
DM page link in course

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#803]
What would it take to get a button or link added to the course page somewhere (location tbd) that links the user straight to their DMs page? Realizing that currently, in courses, the user cannot easily see their DMs. 

Current path - Click JC logo -> Click profile icon -> Click "Messages".

**Comment by GeorgeBellTMH** [comment]
I think what I'd like to do is add the profile and admin buttons to the course menu on the top right (so it matches the rest of the site)....and then we'll add a messages icon that will be on all pages along with the admin/profile buttons.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH I like this! 

For courses, could we also make it open on a separate browser window? Because of the nature of how it works now, it gets the user out of the course if they clicked it and it's not so quick and simple to find their way back to the course.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH if there is an MVP version for this OLC I'm good with that too.

**Comment by GeorgeBellTMH** [comment]
This now exists...I didn't make it open in a new browser....I think it should open a modal that has the messages in it...but we'll have to work on that...
