### ISSUE TITLE
Word Count

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#805]
Stakeholders reverted change:

- [ ] Word count represents the minimum number of words needed for an assignment to be able to be submitted
- Can we accomplish this by making the "post" button disabled until 300 words are reached?
- [ ] Bonus points if we can provide users with feedback if they try to submit when under 300 words.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH wanted to confirm that the minimum word count is supposed to be applied to both assignments and response assignments.

**Comment by GeorgeBellTMH** [comment]
This is done.
