### ISSUE TITLE
Open in new window Links in course not opening in new window

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#810]
Even though the user is creating a hyperlink and checking the box for "open in new browser window" the link is opening on the same browser window.

**Comment by GeorgeBellTMH** [comment]
Where?

**Comment by lucastbelem** [comment]
@GeorgeBellTMH in courses. The issue was identified on beta. Go to the course "inner life of an effective leader", and click on any of the links in the descriptions of the weeks or assignments. All of them have the box "open in a new browser window" but none of them are actually doing that. They're taking the user away from the course page.

**Comment by GeorgeBellTMH** [comment]
I believe this should be fixed....I have defaulted the target to be _blank

If the target is not _blank, set it to _blank and check the box.

**Comment by lucastbelem** [comment]
@JonEsparaz once you tackle what's left of the calendar, if you have time, would you be able to take a look at this one? George was trying to figure out what the problem was here, but wasn't able to fix it before he went off. If you don't have time for this one, no worries. 

And in case you do have time, here is the context:
The links that are causing problems are hyperlinks we add to the description of weeks in courses or in the lessons themselves. We had it working so that the links opened the right url, but stakeholders wanted them to open on a separate browser window. For some reason, this was causing problems and not working.

**Comment by GeorgeBellTMH** [comment]
Note: I was able to add it to the editor, but then it wouldn't save anymore (error was happening somewhere when it was serializing and deserializing the blocks)...I think there is some extra code needed to tell it what to do on either serialization or deserialization....editor change was reverted...

**Comment by lucastbelem** [comment]
@GeorgeBellTMH @JonEsparaz I can't tell from your latest comment, @GeorgeBellTMH, but this seems to be working now on dev!! Woot woot!
