### ISSUE TITLE
Course activities not working

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#811]
@itbel knows what the problem is, but it seems like it's something that needs to be done on your end, @GeorgeBellTMH

**Comment by GeorgeBellTMH** [comment]
Try again.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH still not working.

**Comment by itbel** [comment]
@GeorgeBellTMH Missing authentication for the lambda to use the API. `amplify/backend/function/jcHandleActivity/src/index.js` 
See lines 74-76. I did not use Secrets Manager for my testing, `authenticate()` is not currently being used as I did not test this myself.

**Comment by GeorgeBellTMH** [comment]
Test again.

**Comment by itbel** [comment]
It seems that this is still broken. I followed steps to create a lesson in a course and activityByGroup is still not returning any activities.  
![Capture](https://user-images.githubusercontent.com/42515854/112727386-ac60f100-8ef8-11eb-9889-76a6c2a84498.PNG)
