### ISSUE TITLE
Mobile updates

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#817]
I was looking through our mock ups today and there is a lot of stuff on mobile that we need to modify. 

The other of the components is different that what's implemented in the profile, for example.

Also, the home screen isn't supposed to be a replica of the dashboard. The mobile experience was always designed to be primarily about connections (i.e. messaging) and only secondarily about the other stuff (events/groups/resources/courses). Could we remove all of the carousels from the mobile view and just leave the profile directory? I think that alone would improve that experience quite a bit.

Also, the DM experience is very different. Currently messages display below the person you click on to talk to. But in the design, clicking on that person takes you in to the message screen with that person. @GeorgeBellTMH is there a reason why that's not possible now or is this something we could do, but just would need to put the work in?

**Comment by mmacedom** [comment]
@lucastbelem I removed the carousels from the dashboard. Please let me know who to proceed with the DMs. Thanks

**Comment by GeorgeBellTMH** [comment]
I'm going to hold off on delivering this one for now, I want to check a bunch of stuff before I do it...Mateus just make sure you don't commit more to this PR (and create your next branch from master)...

**Comment by lucastbelem** [comment]
Closing for now as Nathan's redesign will impact this.
