### ISSUE TITLE
Email notification on/off

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#821]
I don't think the on/off toggles in settings work yet...facilitators for the course are asking if it's possible for them to only receive email notifications for DMs? Or if it's all or nothing for now, they'd rather get none.

**Comment by GeorgeBellTMH** [comment]
I'm pretty sure this should work now....please test by flicking the switches both ways....and posting between...

**Comment by GeorgeBellTMH** [comment]
(obviously post as a different user, since you shouldn't get notifications for your own posts anyways)
