### ISSUE TITLE
Multiple products issue

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#827]
So, I need to create a product for courses to let people in right?
But when I do that, it takes over on the billing page and people trying to subscribe for curriculum can't do so. 
How do I create a course product without making it the default product?

**Comment by GeorgeBellTMH** [comment]
Products now have a "Show on Login Page" switch...if it is true and enabled it will be the homepage....right now it just picks the first one it finds with those settings....so only have it once...

Course products just set show on login page to false.
