### ISSUE TITLE
Chat drawer messages not triggering email notifications

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#837]
Ran tests this afternoon and found that messages posted on the chat drawer were not triggering email messages.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713125522)

**Comment by GeorgeBellTMH** [comment]
This is fixed, issue was that the lambda did not download node_modules before uploading to aws...unsure why...resolved for now, may re-occur...

**Comment by lucastbelem** [comment]
Tested everything in dev and everything is working, except this...chat drawer not triggering email notification is re-occuring.

**Comment by lucastbelem** [comment]
@laurengermain can you pls verify? Is this still an issue?

**Comment by laurengermain** [comment]
It doesn't seem to be an issue - I received an email after sending a chat message just now.
