### ISSUE TITLE
UI for messages

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#840]
@mmacedom I added you to a course on beta. Can you take a look at assignment submissions? The UI looks wonky because there are so many messages. Anything you can do to improve it?

**Comment by mmacedom** [comment]
@lucastbelem Looking at this now.

**Comment by mmacedom** [comment]
@lucastbelem Also, can you clarify a bit more what is wonky on that screen besides the number of messages?

**Comment by lucastbelem** [comment]
I think I just mean that the messages spill out of the container. I don't
know if the container should extend with the messages or if the messages
should scroll...or even if it's actually ok as is.

**Comment by mmacedom** [comment]
@lucastbelem I was able to get in on incognito on beta.jesuscollective and saw a number of courses active. What is the course this is happening on?

**Comment by lucastbelem** [comment]
Check "April 7 test 2"

**Comment by mmacedom** [comment]
@lucastbelem this is what I'm seeing... I'm not exactly sure where it's spilling out of the container. Am I in the right assignment?
<img width="476" alt="Screen Shot 2021-04-07 at 10 10 34 PM" src="https://user-images.githubusercontent.com/24467324/113957895-1f6a4180-97ee-11eb-83e2-0312ba95c216.png">

**Comment by lucastbelem** [comment]
This looks right. The messages are contained appropriately within their own containers. But the 2/3 column on which all of the messages sit end before the messages do. So if you keep scrolling, it just looks like the messages are not well placed. This is only an issue once we have more messages than the height of the 2/3 right hand column.

**Comment by mmacedom** [comment]
Sorry, I'm not quite seeing the issue. Do you mind sending a screen shot? This is what I'm seeing when I scroll all the way down.
<img width="516" alt="Screen Shot 2021-04-07 at 10 30 14 PM" src="https://user-images.githubusercontent.com/24467324/113959439-e384ab80-97f0-11eb-9f98-5a2165f09d4c.png">

**Comment by lucastbelem** [comment]
@mmacedom I'm gonna close this. I also cannot see the issue...maybe I imagined it. I think I saw it when another user shared his screen, but he doesn't seem to have a problem now.
