### ISSUE TITLE
Cannot link "respond" activity to "assignment" activity in real time

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#844]
Hey @JonEsparaz could you please take a look at this? The changes you made are in the dev environment still, in case you need to know for replicating the issue.

<img width="1440" alt="Screen Shot 2021-04-12 at 6 14 35 PM" src="https://user-images.githubusercontent.com/48295718/114469443-2cef4500-9bbb-11eb-96cd-c5f30357e46f.png">

**Comment by JonEsparaz** [comment]
Try reloading. I can link the assignment to the respond activity now:
![image](https://user-images.githubusercontent.com/48423418/114469859-e221fd00-9bbb-11eb-9db0-43568f4f5e75.png)

I assume the issue is the data is not updating in realtime - will take a look.

**Comment by lucastbelem** [comment]
@JonEsparaz that did the trick. Not a massive issue now that I know it can reload. Whenever you have time to tackle the real timeness of it is great :)
