### ISSUE TITLE
Calendar legend doesn't work

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#846]
I don't know if this is a new bug or an old we never addressed, but the legend doesn't match what is seen in the calendar. In the picture below, you'll see that according to the legend, there is a zoom assignment on April 13th. However, the actual assignment is not a zoom type. 

<img width="321" alt="Screen Shot 2021-04-12 at 6 22 40 PM" src="https://user-images.githubusercontent.com/48295718/114470176-78eeb980-9bbc-11eb-95e9-705a678a2140.png">

Can we:
- [ ] Make the legend work so that the coloured dots match the type of assignment on a date?
- [ ] For days with more than 1 lesson type, can we make a dot that is filled half with one colour and half with the other colour? Is this too overkill? Too little? @mmacedom do you have thoughts on this from a UI standpoint?

**Comment by lucastbelem** [comment]
Closing for #795.

**Comment by JonEsparaz** [comment]
> For days with more than 1 lesson type, can we make a dot that is filled half with one colour and half with the other colour?

The best I can do is multiple dots:
![image](https://user-images.githubusercontent.com/48423418/114470961-c7e91e80-9bbd-11eb-8ee7-62b1dc3fcd1a.png)

(Assuming this actually works on React Native Web - it should).
