### ISSUE TITLE
How does the "sort lessons" button work?

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#847]
When editing a course, there is now a "sort lessons" button. How does it work?

**Comment by JonEsparaz** [comment]
As it stands, the lessons appear in the order you created them. Clicking "Sort Lessons" will re-sort by date (earliest first). Additionally, it ensures that the lessons numbers are synchronized.

It is purely beneficial (and recommended) to just click the button whenever you add or remove lesson.

**Comment by lucastbelem** [comment]
Perfect! Thank you sir!!

**Comment by JonEsparaz** [comment]
@lucastbelem one clarifying note: the button sorts lessons for the selected week (not the entire course). 

If you want to sort lessons for the entire course, you need to do every week individually.

**Comment by lucastbelem** [comment]
Gotcha.
