### ISSUE TITLE
"Response" type lessons UI for Admins needs improvements

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#848]
@mmacedom if you look at the screenshot below, you'll see that the area where "Review assignments" appears is too tight. That should be almost the length of the screen. Once assignments are posted, then the area shrinks to that size, displays all assignments to load, and another column appears on the right for all of the messages. Can you take a look and see if you can adjust this based on there being no assignments submitted?

**Comment by mmacedom** [comment]
@lucastbelem where's the screenshot? Can you resend?

**Comment by mmacedom** [comment]
check into beta responses

**Comment by mmacedom** [comment]
@lucastbelem I figured out the issue (needed a min width for the empty container) and have pushed the fix in my first open PR
