### ISSUE TITLE
Sort lessons bug

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#852]
When I click "sort lessons", the lessons sort appropriately. However, participants do not see the messages in the appropriately sorted order. And when I (as the course admin) refresh my page, the lessons go back to being un-sorted.

**Comment by JonEsparaz** [comment]
I'll take a look. Are "the messages" the lessons?

**Comment by JonEsparaz** [comment]
Ok I made a mistake here. The button is necessary, but it only fixes the lesson numbers - we need to actually sort the lesson elsewhere in the code.

I will add the sorting function and re-name the button "sync lesson numbers".

**Comment by JonEsparaz** [comment]
> I'll take a look. Are "the messages" the lessons?

Pretty sure we're talking about the lessons here.

**Comment by lucastbelem** [comment]
Yeah, my bad...lessons, not messages.
