### ISSUE TITLE
Course Week Intro Text and Lessons Overlap

### ISSUE THREAD

**Issue by JonEsparaz** [jesus-collective/mobile#859]
This is from "Week 3: Roots of the False Self" in "The Inner Life of an Effective Leader" on the beta environment.

![image](https://user-images.githubusercontent.com/48423418/114892613-eed06c00-9dda-11eb-8a6a-d6a785485ce4.png)

**Comment by lucastbelem** [comment]
@JonEsparaz good catch! @mmacedom any chance you can tackle this today?

**Comment by mmacedom** [comment]
@JonEsparaz What's the screen size of the screenshot? I'm assuming it's much larger than a 13' laptop. This is what I see on the laptop. 
<img width="1232" alt="Screen Shot 2021-04-15 at 10 13 18 PM" src="https://user-images.githubusercontent.com/24467324/114961998-ed815c80-9e37-11eb-8b25-8213f2d23fbd.png">

**Comment by JonEsparaz** [comment]
> What's the screen size of the screenshot? 

The monitor is 1920x1080.

**Comment by mmacedom** [comment]
@JonEsparaz Can you still see the issue? I'm trying to replicate it and can't at that screen width 
<img width="1430" alt="Screen Shot 2021-04-15 at 10 27 51 PM" src="https://user-images.githubusercontent.com/24467324/114963065-e8251180-9e39-11eb-9761-49a9c3141fe6.png">

**Comment by JonEsparaz** [comment]
Hmmm. Now this is interesting.

Looks like you're using Chrome @mmacedom. I can't reproduce on Chrome either, but I can consistently reproduce on Firefox and Edge.

**Comment by mmacedom** [comment]
Thanks @JonEsparaz

**Comment by mmacedom** [comment]
@JonEsparaz @lucastbelem I just open a new PR to fix this.
