### ISSUE TITLE
Message board attachments

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#863]
As per #160, I asked Jon to remove the editor. However, that made it impossible to upload attachments. We need to revert that only to the extend of giving users the ability to upload attachments (as they can on courses).

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=713124936)

**Comment by lucastbelem** [comment]
@laurengermain I believe when we submitted the facelift we fixed this. Can you confirm that message boards have editor tools? i.e. bold, italics, etc.

**Comment by laurengermain** [comment]
Confirmed, they have editor tools.
