### ISSUE TITLE
Members should only show once

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#87]
Members are showing up multiple times in the same group, likely need to ensure they are unique. May also need to update the join/leave queries to check if items exist, or to delete all instead of just one of them.

**Comment by JonEsparaz** [comment]
This is likely resolved going forward by #76 and #78 going forward, but we can add error checking on the queries too.

**Comment by JonEsparaz** [comment]
@GeorgeBellTMH I've played around a little, and it's pretty much impossible for you to join twice. Do you still want to add uniqueness checks?

**Comment by GeorgeBellTMH** [comment]
I’ll clear the membership table...

Sent from my iPhone

On Jun 2, 2020, at 5:32 PM, Jon Esparaz <notifications@github.com> wrote:

﻿

@GeorgeBellTMH<https://github.com/GeorgeBellTMH> I've played around a little, and it's pretty much impossible for you to join twice. Do you still want to add uniqueness checks?

**Comment by GeorgeBellTMH** [comment]
Membership table is cleared...
