### ISSUE TITLE
Change copy on Sign in Page

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#872]
Welcome to One Story

We are looking forward to partnering with you as you introduce kids and youth in your community to Jesus.  
To access our content you will need to create a Jesus Collective account. 
One Story’s partnership with [Jesus Collective](https://jesuscollective.com/) allows us to not only make all of our resources available online in a convenient easy to assess way, but also provides you the benefit of connecting with other One Story users to give feedback, share ideas and ask questions.  
![](https://storage.www.wrike.com/filemeta/thumb100/F216721360.A623666)![](https://storage.www.wrike.com/filemeta/thumb100/F216721228.A623666)

┆Attachments: <a href="https://storage.www.wrike.com/attachments/216721228?accountId=623666">OS Signup_FROM.jpg</a> | <a href="https://storage.www.wrike.com/attachments/216721360?accountId=623666">OS Signup_TO.jpg</a>

**Comment by lucastbelem** [comment]
@GeorgeBellTMH confirming what we discussed today:

- [ ] add paragraph to login page
- [ ] add paragraph to "are you an individual or org" page
- [ ] On login page, change "sign in to Jesus Collective" with "Welcome to One Story".
