### ISSUE TITLE
Curriculum-only users should land right inside curriculum rather than the dashboard

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#873]
Chris reports that this is not functioning for him. He's landing on the dashboard when he logs in. I checked his permissions. He's got:

VerifiedUser
SubscriptionValid
SubscriptionEarlyyears
SubscriptionKids
SubscriptionYouth

**Comment by GeorgeBellTMH** [comment]
This is working for me...not sure the problem...
