### ISSUE TITLE
Unable to navigate to course screen

### ISSUE THREAD

**Issue by itbel** [jesus-collective/mobile#890]
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=720193518)

**Comment by lucastbelem** [comment]
@itbel @GeorgeBellTMH unfortunately, it didn't get fixed.

**Comment by GeorgeBellTMH** [comment]
Just uploading it now.

**Comment by lucastbelem** [comment]
Sorry...I saw you merged and I thought it was already online...my bad.

**Comment by lucastbelem** [comment]
@GeorgeBellTMH let me know when it's done and I'll get it tested.
