### ISSUE TITLE
Card Image glitch

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#892]
Image was added to a card on the overview page (master supply list). However, the card is not sized correctly and is appearing out of bounds.

![image (3)](https://user-images.githubusercontent.com/48295718/125285708-ed82e280-e2e8-11eb-9ee0-c81bb8b7077e.png)

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=721046331)

**Comment by lucastbelem** [comment]
@laurengermain another one for testing.

**Comment by laurengermain** [comment]
I don't think this has been fixed
![Screen Shot 2022-12-16 at 1 30 45 PM](https://user-images.githubusercontent.com/89869101/208165286-3ce6be99-cde1-4860-a435-0c9050a82a9b.png)

**Comment by lucastbelem** [comment]
Irelevant
