### ISSUE TITLE
Eventbrite registration

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#915]
We need to connect the user when signing up for an event with eventbrite. Can we make it so that when the user clicks "attend" on an event:

* [x] they are added to the event as "attending".
* [x] a new window opens taking them to the eventbrite link for that event
* [x] bonus points if we can build a quick modal overtop and have the form embedded right in the platform.

**Due October 15.**

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=770104567)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH any idea why this event isn't showing on the platform?
<img width="1438" alt="Screen Shot 2021-11-10 at 5 12 03 PM" src="https://user-images.githubusercontent.com/48295718/141202124-504e3a2d-cf0c-4367-bcfd-c028685583de.png">

**Comment by GeorgeBellTMH** [comment]
Did you follow the instructions above?

**Comment by lucastbelem** [comment]
They wouldn't have because this event existed before our implementation.

I don't have access, but I think I follow the instructions. Basically, for an event to go to the platform, it needs to be a Partner ticket event or a One Story ticket event, right? If so, I can tell them to fix it.

**Comment by GeorgeBellTMH** [comment]
Yup.
