### ISSUE TITLE
Download buttons not working 

### ISSUE THREAD

**Issue by laurengermain** [jesus-collective/mobile#919]
All of the red download buttons on the One Story curriculum pages aren't working. Both admins and non-admins click on them and nothing happens or downloads.
![Screen Shot 2021-10-14 at 4 03 39 PM](https://user-images.githubusercontent.com/89869101/137387659-54f485d3-266d-4b69-81e3-fafc245debae.png)

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=773459553)

**Comment by lucastbelem** [comment]
Same problem as #918

**Comment by GeorgeBellTMH** [comment]
Fixed...

**Comment by GeorgeBellTMH** [comment]
Issue is that v5 of react-native-dropdown-picker doesn't seem to work...
