### ISSUE TITLE
MainUserGroup is empty for many users

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#923]
As per the convo we had, I send GeorgeBellTMH an email with email addresses to check.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=781507971)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH can you pls solve this one? Many people aren't appearing on the map and I think it's because of this.

**Comment by GeorgeBellTMH** [comment]
I believe this is fixed now

**Comment by lucastbelem** [comment]
@GeorgeBellTMH how did you tackle this? Did you make adjustments to how partners appear on the map or did you solve the part about showing "partner" or "one story" or "admin" where it currently says "inactive" in their profiles? If the latter, is it supposed to be solved for all users or just users signing up going forward? I asked because I just checked and I'm still seeing "inactive" for a number of users.

**Comment by GeorgeBellTMH** [comment]
Closing this...
