### ISSUE TITLE
Invited users not setup correctly with stripe

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#925]
There was a bug where we would attempt to create a stripe user when a user was invited from the admin page. The stripe user would have all the details of the new user, but would be associated with the admin user instead of the created user. 

This would show up with invited users potentially getting the payment screen, and a second stripe user potentially being created. 

Going forward stripe users should be created and linked correctly. 

There may need to be some work to delete users that appear twice in stripe (just delete the one that has metadata with a userid that is one of the admin users). Or just leave the user and it shouldn't be used....

Cc: 
@lucastbelem @chrstygratton @ZulemaTMH

**Comment by lucastbelem** [comment]
@GeorgeBellTMH is "admin user" in this case the user who invited that new user?

**Comment by GeorgeBellTMH** [comment]
Yup
