### ISSUE TITLE
Ability to change email

### ISSUE THREAD

**Issue by GeorgeBellTMH** [jesus-collective/mobile#926]
This should be working from the admin section of dev right now...

I had to modify a bunch of things to make it work...please test:

1. Invitations
1. Creating a subscription
1. All admin page functionality

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=783623333)

**Comment by lucastbelem** [comment]
@GeorgeBellTMH this is great, thank you!

What do you mean by "creating a subscription"? Do you mean create a new user account and purchase curriculum and verify that the data went to stripe and returned to the platform?

**Comment by GeorgeBellTMH** [comment]
Yup
