### ISSUE TITLE
Members' profile pics in a group or event

### ISSUE THREAD

**Issue by lucastbelem** [jesus-collective/mobile#93]
A person's profile picture in a group or event shows up too far apart from the others in comparison to design. Here is a screenshot: 
<img width="441" alt="Screen Shot 2020-06-01 at 10 54 30 AM" src="https://user-images.githubusercontent.com/48295718/83421604-5ca7bb00-a3f6-11ea-8484-c9a3559f2639.png">

**Comment by mmacedom** [comment]
@lucastbelem The issue has been taken care of. Can you confirm on your end?

**Comment by lucastbelem** [comment]
Looks beautiful!
